-- SANITIZED PUBLIC VERSION
-- Direct student/borrower identifiers and hard-coded student data have been removed from public output.
-- Literal student ID/SSN lists have been replaced with bind parameters where applicable.
-- Schema fields may remain internally where required for joins, filtering, or comparison logic.
-- Do not commit query results or exports containing student records.

--MANUAL OVERRIDES FOR BUDGET

SELECT NULL AS STUDENT_ID, NULL AS STUDENT_FIRST_NAME, NULL AS STUDENT_LAST_NAME,
ROBUSDF_VALUE_202,

CASE WHEN ROBUSDF_vALUE_202 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202560'
AND RBRAPBC_PBCP_CODE = 'R+B') END SMR_ON_CAMPUS_HOUSING,

CASE WHEN ROBUSDF_vALUE_202 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202560'
AND RBRAPBC_PBCP_CODE = 'R+BF') END SMR_OFF_CAMPUS_HOUSING,

 ROBUSDF_VALUE_203,
 CASE WHEN ROBUSDF_vALUE_203 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202580'
AND RBRAPBC_PBCP_CODE = 'R+B') END FAL_ON_CAMPUS_HOUSING,

CASE WHEN ROBUSDF_vALUE_203 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202580'
AND RBRAPBC_PBCP_CODE = 'R+BF') END FALL_OFF_CAMPUS_HOUSING,
 ROBUSDF_VALUE_204,
  CASE WHEN ROBUSDF_vALUE_204 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202610'
AND RBRAPBC_PBCP_CODE = 'R+B') END SPR_ON_CAMPUS_HOUSING,

CASE WHEN ROBUSDF_vALUE_204 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202610'
AND RBRAPBC_PBCP_CODE = 'R+BF') END SPR_OFF_CAMPUS_HOUSING,
 
 ROBUSDF_VALUE_229,
   CASE WHEN ROBUSDF_vALUE_229 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202560'
AND RBRAPBC_PBCP_CODE = 'PERS') END SMR_PERS,

 ROBUSDF_VALUE_230,
    CASE WHEN ROBUSDF_vALUE_230 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202580'
AND RBRAPBC_PBCP_CODE = 'PERS') END FAL_PERS,

 ROBUSDF_VALUE_231,
     CASE WHEN ROBUSDF_vALUE_231 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202610'
AND RBRAPBC_PBCP_CODE = 'PERS') END SPR_PERS,

 ROBUSDF_vALUE_236,
  CASE WHEN ROBUSDF_vALUE_236 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202560'
AND RBRAPBC_PBCP_CODE = 'B+S') END SMR_BOOKS,
 ROBUSDF_VALUE_237,
   CASE WHEN ROBUSDF_vALUE_237 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202580'
AND RBRAPBC_PBCP_CODE = 'B+S') END FAL_BOOKS,
 ROBUSDF_VALUE_238,
   CASE WHEN ROBUSDF_vALUE_238 IS NOT NULL
THEN (SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PIDM = ROBUSDF_PIDM
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PERIOD = '202610'
AND RBRAPBC_PBCP_CODE = 'B+S') END SPR_BOOKS



FROM ROBUSDF

LEFT JOIN SPRIDEN
ON SPRIDEN_PIDM = ROBUSDF_PIDM
AND SPRIDEN_CHANGE_IND IS NULL

WHERE ROBUSDF_AIDY_CODE = '2526'
AND (ROBUSDF_VALUE_202 IS NOT NULL
OR ROBUSDF_VALUE_203 IS NOT NULL
OR ROBUSDF_VALUE_204 IS NOT NULL
OR ROBUSDF_VALUE_229 IS NOT NULL
OR ROBUSDF_VALUE_230 IS NOT NULL
OR ROBUSDF_VALUE_231 IS NOT NULL
OR ROBUSDF_vALUE_236 IS NOT NULL
OR ROBUSDF_VALUE_237 IS NOT NULL
OR ROBUSDF_VALUE_238 IS NOT NULL)