-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Schema fields used internally for joins/comparisons are retained where required by the query logic.
-- Do not commit query results or exports containing student records.

SELECT DISTINCT
        RFRBASE_FUND_CODE AS FUND, RFRBASE_FUND_TITLE AS FUND_TITLE, 
        RORENRL_CONSORTIUM_IND AS CONSORTIUM_IND, 
        RPRATRM_OFFER_AMT AS OFFER_AMT, 
        RPRATRM_ACCEPT_AMT AS ACCEPT_AMT, 
        RPRATRM_PAID_AMT AS PAID_AMT, 
        RPRATRM_AUTHORIZE_AMT AS AUTH_AMT,
        RPRATRM_MEMO_AMT AS MEMO_AMT, 
        (SELECT RORENRL_FINAID_ADJ_HR FROM RORENRL WHERE RORENRL_PIDM = SPRIDEN_PIDM AND RORENRL_ENRR_CODE = 'STANDARD' AND RORENRL_TERM_CODE = :TERM) AS FROZEN_HRS,
        (SELECT RORENRL_FINAID_ADJ_HR FROM RORENRL WHERE RORENRL_PIDM = SPRIDEN_PIDM AND RORENRL_ENRR_CODE = 'REPEAT' AND RORENRL_TERM_CODE = :TERM) AS FROZEN_REPEAT_HRS,
        (SELECT SUM(SFRSTCR_BILL_HR) FROM SFRSTCR WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE = :TERM AND SFRSTCR_BILL_HR >0) AS BILLED_HRS,
        SGBSTDN_LEVL_CODE AS STUDENT_LEVEL,
        RPRAWRD_OFFER_AMT AS YEAR_OFFER_AMOUNT, 
        RPRAWRD_ACCEPT_AMT AS YEAR_ACCEPT_AMOUNT, 
        RPRAWRD_PAID_AMT AS YEAR_PAID_AMOUNT
FROM SPRIDEN
LEFT JOIN SGBSTDN ON SPRIDEN_PIDM = SGBSTDN_PIDM
LEFT JOIN RPRATRM ON RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_AIDY_CODE = :AIDY AND RPRATRM_PERIOD = :TERM AND RPRATRM_OFFER_AMT > 0
LEFT JOIN RPRAWRD ON RPRAWRD_PIDM = SPRIDEN_PIDM AND RPRAWRD_FUND_CODE = RPRATRM_FUND_CODE AND RPRAWRD_AIDY_CODE = :AIDY AND RPRAWRD_OFFER_AMT > 0
LEFT JOIN RFRBASE ON RPRATRM_FUND_CODE = RFRBASE_FUND_CODE AND RPRAWRD_FUND_CODE = RFRBASE_FUND_CODE
LEFT JOIN RORENRL ON RORENRL_PIDM = SPRIDEN_PIDM
WHERE SPRIDEN_CHANGE_IND IS NULL
AND (RPRATRM_FUND_CODE LIKE '_I%' OR RPRATRM_FUND_CODE LIKE '_P%' OR RPRATRM_FUND_CODE LIKE '_S%' OR RPRATRM_FUND_CODE LIKE '_F%')
AND RPRATRM_PERIOD = :TERM
AND RPRAWRD_AIDY_CODE = :AIDY
AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z WHERE Z.SGBSTDN_PIDM = SPRIDEN_PIDM AND Z.SGBSTDN_TERM_CODE_EFF <= :TERM)