SELECT
SPRIDEN_ID,
'00305100' AS Reporting_OE_Code,
'01' AS Reporting_OE_Code_Suffix,
'2024' AS ACADEMIC_YEAR,
SSN,
DOB,
LAST_NAME,
FIRST_NAME,
'00305100' AS SCHOOL_ATTENDING_FALL_CODE,
'01' AS SCHOOL_ATTENDING_FALL_SUFFIX,
--'C = Bachelors Degree - All Other Majors (C)' AS PROGRAM_OF_STUDY_FALL_CODE,
NULL AS PROGRAM_OF_STUDY_FALL_CODE,
NULL AS CLASS_LEVEL_FALL,
NULL AS ENROLLMENT_STATUS_FALL,
FALL_ENROLLMENT_MODE,
NULL AS SCHOOL_ATTENDING_WINTER_CODE,
NULL AS SCHOOL_ATTENDING_WINTER_SUFFIX,
NULL AS PROGRAM_OF_STUDY_WINTER_CODE,
NULL AS CLASS_LEVEL_WINTER,
NULL AS ENROLLMENT_STATUS_WINTER,
NULL AS ENROLLMENT_MODE_STATUS_WINTER,
'00305100' AS SCHOOL_ATTENDING_SPRING_CODE,
'01' AS SCHOOL_ATTENDING_SPRING_SUFFIX,
--'Bachelors Degree - All Other Majors (C)' AS PROGRAM_OF_STUDY_SPRING_CODE,
NULL AS PROGRAM_OF_STUDY_SPRING_CODE,
NULL AS CLASS_LEVEL_SPRING,
NULL AS ENROLLMENT_STATUS_SPRING,
ENROLLMENT_MODE_STATUS_SPRING,
NULL AS FULL_YEAR_PROGRAM_INDICATOR,
--CASE WHEN ALL_TERMS_AWARD_CANCEL_REINSTATE IN ('CNCL', 'WDCL', 'SYSC')
--THEN 'CANCEL'
--END AS ALL_TERMS_AWARD_CANCEL_REINSTATE,
--NULL AS FULL_YEAR_PROGRAM_INDICATOR,
--CASE WHEN FALL_AWARD_CANCEL_REINSTATE IN ('CNCL', 'WDCL', 'SYSC')
--THEN 'CANCEL'
--END AS FALL_AWARD_CANCEL_REINSTATE,
--NULL AS WINTER_AWARD_CANCEL_REINSTATE,
--CASE WHEN SPRING_AWARD_CANCEL_REINSTATE IN ('CNCL', 'WDCL', 'SYSC')
--THEN 'CANCEL'
--END AS SPRING_AWARD_CANCEL_REINSTATE,
NULL AS ALL_TERMS_AWARD_CANCEL_REINSTATE,
NULL AS FALL_AWARD_CANCEL_REINSTATE,
NULL AS WINTER_AWARD_CANCEL_REINSTATE,
NULL AS SPRING_AWARD_CANCEL_REINSTATE,
NULL AS ALL_TERMS_AWARD_REJECT_FOR_PROGRESS,
NULL AS FALL_AWARD_REJECT_FOR_PROGRESS,
NULL AS WINTER_AWARD_REJECT_FOR_PROGRESS,
NULL AS SPRING_FAILURE_TO_PROGRESS

FROM
(SELECT DISTINCT SPRIDEN_ID,
SPRIDEN_FIRST_NAME AS FIRST_NAME,
SPRIDEN_LAST_NAME AS LAST_NAME,
RPRAWRD_AIDY_CODE AS ACADEMIC_YEAR,
SPBPERS_SSN AS SSN,

(SELECT REPLACE (TO_CHAR(SPBPERS_BIRTH_DATE, 'MMDDYYY'), '/', '')
FROM SPBPERS
WHERE SPBPERS_PIDM = RPRAWRD_PIDM) AS DOB,

--SORLCUR_PROGRAM AS PROGRAM_OF_STUDY_FALL_CODE,
SORLCUR_LEVL_CODE AS CLASS_LEVEL_FALL,
--SGBSTDN_LEVL_CODE AS CLASS_LEVEL_FALL
ROBUSDF_VALUE_55 AS ENROLLMENT_STATUS_FALL,
ROBUSDF_VALUE_56 AS FALL_ENROLLMENT_MODE,
ROBUSDF_VALUE_59 AS ENROLLMENT_STATUS_SPRING,
ROBUSDF_VALUE_60 AS ENROLLMENT_MODE_STATUS_SPRING,

(SELECT D.RPRAWRD_AWST_CODE
FROM RPRAWRD D
WHERE rownum = 1 
AND D.RPRAWRD_PIDM = RPRAWRD_PIDM
AND D.RPRAWRD_FUND_CODE IN ('GSNPPP','GSNPPF')
AND D.RPRAWRD_AIDY_CODE = :AIDY) AS ALL_TERMS_AWARD_CANCEL_REINSTATE,
--AND D.RPRAWRD_AWST_CODE = 'CNCL') 

SORLCUR_ROLL_IND AS FULL_YEAR_PROGRAM_INDICATOR,

(SELECT E.RPRATRM_AWST_CODE
FROM RPRATRM E
WHERE rownum = 1
AND E.RPRATRM_PIDM = RPRAWRD_PIDM
AND E.RPRATRM_FUND_CODE IN ('GSNPPP','GSNPPF')
AND E.RPRATRM_PERIOD = :FAL_TERM) AS FALL_AWARD_CANCEL_REINSTATE,
--AND E.RPRATRM_AWST_CODE = 'CNCL') 

(SELECT F.RPRATRM_AWST_CODE
FROM RPRATRM F
WHERE rownum = 1
AND F.RPRATRM_PIDM = RPRAWRD_PIDM
AND F.RPRATRM_FUND_CODE IN ('GSNPPP','GSNPPF')
AND F.RPRATRM_PERIOD = :SPR_TERM) AS SPRING_AWARD_CANCEL_REINSTATE,
--AND F.RPRATRM_AWST_CODE = 'CNCL')

(SELECT A.RORSAPR_SAPR_CODE
FROM RORSAPR A
WHERE A.RORSAPR_PIDM = RPRAWRD_PIDM
AND A.RORSAPR_SAPR_CODE_CALC LIKE 'C%'
AND A.RORSAPR_TERM_CODE IN (:FAL_TERM, :SPR_TERM)) AS FULL_YEAR_FAILURE_TO_PROGRESS,

(SELECT B.RORSAPR_SAPR_CODE
FROM RORSAPR B
WHERE B.RORSAPR_PIDM = RPRAWRD_PIDM
AND B.RORSAPR_SAPR_CODE_CALC LIKE 'C%'
AND B.RORSAPR_TERM_CODE = :FAL_TERM) AS FALL_AWARD_REJECT_FOR_PROGRESS,

(SELECT C.RORSAPR_SAPR_CODE
FROM RORSAPR C
WHERE C.RORSAPR_PIDM = RPRAWRD_PIDM
AND C.RORSAPR_SAPR_CODE_CALC LIKE 'C%'
AND C.RORSAPR_TERM_CODE = :SPR_TERM) AS SPRING_FAILURE_TO_PROGRESS

FROM RPRAWRD

LEFT JOIN SPRIDEN
ON SPRIDEN_PIDM = RPRAWRD_PIDM
AND SPRIDEN_CHANGE_IND IS NULL

LEFT JOIN SPBPERS
ON SPBPERS_PIDM = RPRAWRD_PIDM

LEFT JOIN SORLCUR
ON SORLCUR_PIDM = RPRAWRD_PIDM

LEFT JOIN SGBSTDN
ON SGBSTDN_PIDM = RPRAWRD_PIDM

LEFT JOIN ROBUSDF
ON ROBUSDF_PIDM = RPRAWRD_PIDM
AND ROBUSDF_AIDY_CODE = RPRAWRD_AIDY_CODE

WHERE ROBUSDF_VALUE_56 IS NOT NULL --FALL PHEAA ENROLLMENT MODE
AND RPRAWRD_AIDY_CODE = :AIDY
AND RPRAWRD_FUND_CODE IN ('GSNPPP','GSNPPF')
--AND RPRAWRD_OFFER_AMT > 0)
AND SORLCUR_SEQNO =
                   (SELECT MAX (S.SORLCUR_SEQNO)
                           KEEP (DENSE_RANK FIRST
                                 ORDER BY
                                     S.SORLCUR_PRIORITY_NO ASC,
                                     S.SORLCUR_TERM_CODE DESC,
                                     S.SORLCUR_SEQNO DESC)
                           FROM SORLCUR S
                           WHERE     S.SORLCUR_CACT_CODE = 'ACTIVE'
                                AND S.SORLCUR_LMOD_CODE = 'LEARNER'
                                AND S.SORLCUR_PIDM = RPRAWRD_PIDM
                                AND SB_CURRICULUM.F_FIND_CURRENT_ALL_IND (
                                   S.SORLCUR_PIDM, ----ADD PIDM HERE TO SPEED TEST LOOK UP
                                   S.SORLCUR_LMOD_CODE,
                                   S.SORLCUR_TERM_CODE,
                                   S.SORLCUR_KEY_SEQNO,
                                   S.SORLCUR_PRIORITY_NO,
                                   S.SORLCUR_SEQNO,
                                   '',' ','20'|| SUBSTR (LTRIM (TO_CHAR ( :AIDY, '0009')),3,2)|| '10') = 'Y'))
                                   
                WHERE SPRIDEN_ID NOT IN ('811232850', 
                      '811302483',
                '811348917',
                  '811093242',
                    '811204465',
                       '811212647',
                              '811222243',
                              '811192548')

                            --ORDER BY 7, 8