Select DISTINCT SPRIDEN_PIDM, SPRIDEN_ID, SPRIDEN_FIRST_NAME, SPRIDEN_LAST_NAME, RORSTAT_APRD_CODE APRD, RORSTAT_PGRP_CODE PGRP,

(Select SGBSTDN_RESD_CODE
from SGBSTDN
where SGBSTDN_PIDM = RORSTAT_PIDM
and SGBSTDN_TERM_CODE_EFF = 
(Select MAX(A.SGBSTDN_TERM_CODE_EFF)
from SGBSTDN A
where A.SGBSTDN_PIDM = RORSTAT_PIDM
and A.SGBSTDN_TERM_CODE_EFF <='202510')) RES,

E.RORSAPR_SAPR_CODE SMR_SAP, F.RORSAPR_SAPR_CODE FAL_SAP, G.RORSAPR_SAPR_CODE SPR_SAP, RORSTAT_PCKG_REQ_COMP_DATE,
A.RPRAWRD_FUND_CODE SEOG, A.RPRAWRD_OFFER_AMT SEOG_OFFER, A.RPRAWRD_PAID_AMT SEOG_PAID, B.RPRAWRD_PAID_AMT PELL_PAID, RCRAPP2_PELL_PGI PELL_EFC, 

(Select SUM(RPRAWRD_OFFER_AMT)
from RPRAWRD
where RORSTAT_PIDM = RPRAWRD_PIDM
and RORSTAT_AIDY_CODE = RPRAWRD_AIDY_CODE
and (RPRAWRD_FUND_CODE like 'GIA%'
or RPRAWRD_FUND_CODE Like 'GEA%'))ATH_OFFER,

(Select SUM(RPRAWRD_PAID_AMT)
from RPRAWRD
where RORSTAT_PIDM = RPRAWRD_PIDM
and RORSTAT_AIDY_CODE = RPRAWRD_AIDY_CODE
and (RPRAWRD_FUND_CODE like 'GIA%'
or RPRAWRD_FUND_CODE Like 'GEA%'))ATH_PAID,

SGRSPRT_ACTC_CODE SPORT,

RNVAND0_UNMET_NEED UNMET_NEED,
RORSTAT_APPL_RCVD_DATE, RORSTAT_PGRP_CODE,

(Select (SFRTHST_TMST_CODE)
from SFRTHST
where RORSTAT_PIDM = SFRTHST_PIDM
and SFRTHST_TERM_CODE = '202480'
and SFRTHST_TMST_DATE = 
(Select MAX(A.SFRTHST_TMST_DATE)
from SFRTHST A
where A.SFRTHST_PIDM = RORSTAT_PIDM
and A.SFRTHST_TERM_CODE = '202480')) FALL_TMST,

SHRTGPA_HOURS_EARNED FALL_EARNED, SHRTGPA_GPA FALL_GPA, 
SHRLGPA_GPA, 

(Select (SFRTHST_TMST_CODE)
from SFRTHST
where RORSTAT_PIDM = SFRTHST_PIDM
and SFRTHST_TERM_CODE = '202510'
and SFRTHST_TMST_DATE = 
(Select MAX(A.SFRTHST_TMST_DATE)
from SFRTHST A
where A.SFRTHST_PIDM = RORSTAT_PIDM
and A.SFRTHST_TERM_CODE = '202510')) SPR_TMST,

(Select (SFRTHST_TMST_CODE)
from SFRTHST
where RORSTAT_PIDM = SFRTHST_PIDM
and SFRTHST_TERM_CODE = '202460'
and SFRTHST_TMST_DATE = 
(Select MAX(A.SFRTHST_TMST_DATE)
from SFRTHST A
where A.SFRTHST_PIDM = RORSTAT_PIDM
and A.SFRTHST_TERM_CODE = '202460')) SMR_TMST,


C.SGBUSER_SUDJ_CODE FALL_CAMPUS, D.SGBUSER_SUDJ_CODE SPR_CAMPUS,

(select sum(tbraccd_balance)
         from tbraccd
         where tbraccd_pidm = SPRIDEN_pidm) total_balance,

GOREMAL_EMAIL_ADDRESS

from RORSTAT

left join SPRIDEN
on RORSTAT_PIDM = SPRIDEN_PIDM
and SPRIDEN_CHANGE_IND is null

left join SGRSPRT
on RORSTAT_PIDM = SGRSPRT_PIDM
and SGRSPRT_TERM_CODE in ('202480','202510')

left join RNVAND0
on RORSTAT_PIDM =RNVAND0_PIDM
and RORSTAT_AIDY_CODE = RNVAND0_AIDY_CODE

left join RCRAPP1
on RORSTAT_PIDM = RCRAPP1_PIDM
and RORSTAT_AIDY_CODE = RCRAPP1_AIDY_CODE
and RCRAPP1_INFC_CODE = 'EDE'
and RCRAPP1_CURR_REC_IND = 'Y'

left join RCRAPP2
on RCRAPP1_PIDM = RCRAPP2_PIDM
and RCRAPP1_INFC_CODE = RCRAPP2_INFC_CODE
and RCRAPP1_AIDY_CODE = RCRAPP2_AIDY_CODE
and RCRAPP1_SEQ_NO = RCRAPP2_SEQ_NO

left join RPRAWRD A
on RORSTAT_PIDM = A.RPRAWRD_PIDM
and RORSTAT_AIDY_CODE = A.RPRAWRD_AIDY_CODE
and A.RPRAWRD_FUND_CODE = 'GFNSEO'

left join RPRAWRD B
on RORSTAT_PIDM = B.RPRAWRD_PIDM
and RORSTAT_AIDY_CODE = B.RPRAWRD_AIDY_CODE
and B.RPRAWRD_FUND_CODE = 'GFNPEL'

left join SHRTGPA
on RORSTAT_PIDM = SHRTGPA_PIDM
and SHRTGPA_TERM_CODE = '202480'
and SHRTGPA_LEVL_CODE = 'UG'
and SHRTGPA_GPA_TYPE_IND = 'I'

left join SHRLGPA
on RORSTAT_PIDM = SHRLGPA_PIDM
and SHRLGPA_LEVL_CODE = 'UG'
and SHRLGPA_GPA_TYPE_IND = 'O'

left join SGBUSER C
on RORSTAT_PIDM = C.SGBUSER_PIDM
and C.SGBUSER_TERM_CODE = '202480'

left join SGBUSER D
on RORSTAT_PIDM = D.SGBUSER_PIDM
and D.SGBUSER_TERM_CODE = '202510'

left join RORSAPR E
on RORSTAT_PIDM = E.RORSAPR_PIDM
and E.RORSAPR_TERM_CODE = '202460'

left join RORSAPR F
on RORSTAT_PIDM = F.RORSAPR_PIDM
and F.RORSAPR_TERM_CODE = '202480'

left join RORSAPR G
on RORSTAT_PIDM = G.RORSAPR_PIDM
and G.RORSAPR_TERM_CODE = '202510'

left join GOREMAL
on RORSTAT_PIDM = GOREMAL_PIDM
and GOREMAL_EMAL_CODE = 'U'

where RORSTAT_AIDY_CODE = '2425'
and RCRAPP2_PELL_PGI = 0
and NVL(A.RPRAWRD_PAID_AMT,0) = 0
and B.RPRAWRD_PAID_AMT >0
and A.RPRAWRD_FUND_CODE is null