SELECT
BID, 
FNAME,
LNAME,
CRN,
STATUS_MESS,
CREDIT_HRS,
BF_ACTIVITY_DATE,
BF_STATUS_CODE,
AF_ACTIVITY_DATE,
AF_STATUS_CODE,
RPRATRM_FUND_CODE

FROM
(SELECT
SPRIDEN_ID BID,
SPRIDEN_FIRST_NAME FNAME,
SPRIDEN_LAST_NAME LNAME,
A.SFRSTCA_TERM_CODE,
A.SFRSTCA_CRN CRN,
A.SFRSTCA_MESSAGE STATUS_MESS,
A.SFRSTCA_CREDIT_HR CREDIT_HRS,
A.SFRSTCA_ACTIVITY_DATE BF_ACTIVITY_DATE,
A.SFRSTCA_RSTS_CODE BF_STATUS_CODE,
B.SFRSTCA_ACTIVITY_DATE AF_ACTIVITY_DATE,
B.SFRSTCA_RSTS_CODE AF_STATUS_CODE,
RPRATRM_FUND_CODE

FROM 
SFRSTCA A

JOIN
SFRSTCA B
ON A.SFRSTCA_PIDM = B.SFRSTCA_PIDM
AND A.SFRSTCA_CRN = B.SFRSTCA_CRN

JOIN SPRIDEN
ON SPRIDEN_PIDM = A.SFRSTCA_PIDM
AND SPRIDEN_PIDM = B.SFRSTCA_PIDM
AND SPRIDEN_CHANGE_IND IS NULL

JOIN RPRATRM
ON A.SFRSTCA_PIDM = RPRATRM_PIDM
AND RPRATRM_PERIOD = '202510'
AND RPRATRM_FUND_CODE IN ('GFNPEL', 'GFUTGU', 'GFUTGG', 'GSNPPF', 'GSNPPP')

 WHERE A.SFRSTCA_TERM_CODE = :CUR_TERM
       AND A.SFRSTCA_SOURCE_CDE = 'BASE' 
       AND A.SFRSTCA_RSTS_CODE LIKE 'N%'
       AND TRUNC(A.SFRSTCA_ACTIVITY_DATE) < TO_DATE('29-MAY-2025', 'DD-MON-YYYY')
       AND B.SFRSTCA_RSTS_CODE NOT LIKE 'N%'
       AND TRUNC(B.SFRSTCA_ACTIVITY_DATE) >= TO_DATE('29-MAY-2025', 'DD-MON-YYYY'))
