SELECT
ID,
NAME,
FUND,
AWARD_OFFER_AMT,
AWARD_ACCEPT_AMT,
AWARD_PAID_AMT,
SUM_OFFER_AMT,
FAL_OFFER_AMT,
SPR_OFFER_AMT,
SUM_ACCEPT_AMT,
FAL_ACCEPT_AMT,
SPR_ACCEPT_AMT,
SUM_PAID_AMT,
FAL_PAID_AMT,
SPR_PAID_AMT,
SM_UG_KC,
FA_UG_KC, 
SP_UG_KC,
SM_UG_NON_KC,
FA_UG_NON_KC,
SP_UG_NON_KC,

(AWARD_OFFER_AMT-AWARD_ACCEPT_AMT) OFFER_ACCEPT,

(AWARD_OFFER_AMT-AWARD_PAID_AMT) OFFER_PAID

FROM
(SELECT
DISTINCT SPRIDEN_ID ID,
SPRIDEN_LAST_NAME || ', ' || SPRIDEN_FIRST_NAME AS NAME,
RPRAWRD_FUND_CODE FUND,
RPRAWRD_OFFER_AMT AWARD_OFFER_AMT,
RPRAWRD_ACCEPT_AMT AWARD_ACCEPT_AMT,
RPRAWRD_PAID_AMT AWARD_PAID_AMT,
--RORENRL_FINAID_ADJ_HR REPEAT_HRS,

(SELECT A.RPRATRM_OFFER_AMT
        FROM RPRATRM A
        WHERE A.RPRATRM_PIDM = RPRAWRD_PIDM
        AND A.RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND A.RPRATRM_PERIOD = :SMR_TRM
        AND A.RPRATRM_FUND_CODE = 'GFNSEO'    
        AND A.RPRATRM_OFFER_AMT > 0) SUM_OFFER_AMT,
        
(SELECT RPRATRM_OFFER_AMT
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND RPRATRM_PERIOD = :FAL_TRM
        AND RPRATRM_FUND_CODE = 'GFNSEO'    
        AND RPRATRM_OFFER_AMT > 0) FAL_OFFER_AMT,
        
(SELECT RPRATRM_OFFER_AMT
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND RPRATRM_PERIOD = :SPR_TRM
        AND RPRATRM_FUND_CODE = 'GFNSEO'    
        AND RPRATRM_OFFER_AMT > 0) SPR_OFFER_AMT,
        
(SELECT RPRATRM_ACCEPT_AMT
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND RPRATRM_PERIOD = :SMR_TRM
        AND RPRATRM_FUND_CODE = 'GFNSEO'    
        AND RPRATRM_OFFER_AMT > 0) SUM_ACCEPT_AMT,
        
(SELECT RPRATRM_ACCEPT_AMT
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND RPRATRM_PERIOD = :FAL_TRM
        AND RPRATRM_FUND_CODE = 'GFNSEO'    
        AND RPRATRM_OFFER_AMT > 0) FAL_ACCEPT_AMT,
        
(SELECT RPRATRM_ACCEPT_AMT
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND RPRATRM_PERIOD = :SPR_TRM
        AND RPRATRM_FUND_CODE = 'GFNSEO'    
        AND RPRATRM_OFFER_AMT > 0) SPR_ACCEPT_AMT,

(SELECT RPRATRM_PAID_AMT
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND RPRATRM_PERIOD = :SMR_TRM
        AND RPRATRM_FUND_CODE = 'GFNSEO'    
        AND RPRATRM_OFFER_AMT > 0) SUM_PAID_AMT,
        
(SELECT RPRATRM_PAID_AMT
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND RPRATRM_PERIOD = :FAL_TRM
        AND RPRATRM_FUND_CODE = 'GFNSEO'    
        AND RPRATRM_OFFER_AMT > 0) FAL_PAID_AMT,
        
(SELECT RPRATRM_PAID_AMT
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND RPRATRM_PERIOD = :SPR_TRM
        AND RPRATRM_FUND_CODE = 'GFNSEO'    
        AND RPRATRM_OFFER_AMT > 0) SPR_PAID_AMT,

(SELECT SUM(SFRSTCR_BILL_HR)
        FROM SFRSTCR
        WHERE SPRIDEN_PIDM = SFRSTCR_PIDM
        AND SFRSTCR_TERM_CODE = :SMR_TRM
        AND SFRSTCR_CAMP_CODE = 'KC'
        AND SFRSTCR_LEVL_CODE = 'UG'
        AND SFRSTCR_RSTS_CODE IN ('RR', 'RW','R2','RE')) SM_UG_KC, 

(SELECT SUM(SFRSTCR_BILL_HR)
        FROM SFRSTCR
        WHERE SPRIDEN_PIDM = SFRSTCR_PIDM
        AND SFRSTCR_TERM_CODE = :FAL_TRM
        AND SFRSTCR_CAMP_CODE = 'KC'
        AND SFRSTCR_LEVL_CODE = 'UG'
        AND SFRSTCR_RSTS_CODE IN ('RR', 'RW','R2','RE')) FA_UG_KC, 
        
(SELECT SUM(SFRSTCR_BILL_HR)
        FROM SFRSTCR
        WHERE SPRIDEN_PIDM = SFRSTCR_PIDM
        AND SFRSTCR_TERM_CODE = :SPR_TRM
        AND SFRSTCR_CAMP_CODE = 'KC'
        AND SFRSTCR_LEVL_CODE = 'UG'
        AND SFRSTCR_RSTS_CODE IN ('RR', 'RW','R2','RE')) SP_UG_KC, 
        
(SELECT SUM(SFRSTCR_BILL_HR)
        FROM SFRSTCR
        WHERE SPRIDEN_PIDM = SFRSTCR_PIDM
        AND SFRSTCR_TERM_CODE = :SMR_TRM
        AND SFRSTCR_CAMP_CODE <> 'KC'
        AND SFRSTCR_LEVL_CODE = 'UG'
        AND SFRSTCR_RSTS_CODE IN ('RR', 'RW','R2','RE')) SM_UG_NON_KC,
        
(SELECT SUM(SFRSTCR_BILL_HR)
        FROM SFRSTCR
        WHERE SPRIDEN_PIDM = SFRSTCR_PIDM
        AND SFRSTCR_TERM_CODE = :FAL_TRM
        AND SFRSTCR_CAMP_CODE <> 'KC'
        AND SFRSTCR_LEVL_CODE = 'UG'
        AND SFRSTCR_RSTS_CODE IN ('RR', 'RW','R2','RE')) FA_UG_NON_KC,
        
(SELECT SUM(SFRSTCR_BILL_HR)
        FROM SFRSTCR
        WHERE SPRIDEN_PIDM = SFRSTCR_PIDM
        AND SFRSTCR_TERM_CODE = :SPR_TRM
        AND SFRSTCR_CAMP_CODE <> 'KC'
        AND SFRSTCR_LEVL_CODE = 'UG'
        AND SFRSTCR_RSTS_CODE IN ('RR', 'RW','R2','RE')) SP_UG_NON_KC

FROM RPRAWRD

LEFT JOIN RPRATRM
ON RPRATRM_PIDM = RPRAWRD_PIDM
AND RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE
AND RPRATRM_FUND_CODE = RPRAWRD_FUND_CODE

LEFT JOIN SPRIDEN
ON RPRAWRD_PIDM = SPRIDEN_PIDM
AND SPRIDEN_CHANGE_IND IS NULL

LEFT JOIN SFRSTCR
ON SFRSTCR_PIDM = RPRAWRD_PIDM
AND SFRSTCR_TERM_CODE = RPRATRM_PERIOD

--LEFT JOIN RORENRL
--ON RORENRL_PIDM = RPRATRM_PIDM
--AND RORENRL_ENRR_CODE = 'REPEAT'
--
--LEFT JOIN STVTERM
--ON RORENRL_ENRR_CODE = STVTERM_CODE
--AND RORENRL_TERM_CODE = STVTERM_FA_TERM

WHERE RPRAWRD_AIDY_CODE =:AIDY
AND RPRATRM_PERIOD =:CUR_TRM
AND RPRAWRD_FUND_CODE = 'GFNSEO'
AND RPRAWRD_OFFER_AMT > 0)

ORDER BY 2
