SELECT *
  FROM (  SELECT SPRIDEN_ID, SPRIDEN_FIRST_NAME, SPRIDEN_LAST_NAME, COUNT(RPRATRM_FUND_CODE) FUND_COUNT
            FROM RPRATRM, SPRIDEN
           WHERE     RPRATRM_PIDM = SPRIDEN_PIDM
                 AND SPRIDEN_CHANGE_IND IS NULL
                 AND RPRATRM_OFFER_AMT > 0
                 AND RPRATRM_PERIOD = :TERM
                 AND RPRATRM_FUND_CODE LIKE 'GSNOC%'
        GROUP BY SPRIDEN_ID, SPRIDEN_FIRST_NAME, SPRIDEN_LAST_NAME)
 WHERE FUND_COUNT > 1