Select * from(

Select SPRIDEN_ID, SPRIDEN_FIRST_NAME, SPRIDEN_LAST_NAME, RORSTAT_APRD_CODE,

( SELECT SFRTHST_TMST_CODE
  FROM (SELECT SFRTHST_TMST_CODE
          FROM SFRTHST
         WHERE RORSTAT_PIDM = SFRTHST_PIDM
          AND  SFRTHST_TERM_CODE = :SMR_TERM
      ORDER BY SFRTHST_ACTIVITY_DATE DESC )
      WHERE ROWNUM = 1) SMR_TMST,
    
( SELECT SFRTHST_TMST_CODE
  FROM (SELECT SFRTHST_TMST_CODE
          FROM SFRTHST
         WHERE RORSTAT_PIDM = SFRTHST_PIDM
          AND  SFRTHST_TERM_CODE = :FAL_TERM
      ORDER BY SFRTHST_ACTIVITY_DATE DESC )
      WHERE ROWNUM = 1) FAL_TMST,
    
( SELECT SFRTHST_TMST_CODE
  FROM (SELECT SFRTHST_TMST_CODE
          FROM SFRTHST
         WHERE RORSTAT_PIDM = SFRTHST_PIDM
          AND  SFRTHST_TERM_CODE = :SPR_TERM
      ORDER BY SFRTHST_ACTIVITY_DATE DESC )
      WHERE ROWNUM = 1) SPR_TMST,

RORENRL_FINAID_ADJ_HR FROZEN_REPEAT, RORENRL_CONSORTIUM_IND CONSORTIUM, RPRATRM_FUND_CODE, RPRAWRD_AWST_CODE, 
RPRATRM_OFFER_AMT TERM_OFFER, RPRATRM_ACCEPT_AMT TERM_ACCEPT, RPRATRM_PAID_AMT TERM_PAID,

RPRAWRD_OFFER_AMT YEAR_OFFER

from RPRATRM
left join SPRIDEN
on RPRATRM_PIDM = SPRIDEN_PIDM
and SPRIDEN_CHANGE_IND is null

left join RPRAWRD
on RPRATRM_PIDM = RPRAWRD_PIDM
and RPRATRM_FUND_CODE = RPRAWRD_FUND_CODE
and RPRAWRD_AIDY_CODE = :AIDY

left join RORSTAT
on RPRATRM_PIDM = RORSTAT_PIDM
and RORSTAT_AIDY_CODE = :AIDY

left join RORENRL
on RPRATRM_PIDM = RORENRL_PIDM
and RPRATRM_PERIOD = RORENRL_TERM_CODE
and RORENRL_ENRR_CODE = 'REPEAT'

where RPRATRM_FUND_CODE like 'LF%'
and RPRATRM_PERIOD = :CUR_TRM
)
where SMR_TMST in ('00','LH')    -- UPDATE THIS FIELD NAME EACH TERM
and TERM_OFFER >0
and NVL(TERM_PAID,0) =0
