    SELECT
    DISTINCT SPRIDEN_ID,
    SPRIDEN_FIRST_NAME,
    SPRIDEN_LAST_NAME,
    RORMESG_MESG_CODE,
    RORMESG_EXPIRATION_DATE,
    RRRAREQ_TREQ_CODE,
    RRRAREQ_SAT_IND
    
    FROM RORMESG
    
    LEFT JOIN RRRAREQ
    ON RRRAREQ_PIDM = RORMESG_PIDM
    AND RRRAREQ_AIDY_CODE = RORMESG_AIDY_CODE
    AND RRRAREQ_TREQ_CODE = 'OGSLSV'
    AND RRRAREQ_SAT_IND <> 'Y'
    
    LEFT JOIN SPRIDEN
    ON SPRIDEN_PIDM = RORMESG_PIDM
    AND SPRIDEN_CHANGE_IND IS NULL
    
    WHERE RORMESG_MESG_CODE = 'OSLS'
    AND RORMESG_AIDY_CODE = '2526'
    AND RORMESG_EXPIRATION_DATE >= sysdate