-- Add CTEs for safe outer join filtering
WITH MAX_SGBSTDN AS (
    SELECT SGBSTDN_PIDM AS MAX_PIDM, MAX(SGBSTDN_TERM_CODE_EFF) AS MAX_TERM
    FROM SGBSTDN
    WHERE SGBSTDN_TERM_CODE_EFF <= :CUR_TRM
      AND SGBSTDN_STST_CODE = 'AS'
    GROUP BY SGBSTDN_PIDM
),

TOTAL_GPA AS (SELECT SHRLGPA_PIDM, MAX(SHRLGPA_GPA) AS OFFICIAL_GPA_TOT
    FROM SHRLGPA
    WHERE SHRLGPA_GPA_TYPE_IND = 'O'
    GROUP BY SHRLGPA_PIDM
),

MAX_RORSAPR AS (
    SELECT RORSAPR_PIDM AS APOK_PIDM, MAX(RORSAPR_TERM_CODE) AS MAX_TERM
    FROM RORSAPR
    WHERE RORSAPR_TERM_CODE <= :SPR_TRM
    GROUP BY RORSAPR_PIDM
),

RECENT_TEST AS (
    SELECT SPRIDEN_PIDM,
           CASE
                WHEN SORTEST_TESC_CODE = 'A01' AND SORTEST_TEST_SCORE >= 24 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('1997','1998','1999','2000','2001','2002','2003','2004','2005','2019','2020','2021','2022') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'A01' AND SORTEST_TEST_SCORE >= 25 THEN 'Y'
                WHEN SORTEST_TESC_CODE IN ('A02', 'A05') AND SORTEST_TEST_SCORE >= 24
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2022') THEN 'Y'
                WHEN SORTEST_TESC_CODE IN ('A02', 'A05') AND SORTEST_TEST_SCORE >= 25 THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'A03' AND SORTEST_TEST_SCORE >= 25 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('1997','1998','1999','2001','2003','2004','2009','2010','2011','2022') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'A03' AND SORTEST_TEST_SCORE >= 26 THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'A04' AND SORTEST_TEST_SCORE >= 24 THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S01' AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2014','2015','2016') AND SORTEST_TEST_SCORE >= 590 THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S01' AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2014','2015','2016') AND SORTEST_TEST_SCORE < 590 THEN 'N'
                WHEN SORTEST_TESC_CODE = 'S01' AND SORTEST_TEST_SCORE >= 580 THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S02' AND SORTEST_TEST_SCORE >= 580 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2017','2018','2021','2022') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S02' AND SORTEST_TEST_SCORE >= 590 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('1997','1998','1999','2000','2001','2002','2008','2009') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S02' AND SORTEST_TEST_SCORE >= 600 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2003','2004','2005','2006','2007','2011','2012','2019','2020') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S02' AND SORTEST_TEST_SCORE >= 610 THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S07' AND SORTEST_TEST_SCORE >= 570 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2006','2007','2008','2009','2011','2012','2014','2015') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S07' AND SORTEST_TEST_SCORE >= 580 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2009','2012') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S10' AND SORTEST_TEST_SCORE >= 1160 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2016','2017','2021','2022') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S10' AND SORTEST_TEST_SCORE >= 1210 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2018','2019','2020') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S11' AND SORTEST_TEST_SCORE >= 590 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2016','2017','2021','2022') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S11' AND SORTEST_TEST_SCORE >= 610 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2018','2019','2020') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S12' AND SORTEST_TEST_SCORE >= 580 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2016','2017','2021','2022') THEN 'Y'
                WHEN SORTEST_TESC_CODE = 'S12' AND SORTEST_TEST_SCORE >= 600 
                     AND TO_CHAR(SORTEST_TEST_DATE, 'YYYY') IN ('2018','2019','2020') THEN 'Y'
                ELSE 'N'
           END AS PERCENT_CALC_75
    FROM (
        SELECT SPRIDEN_PIDM, SORTEST_TESC_CODE, SORTEST_TEST_SCORE, SORTEST_TEST_DATE,
               ROW_NUMBER() OVER (PARTITION BY SPRIDEN_PIDM ORDER BY SORTEST_TEST_DATE DESC) AS RN
        FROM SORTEST
        JOIN SPRIDEN ON SPRIDEN_PIDM = SORTEST_PIDM AND SPRIDEN_CHANGE_IND IS NULL
        WHERE SORTEST_TESC_CODE IN ('A01','A02','A03','A04','A05','A14','S01','S02','S07','S10','S11','S12')
          AND SORTEST_TEST_DATE >= TO_DATE('2000-01-01', 'YYYY-MM-DD')
    )
    WHERE RN = 1
)

SELECT *
    
    FROM
    
    (SELECT 
        DISTINCT SPRIDEN_ID                             ID,
        SPRIDEN_LAST_NAME || ', ' || SPRIDEN_FIRST_NAME NAME,
        RORSTAT_APRD_CODE                               AID_PERIOD,
        ROBUSDF_VALUE_108                               TEACH_POTENTIALLY_ELIG_USDF_108,
        RORSTAT_PCKG_COMP_DATE                          PACKAGE_COMPLETE_DATE,
        RORHSDT_ADMISSION_TEST_IND,
        RECENT_TEST.PERCENT_CALC_75,
        CASE WHEN NVL(C.RPRAWRD_ORIG_OFFER_AMT, 0) > 0 THEN 'Y' END TEACH_PREVIOUSLY_ANY_YEAR,
        TOTAL_GPA.OFFICIAL_GPA_TOT                      GPA,
        ROBUSDF_VALUE_34                                UDF_34,
        ROBUSDF_VALUE_35                                UDF_35,
        RORSTAT_PGRP_CODE                               PCKG_GRP,
        RORSAPR_SAPR_CODE                               AP_CODE,
        RTVSAPR_DESC                                    AP_DESC,
        RORSAPR_TERM_CODE                               MAX_AP_TERM,
        SGBSTDN_LEVL_CODE                               STU_LEVEL,
        
        CASE WHEN
              (  ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 IN ('READ', 'SPED'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 IN ('READ', 'SPED'))
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 IN ('MTHT','TESL'))
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 IN ('MTHT','TESL'))
              OR ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 IN ('ARTE','TESL'))
              OR ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 IN ('ARTE','TESL'))
              OR ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 IN ('ARTE','TESL'))
              OR ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 IN ('ARTE','TESL'))
              OR ('BM' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'MUED')
              OR ('BM' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'MUED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 IN ('ESCI','IMTH','ISCI','LFSC','LSCM','PHSC','SHED','SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 IN ('ESCI','IMTH','ISCI','LFSC','LSCM','PHSC','SHED','SPED'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 IN ('READ', 'SPED'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 IN ('READ', 'SPED'))
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 IN ('MTHT','TESL'))
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 IN ('MTHT','TESL'))
              OR ('BM' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'MUED')
              OR ('BM' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'MUED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 IN ('ESCI','IMTH','ISCI','LFSC','LSCM','PHSC','SHED','SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 IN ('ESCI','IMTH','ISCI','LFSC','LSCM','PHSC','SHED','SPED'))
              
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_1 = 'SPED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_2 = 'SPED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'HEDP' AND SGBSTDN_MAJR_CODE_CONC_1 IN ('HPE','SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'HEDP' AND SGBSTDN_MAJR_CODE_CONC_2 IN ('HPE','SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'ISCI' AND SGBSTDN_MAJR_CODE_CONC_1 IN ('CHEM', 'ESCI', 'LFSC', 'PHY'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'ISCI' AND SGBSTDN_MAJR_CODE_CONC_2 IN ('CHEM', 'ESCI', 'LFSC', 'PHY'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'MCED' AND SGBSTDN_MAJR_CODE_CONC_1 IN ('LAMT','LASC','MATH','MTSC','SCNC','MTSS','SSSC'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'MCED' AND SGBSTDN_MAJR_CODE_CONC_2 IN ('LAMT','LASC','MATH','MTSC','SCNC','MTSS','SSSC'))
              OR ('BS' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'PESP' AND SGBSTDN_MAJR_CODE_CONC_1 IN ('HPE', 'PEL'))
              OR ('BS' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'PESP' AND SGBSTDN_MAJR_CODE_CONC_2 IN ('HPE', 'PEL'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_1 IN ('SPED', 'SHLI'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_2 IN ('SPED', 'SHLI'))
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 IN ('FR','LAT','SPAN') AND SGBSTDN_MAJR_CODE_CONC_1 = 'APLP')
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 IN ('FR','LAT','SPAN') AND SGBSTDN_MAJR_CODE_CONC_2 = 'APLP')
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'SEED' AND SGBSTDN_MAJR_CODE_CONC_1 IN ('ART9','CHPH','ESCI','DANC','FR','GER','HLTH','ISCI','LAT','LFSC','LSCM','MATH','MUS','PEP','SPAN','SPED'))
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'SEED' AND SGBSTDN_MAJR_CODE_CONC_2 IN ('ART9','CHPH','ESCI','DANC','FR','GER','HLTH','ISCI','LAT','LFSC','LSCM','MATH','MUS','PEP','SPAN','SPED'))   
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_1 = 'SPED')
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_2 = 'SPED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_1_2 = 'SPED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_2_2 = 'SPED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'HEDP' AND SGBSTDN_MAJR_CODE_CONC_1_2 IN ('HPE','SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'HEDP' AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('HPE','SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'ISCI' AND SGBSTDN_MAJR_CODE_CONC_1_2 IN ('CHEM', 'ESCI', 'LFSC', 'PHY'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'ISCI' AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('CHEM', 'ESCI', 'LFSC', 'PHY'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'MCED' AND SGBSTDN_MAJR_CODE_CONC_1_2 IN ('LAMT','LASC','MATH','MTSC','SCNC','MTSS','SSSC'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'MCED' AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('LAMT','LASC','MATH','MTSC','SCNC','MTSS','SSSC'))
              OR ('BS' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'PESP' AND SGBSTDN_MAJR_CODE_CONC_1_2 IN ('HPE', 'PEL'))
              OR ('BS' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'PESP' AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('HPE', 'PEL'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_1_2 IN ('SPED', 'SHLI'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('SPED', 'SHLI'))
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 IN ('FR','LAT','SPAN') AND SGBSTDN_MAJR_CODE_CONC_1_2 = 'APLP')
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 IN ('FR','LAT','SPAN') AND SGBSTDN_MAJR_CODE_CONC_2_2 = 'APLP')
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'SEED' AND SGBSTDN_MAJR_CODE_CONC_1_2 IN ('ART9','CHPH','ESCI','DANC','FR','GER','HLTH','ISCI','LAT','LFSC','LSCM','MATH','MUS','PEP','SPAN','SPED'))
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'SEED' AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('ART9','CHPH','ESCI','DANC','FR','GER','HLTH','ISCI','LAT','LFSC','LSCM','MATH','MUS','PEP','SPAN','SPED'))   
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_1_2 = 'SPED')
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'ECDE' AND SGBSTDN_MAJR_CODE_CONC_2_2 = 'SPED')
              
              OR ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 IN ('FR','GER','SPAN') AND SGBSTDN_MAJR_CODE_MINR_1 = 'EDUC') 
              OR ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 IN ('FR','GER','SPAN') AND SGBSTDN_MAJR_CODE_MINR_2 = 'EDUC')                                       
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 IN ('ECDE', 'MCED') AND SGBSTDN_MAJR_CODE_MINR_1 = 'MMSP')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 IN ('ECDE', 'MCED') AND SGBSTDN_MAJR_CODE_MINR_2 = 'MMSP')
              OR ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 IN ('FR','GER','SPAN') AND SGBSTDN_MAJR_CODE_MINR_1_2 = 'EDUC') 
              OR ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 IN ('FR','GER','SPAN') AND SGBSTDN_MAJR_CODE_MINR_2_2 = 'EDUC')                                       
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 IN ('ECDE', 'MCED') AND SGBSTDN_MAJR_CODE_MINR_1_2 = 'MMSP')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 IN ('ECDE', 'MCED') AND SGBSTDN_MAJR_CODE_MINR_2_2 = 'MMSP')
              )
               THEN 'Y'
               END                                      CONC_MINOR_REQMTS_MET,
               
        SGBSTDN_DEGC_CODE_1                             DEGREE,
        SGBSTDN_MAJR_CODE_1                             FIRST_MAJOR,   
         
        CASE WHEN
              (  ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'ECDE') -- AND SGBSTDN_MAJR_CODE_CONC_1 = 'SPED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'HEDP') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('HPE','SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'ISCI') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('CHEM', 'ESCI', 'LFSC', 'PHY'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'MCED') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('LAMT','LASC','MATH','MTSC','SCNC','MTSS','SSSC'))
              OR ('BS' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'PESP') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('HPE', 'PEL'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'ECDE') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('SPED', 'SHLI'))
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 IN ('FR','LAT','SPAN')) -- AND SGBSTDN_MAJR_CODE_CONC_1 = 'APLP')
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'SEED') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('ART9','CHPH','ESCI','DANC','FR','GER','HLTH','ISCI','LAT','LFSC','LSCM','MATH','MUS','PEP','SPAN','SPED'))
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 = 'ECDE') -- AND SGBSTDN_MAJR_CODE_CONC_1 = 'SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'ECDE') -- AND SGBSTDN_MAJR_CODE_CONC_1 = 'SPED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'HEDP') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('HPE','SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'ISCI') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('CHEM', 'ESCI', 'LFSC', 'PHY'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'MCED') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('LAMT','LASC','MATH','MTSC','SCNC','MTSS','SSSC'))
              OR ('BS' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'PESP') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('HPE', 'PEL'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'ECDE') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('SPED', 'SHLI'))
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 IN ('FR','LAT','SPAN')) -- AND SGBSTDN_MAJR_CODE_CONC_1 = 'APLP')
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'SEED') -- AND SGBSTDN_MAJR_CODE_CONC_1 IN ('ART9','CHPH','ESCI','DANC','FR','GER','HLTH','ISCI','LAT','LFSC','LSCM','MATH','MUS','PEP','SPAN','SPED'))
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 = 'ECDE') -- AND SGBSTDN_MAJR_CODE_CONC_1 = 'SPED'))
              )
              THEN 'Y'
              END                                      CONC_REQD_FIRST_MAJOR,
         
         CASE WHEN 
              (  ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 IN ('FR','GER','SPAN')) --AND SGBSTDN_MAJR_CODE_MINR_1 = 'EDUC') 
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1 IN ('ECDE', 'MCED')) --AND SGBSTDN_MAJR_CODE_MINR_1 = 'MMSP'))
              OR ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 IN ('FR','GER','SPAN')) --AND SGBSTDN_MAJR_CODE_MINR_1 = 'EDUC') 
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_1_2 IN ('ECDE', 'MCED')) --AND SGBSTDN_MAJR_CODE_MINR_1 = 'MMSP'))
              )       
              THEN 'Y'
              END                                       MINOR_REQD_FIRST_MAJOR,
               
        SGBSTDN_MAJR_CODE_MINR_1                         FIRST_MINOR,
        SGBSTDN_MAJR_CODE_CONC_1                         FIRST_MAJOR_CONC,
        STVMAJR1.STVMAJR_DESC                            FIRST_MAJOR_CONC_DESC,
        SGBSTDN_DEGC_CODE_2                              DEGREE_2,
        SGBSTDN_MAJR_CODE_2                              SECOND_MAJOR,
        
        CASE WHEN
              (  ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'ECDE') --AND SGBSTDN_MAJR_CODE_CONC_2 = 'SPED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'HEDP') --AND SGBSTDN_MAJR_CODE_CONC_2 IN ('HPE','SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'ISCI') --AND SGBSTDN_MAJR_CODE_CONC_2 IN ('CHEM', 'ESCI', 'LFSC', 'PHY'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'MCED') --AND SGBSTDN_MAJR_CODE_CONC_2 IN ('LAMT','LASC','MATH','MTSC','SCNC','MTSS','SSSC'))
              OR ('BS' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'PESP') --AND SGBSTDN_MAJR_CODE_CONC_2 IN ('HPE', 'PEL'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'ECDE') --AND SGBSTDN_MAJR_CODE_CONC_2 IN ('SPED', 'SHLI'))
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 IN ('FR','LAT','SPAN')) --AND SGBSTDN_MAJR_CODE_CONC_2 = 'APLP')
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'SEED') --AND SGBSTDN_MAJR_CODE_CONC_2 IN ('ART9','CHPH','ESCI','DANC','FR','GER','HLTH','ISCI','LAT','LFSC','LSCM','MATH','MUS','PEP','SPAN','SPED'))   
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 = 'ECDE') --AND SGBSTDN_MAJR_CODE_CONC_2 = 'SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'ECDE') --AND SGBSTDN_MAJR_CODE_CONC_2_2 = 'SPED')
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'HEDP') --AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('HPE','SPED'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'ISCI') --AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('CHEM', 'ESCI', 'LFSC', 'PHY'))
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'MCED') --AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('LAMT','LASC','MATH','MTSC','SCNC','MTSS','SSSC'))
              OR ('BS' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'PESP') --AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('HPE', 'PEL'))
              OR ('MED' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'ECDE') --AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('SPED', 'SHLI'))
              OR ('MA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 IN ('FR','LAT','SPAN')) --AND SGBSTDN_MAJR_CODE_CONC_2_2 = 'APLP')
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'SEED') --AND SGBSTDN_MAJR_CODE_CONC_2_2 IN ('ART9','CHPH','ESCI','DANC','FR','GER','HLTH','ISCI','LAT','LFSC','LSCM','MATH','MUS','PEP','SPAN','SPED'))   
              OR ('MAT' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 = 'ECDE') --AND SGBSTDN_MAJR_CODE_CONC_2_2 = 'SPED'))
               )
               THEN 'Y'
               END                                       CONC_REQD_SECOND_MAJOR,
        
        CASE WHEN 
              (  ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 IN ('FR','GER','SPAN')) -- AND SGBSTDN_MAJR_CODE_MINR_2 = 'EDUC')                                       
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2 IN ('ECDE', 'MCED')) --AND SGBSTDN_MAJR_CODE_MINR_2 = 'MMSP'))
              OR ('BA' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 IN ('FR','GER','SPAN')) -- AND SGBSTDN_MAJR_CODE_MINR_2 = 'EDUC')                                       
              OR ('BSE' IN (SGBSTDN_DEGC_CODE_1, SGBSTDN_DEGC_CODE_2) AND SGBSTDN_MAJR_CODE_2_2 IN ('ECDE', 'MCED')) --AND SGBSTDN_MAJR_CODE_MINR_2 = 'MMSP'))
               )
               THEN 'Y'
               END                                       MINOR_REQD_SECOND_MAJOR,
               
        SGBSTDN_MAJR_CODE_MINR_2                         SECOND_MINOR,
        SGBSTDN_MAJR_CODE_CONC_2                         SECOND_MAJOR_CONC,
        STVMAJR2.STVMAJR_DESC                            SECOND_MAJOR_CONC_DESC,     
        SGBSTDN_MAJR_CODE_1_2                            THIRD_MAJOR,
        SGBSTDN_MAJR_CODE_2_2                            FOURTH_MAJOR,
        RORMESG_MESG_CODE                                MESSAGE,
        N.SORDEGR_GPA_TRANSFERRED                        TRANSFER_GPA,
        N.SORDEGR_SBGI_CODE                              CUM_DEGREE,
        SGBSTDN_STYP_CODE                                STUDENT_TYPE,        
        STVSBGI_DESC                                     INSTITUTION_DESC,
        M.SORDEGR_DEGC_CODE                              BACHELORS_DEGREE,
        M.SORDEGR_DEGC_DATE                              DEGREE_DATE,
        M.SORDEGR_GPA_TRANSFERRED                        BACHELORS_TRANSFER_GPA,

        CASE WHEN
                    ((E.SHRLGPA_GPA IS NULL AND SORHSCH_GPA >= 3.4) 
                      OR E.SHRLGPA_GPA >= 3.25
                      OR F.SHRLGPA_GPA >= 3.25)
                THEN 'Y'
                END  COMPLETE_GPA_REQ,
                   
        CASE WHEN (NVL (D.RPRAWRD_PAID_AMT, 0) > 0) 
               THEN 'Y'  
               END  TEACH_PAID_PRIOR_YEAR_ONLY
        
        FROM RORSTAT
               
              LEFT JOIN SPRIDEN
                   ON     SPRIDEN_PIDM = RORSTAT_PIDM
                      AND SPRIDEN_CHANGE_IND IS NULL
                      
               LEFT JOIN ROBUSDF
                   ON     ROBUSDF_PIDM = RORSTAT_PIDM
                      AND ROBUSDF_AIDY_CODE = RORSTAT_AIDY_CODE
                      
               LEFT JOIN RORHSDT 
                   ON RORHSDT_PIDM = RORSTAT_PIDM
                      
               LEFT JOIN RPRAWRD C
                   ON     C.RPRAWRD_PIDM = RORSTAT_PIDM
                      AND C.RPRAWRD_AIDY_CODE BETWEEN '0001' AND :AIDY
                      AND C.RPRAWRD_FUND_CODE IN ('GFUTGU','GFUTGG','GFUTU1','GFUTG1')
                      AND C.RPRAWRD_ORIG_OFFER_AMT > 0
                      
               LEFT JOIN RPRAWRD D
                   ON     D.RPRAWRD_PIDM = RORSTAT_PIDM
                      AND D.RPRAWRD_AIDY_CODE = :PRIOR_AIDY
                      AND D.RPRAWRD_FUND_CODE IN ('GFUTGU','GFUTGG','GFUTU1','GFUTG1')
                      
               LEFT JOIN MAX_SGBSTDN MZ 
               ON MZ.MAX_PIDM = RORSTAT_PIDM

               LEFT JOIN SGBSTDN 
               ON SGBSTDN_PIDM = MZ.MAX_PIDM 
               AND SGBSTDN_TERM_CODE_EFF = MZ.MAX_TERM
               
               LEFT JOIN MAX_RORSAPR MR ON MR.APOK_PIDM = RORSTAT_PIDM

               LEFT JOIN RORSAPR 
               ON RORSAPR_PIDM = MR.APOK_PIDM 
               AND RORSAPR_TERM_CODE = MR.MAX_TERM

               LEFT JOIN RTVSAPR 
                   ON RORSAPR_SAPR_CODE = RTVSAPR_CODE
                      
               LEFT JOIN RORMESG
                   ON RORMESG_PIDM = RORSTAT_PIDM
                      AND RORMESG_AIDY_CODE = RORSTAT_AIDY_CODE
                      AND RORMESG_MESG_CODE LIKE 'GT%'

              LEFT JOIN SHRLGPA E
                    ON E.SHRLGPA_PIDM = RORSTAT_PIDM
                      AND E.SHRLGPA_GPA_TYPE_IND = 'O'
                      AND E.SHRLGPA_LEVL_CODE = 'UG'
                
               LEFT JOIN SHRLGPA F
                    ON F.SHRLGPA_PIDM = RORSTAT_PIDM
                      AND F.SHRLGPA_GPA_TYPE_IND = 'O'
                      AND F.SHRLGPA_LEVL_CODE <> 'UG' 
                                               
               LEFT JOIN SORHSCH
                    ON   RORSTAT_PIDM = SORHSCH_PIDM
                     AND SORHSCH_GRADUATION_DATE IS NOT NULL
                     
               LEFT JOIN STVMAJR STVMAJR1
                    ON STVMAJR1.STVMAJR_CODE = SGBSTDN_MAJR_CODE_CONC_1

               LEFT JOIN STVMAJR STVMAJR2
                    ON STVMAJR2.STVMAJR_CODE = SGBSTDN_MAJR_CODE_CONC_2
                      
               LEFT JOIN SORDEGR N
                    ON   N.SORDEGR_PIDM = RORSTAT_PIDM
                     AND RORSTAT_AIDY_CODE = :AIDY
                     AND (N.SORDEGR_SBGI_CODE  = 'CUMGPA' 
                     OR N.SORDEGR_DEGC_CODE = 'CUMGPA')
               
               LEFT JOIN SORDEGR M
                    ON   M.SORDEGR_PIDM = RORSTAT_PIDM
                    AND RORSTAT_AIDY_CODE = :AIDY
                    AND (M.SORDEGR_DEGC_CODE = 'NB'
                    OR M.SORDEGR_DEGC_CODE LIKE 'B%')
                    AND M.SORDEGR_DEGC_DATE IS NOT NULL
                
               LEFT JOIN STVSBGI
                    ON STVSBGI_CODE = M.SORDEGR_SBGI_CODE

               LEFT JOIN RECENT_TEST 
                    ON RECENT_TEST.SPRIDEN_PIDM = RORSTAT_PIDM
                    
               LEFT JOIN TOTAL_GPA 
                    ON TOTAL_GPA.SHRLGPA_PIDM = RORSTAT_PIDM
      
        WHERE RORSTAT_AIDY_CODE = :AIDY)
       
        WHERE ( TEACH_POTENTIALLY_ELIG_USDF_108 ='Y'
        
        OR 
        (PERCENT_CALC_75 = 'Y'
        AND PCKG_GRP NOT IN ('KFNRES','REGFR','RDEGX1','KUNDSO','KUNDFR','RDEGXF','REGUFR','KFRES','RDEGX2','REGUSO')  
        AND CONC_MINOR_REQMTS_MET = 'Y'
        AND STUDENT_TYPE <> 'N')
        
        OR 
        (PCKG_GRP NOT IN ('KFNRES','REGFR','RDEGX1','KUNDSO','KUNDFR','RDEGXF','REGUFR','KFRES','RDEGX2','REGUSO')
        AND CONC_MINOR_REQMTS_MET = 'Y'
        AND STUDENT_TYPE <> 'N'
        AND COMPLETE_GPA_REQ = 'Y')
        
        OR  
        (PERCENT_CALC_75 = 'Y'
        AND PCKG_GRP IN  ('KFNRES','REGFR','KUNDSO','KUNDFR','REGUFR','KFRES','REGUSO', 'TREGFR', 'TKFRES', 'TKFNRS')
        AND CONC_MINOR_REQMTS_MET = 'Y'
        AND STUDENT_TYPE <> 'N'
        AND TEACH_PAID_PRIOR_YEAR_ONLY = 'Y')
        
        OR 
        (PCKG_GRP IN ('KFNRES','REGFR','KUNDSO','KUNDFR','REGUFR','KFRES','REGUSO','TREGFR', 'TKFRES', 'TKFNRS')
        AND CONC_MINOR_REQMTS_MET = 'Y'
        AND STUDENT_TYPE <> 'N'
        AND COMPLETE_GPA_REQ = 'Y'
        AND TEACH_PAID_PRIOR_YEAR_ONLY = 'Y') )
              
        ORDER BY NAME
        