SELECT DISTINCT
       SPRIDEN_ID,
       SPRIDEN_LAST_NAME,
       SPRIDEN_FIRST_NAME,
       SPBPERS_SSN,
       ROBUSDF_AIDY_CODE,
       ROBUSDF_VALUE_105,
       ROBUSDF_VALUE_106,
       
       (SELECT MAX (SFRTHST_TERM_CODE)
          FROM SFRTHST
         WHERE     SFRTHST_PIDM = RPRAWRD_PIDM
               AND SFRTHST_TMST_CODE IS NOT NULL)    MAX_ENROLLMENT_TERM,
               
       (SELECT MAX (RPRATRM_TERM_CODE)
          FROM RPRATRM
         WHERE     RPRATRM_PIDM = RPRAWRD_PIDM
               AND RPRATRM_FUND_CODE LIKE 'GFUT%'
               AND RPRATRM_PAID_AMT > 0)             MAX_TERM_PAID,
               
       (SELECT SUM (RPRATRM_PAID_AMT)
          FROM RPRATRM
         WHERE     RPRATRM_PIDM = RPRAWRD_PIDM
               AND RPRATRM_FUND_CODE LIKE 'GFUT%'
               AND RPRATRM_PAID_AMT > 0)             TOTAL_PAID,
               
       SHRDGMR_DEGS_CODE,
       SHRDGMR_TERM_CODE_GRAD,
       SHRDGMR_DEGC_CODE,
       SHRDGMR_COLL_CODE_1,
       SHRDGMR_MAJR_CODE_1,
       SHRDGMR_COLL_CODE_2,
       SHRDGMR_MAJR_CODE_2
       
  FROM RPRAWRD
  
       LEFT JOIN SPRIDEN
           ON RPRAWRD_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
           
       LEFT JOIN SPBPERS ON RPRAWRD_PIDM = SPBPERS_PIDM
       
       LEFT JOIN SHRDGMR
           ON     RPRAWRD_PIDM = SHRDGMR_PIDM
              AND SHRDGMR_TERM_CODE_GRAD = :Grad_Term
              
       LEFT JOIN ROBUSDF
           ON     RPRAWRD_PIDM = ROBUSDF_PIDM
              AND (   ROBUSDF_VALUE_105 IS NOT NULL
                   OR ROBUSDF_VALUE_106 IS NOT NULL)
                   
 WHERE     RPRAWRD_FUND_CODE LIKE 'GFUT%'
       AND RPRAWRD_PAID_AMT > 0
       AND SHRDGMR_DEGS_CODE IN ('PN', 'AW')