-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT DISTINCT RPRAWRD_FUND_CODE, RPRAWRD_OFFER_AMT, RPRAWRD_PAID_AMT,

RORHOLD_HOLD_CODE HOLD, RTVHOLD_DESC HOLD_DESC, RORHOLD_AIDY_CODE HOLD_AIDY, RORHOLD_PERIOD HOLD_TERM, RORHOLD_TO_DATE HOLD_EXP, RTVHOLD_DISB_IND PREVENTS_DISB

FROM RPRAWRD

LEFT JOIN SPRIDEN
ON SPRIDEN_PIDM = RPRAWRD_PIDM
AND SPRIDEN_CHANGE_IND IS NULL

LEFT JOIN RORHOLD
ON RORHOLD_PIDM = RPRAWRD_PIDM 
AND TRUNC(RORHOLD_TO_DATE) > SYSDATE 

LEFT JOIN RTVHOLD
ON RTVHOLD_CODE = RORHOLD_HOLD_CODE

WHERE RPRAWRD_AIDY_CODE = '2425'
AND RPRAWRD_FUND_CODE IN ('WIWFWE', 'WIWFWO')
AND RPRAWRD_OFFER_AMT > 0
AND RORHOLD_HOLD_CODE IS NOT NULL
AND (RORHOLD_AIDY_CODE IS NULL OR RORHOLD_AIDY_CODE = '2425')
AND (RORHOLD_PERIOD IS NULL OR RORHOLD_PERIOD IN ('202460','202480','202510'))