-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Schema fields used internally for joins/comparisons are retained where required by the query logic.
-- Do not commit query results or exports containing student records.

select RORSTAT_PGRP_CODE, RORSTAT_APRD_CODE, RCRAPP2_MODEL_CDE DEPENDENCY_STATUS,
RCRLDS4_INFC_CODE INFC_CODE,
RCRLDS4_PROC_DATE,
RCRLDS4_AGT_OVER_LIMIT_SUB EXCEEDS_SUB_LIMITS, 
RCRLDS4_AGT_OVER_LIMIT_COMB EXCEEDS_COMB_LIMITS,
RCRLDS4_LIFEMAX_LOAN_LIMIT_FLG LIFE_MAX_LIMIT, 
RCRLDS4_PAR_PLUS_LN_LIMIT_FLG PARENT_PLUS_LIMIT,
RCRLDS4_GR_AGT_OVER_LIMIT_SUB EXCEEDS_PRE_OBBBA_GRAD_PROF_SUB_LIMITS,
RCRLDS4_GR_AGT_OVER_LIMIT_COMB EXCEEDS_PRE_OBBBA_GRAD_PROF_COMB_LIMITS,
RCRLDS4_GR_COMB_LOAN_LIMIT_FLG GRAD_COMB_LIMIT_FLAG,
RCRLDS4_PR_COMB_LOAN_LIMIT_FLG PROF_COMB_LIMIT_FLAG,
RCRLDS4_AGT_UG_SUB_OPB UG_SUB_OUTSTND_PRINC_BAL,
RCRLDS4_AGT_UG_SUB_PEND_DISB UG_SUB_PEND_DISB,
RCRLDS4_AGT_UG_SUB_TOTAL UG_SUB_TOTAL,
RCRLDS4_AGT_UG_UNSUB_OPB UG_UNSUB_OUTSTND_PRINC_BAL,
RCRLDS4_AGT_UG_UNSUB_PEND_DISB UG_UNSUB_PEND_DISB,
RCRLDS4_AGT_UG_UNSUB_TOTAL UG_SUB_TOTAL,
RCRLDS4_AGT_UG_COMB_OPB UG_COMB_OUTSTND_PRINC_BAL,
RCRLDS4_AGT_UG_COMB_PEND_DISB UG_COMB_PEND_DISB,
RCRLDS4_AGT_UG_COMB_TOTAL UG_COMB_TOTAL,
RCRLDS4_AGT_UG_UNAL_CONSOL_OPB UG_UNAL_CONSOL_OUTSTND_PRINC_BAL,
RCRLDS4_AGT_UG_UNAL_CONS_TOTAL UG_UNAL_CONSOL_TOTAL,
RCRLDS4_AGT_GR_SUB_OPB GR_SUB_OUTSTND_PRINC_BAL,
RCRLDS4_AGT_GR_SUB_PEND_DISB GR_SUB_PEND_DISB,
RCRLDS4_AGT_GR_SUB_TOTAL GR_SUB_TOTAL,
RCRLDS4_AGT_GR_UNSUB_OPB GR_UNSUB_OUTSTND_PRINC_BAL,
RCRLDS4_AGT_GR_UNSUB_PEND_DISB GR_UNSUB_PEND_DISB,
RCRLDS4_AGT_GR_UNSUB_TOTAL GR_SUB_TOTAL,
RCRLDS4_AGT_GR_COMB_OPB GR_COMB_OUTSTND_PRINC_BAL,
RCRLDS4_AGT_GR_COMB_PEND_DISB GR_COMB_PEND_DISB,
RCRLDS4_AGT_GR_COMB_TOTAL GR_COMB_TOTAL,
RCRLDS4_AGT_GR_UNAL_CONSOL_OPB GR_UNAL_CONSOL_OUTSTND_PRINC_BAL,
RCRLDS4_AGT_GR_UNAL_CONS_TOTAL GR_UNAL_CONSOL_TOTAL, 
RORSTAT_PCKG_COMP_DATE PCKG_COMP_DT, 
(SELECT SUM(RPRAWRD_OFFER_AMT) FROM RPRAWRD WHERE RPRAWRD_PIDM = RCRLDS4_PIDM AND RPRAWRD_AIDY_CODE = RCRLDS4_AIDY_CODE AND RPRAWRD_FUND_CODE LIKE 'LFUUD%' AND RPRAWRD_OFFER_AMT >0) CURRENT_YEAR_UNSUB,
(SELECT SUM(RPRAWRD_OFFER_AMT) FROM RPRAWRD WHERE RPRAWRD_PIDM = RCRLDS4_PIDM AND RPRAWRD_AIDY_CODE = RCRLDS4_AIDY_CODE AND RPRAWRD_FUND_CODE LIKE 'LFUGD%' AND RPRAWRD_OFFER_AMT >0) CURRENT_YEAR_GRAD_PLUS,
ROBNYUD_VALUE_22 COD_PAR_PLUS_LEGACY, ROBNYUD_VALUE_23 COD_GRAD_PLUS_LEGACY
from RCRLDS4
LEFT JOIN RORSTAT ON RORSTAT_PIDM = RCRLDS4_PIDM AND RORSTAT_AIDY_CODE = :AIDY
left join SPRIDEN on SPRIDEN_PIDM = RCRLDS4_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN RCRAPP1 ON RCRAPP1_PIDM = RCRLDS4_PIDM AND RCRAPP1_AIDY_CODE = :AIDY AND RCRAPP1_INFC_CODE = 'EDE' AND RCRAPP1_CURR_REC_IND = 'Y'
LEFT JOIN RCRAPP2 ON RCRAPP2_PIDM = RCRLDS4_PIDM AND RCRAPP1_AIDY_CODE = RCRAPP2_AIDY_CODE AND RCRAPP1_INFC_CODE = RCRAPP2_INFC_CODE AND RCRAPP1_SEQ_NO = RCRAPP2_SEQ_NO
LEFT JOIN ROBNYUD ON ROBNYUD_PIDM = RCRLDS4_PIDM
WHERE RCRLDS4_AIDY_CODE= :AIDY
AND RCRLDS4_PROC_DATE = (SELECT MAX(Z.RCRLDS4_PROC_DATE) FROM RCRLDS4 Z WHERE Z.RCRLDS4_PIDM = SPRIDEN_PIDM AND Z.RCRLDS4_AIDY_CODE = :AIDY)