-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Schema fields used internally for joins/comparisons are retained where required by the query logic.
-- Do not commit query results or exports containing student records.

SELECT DISTINCT FLOOR((FALL_BUDGET+SPRING_BUDGET)-RCRAPP2_PELL_PGI)
FROM 
(

SELECT  RCRAPP2_PELL_PGI, RORSTAT_APRD_CODE, ROBUSDF_VALUE_207 SMR_LN,

(SELECT NVL(SUM(RPRATRM_OFFER_AMT), 0) AS "AWARDS"
FROM RPRATRM
WHERE RPRATRM_PERIOD IN ('202380','202410')
AND     RPRATRM_PIDM = SPRIDEN_PIDM
AND     RPRATRM_AIDY_CODE = :AIDY) AWARDS,

(SELECT SUM(RBRAPBC_AMT) AS "BUDGET"
FROM RBRAPBC
WHERE RBRAPBC_PERIOD IN ('202380','202410')
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PIDM = SPRIDEN_PIDM) BUDGET,

(SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PERIOD IN ('202380','X202410')
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PIDM = SPRIDEN_PIDM) FALL_BUDGET,

(SELECT SUM(RBRAPBC_AMT)
FROM RBRAPBC
WHERE RBRAPBC_PERIOD IN ('x202180','202410')
AND RBRAPBC_RUN_NAME = 'ACTUAL'
AND RBRAPBC_PBTP_CODE = 'COA'
AND RBRAPBC_PIDM = SPRIDEN_PIDM) SPRING_BUDGET,

(SELECT NVL(SUM(RPRARSC_ACTUAL_AMT),0) AS "OUTSIDE"
FROM RPRARSC
WHERE RPRARSC_AIDY_CODE = :AIDY
AND     RPRARSC_TERM_CODE IN ('202380','202410')
AND     RPRARSC_PIDM = SPRIDEN_PIDM) OUTSIDE,

(select (SFRTHST_TMST_CODE)
FROM SFRTHST
WHERE SFRTHST_PIDM = SPRIDEN_PIDM
AND     SFRTHST_TERM_CODE = '202360'
AND     SFRTHST_ACTIVITY_DATE = 
        (SELECT MAX(SFRTHST_ACTIVITY_DATE)
        FROM SFRTHST Z
        WHERE Z.SFRTHST_PIDM = SPRIDEN_PIDM
        AND Z.SFRTHST_TERM_CODE = '202360')) SMR_TMST,
        
(select (SFRTHST_TMST_CODE)
FROM SFRTHST
WHERE SFRTHST_PIDM = SPRIDEN_PIDM
AND     SFRTHST_TERM_CODE = '202380'
AND     SFRTHST_ACTIVITY_DATE = 
        (SELECT MAX(SFRTHST_ACTIVITY_DATE)
        FROM SFRTHST Z
        WHERE Z.SFRTHST_PIDM = SPRIDEN_PIDM
        AND Z.SFRTHST_TERM_CODE = '202380')) FAL_TMST,
        
(select (SFRTHST_TMST_CODE)
FROM SFRTHST
WHERE SFRTHST_PIDM = SPRIDEN_PIDM
AND     SFRTHST_TERM_CODE = '202410'
AND     SFRTHST_ACTIVITY_DATE = 
        (SELECT MAX(SFRTHST_ACTIVITY_DATE)
        FROM SFRTHST Z
        WHERE Z.SFRTHST_PIDM = SPRIDEN_PIDM
        AND Z.SFRTHST_TERM_CODE = '202410')) SPR_TMST

FROM SPRIDEN
LEFT JOIN SPBPERS ON SPRIDEN_PIDM = SPBPERS_PIDM
LEFT JOIN RCRAPP1 ON RCRAPP1_PIDM = SPRIDEN_PIDM AND RCRAPP1_AIDY_CODE = :AIDY AND RCRAPP1_INFC_CODE = 'EDE' AND RCRAPP1_CURR_REC_IND = 'Y'
LEFT JOIN RCRAPP2 ON RCRAPP2_PIDM = SPRIDEN_PIDM AND RCRAPP2_AIDY_CODE = :AIDY AND RCRAPP2_INFC_CODE = RCRAPP1_INFC_CODE AND RCRAPP2_SEQ_NO = RCRAPP1_SEQ_NO
LEFT JOIN RCRAPP4 ON RCRAPP4_PIDM = SPRIDEN_PIDM AND RCRAPP4_AIDY_CODE = :AIDY AND RCRAPP4_INFC_CODE = RCRAPP1_INFC_CODE AND RCRAPP4_SEQ_NO = RCRAPP1_SEQ_NO
LEFT JOIN RORSTAT ON SPRIDEN_PIDM = RORSTAT_PIDM AND RORSTAT_AIDY_CODE = :AIDY
LEFT JOIN RORSAPR ON SPRIDEN_PIDM = RORSAPR_PIDM
LEFT JOIN SGBSTDN ON SPRIDEN_PIDM = SGBSTDN_PIDM
LEFT JOIN ROBUSDF ON ROBUSDF_PIDM = RORSTAT_PIDM
WHERE RORSTAT_AIDY_CODE = :AIDY
AND SPRIDEN_PIDM = :PIDM
AND RORSTAT_PCKG_REQ_COMP_DATE IS NOT NULL
AND RCRAPP1_CURR_REC_IND = 'Y'
AND RORSTAT_APRD_CODE IN ('SMFLSP','xFA/SPR','xFALL','xSMRFAL')
)
WHERE NVL(SMR_TMST,'00') < '6'
OR NVL(SMR_LN, 'N') = 'N'