-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Literal student ID/SSN lists have been replaced with bind parameters where applicable.
-- Schema fields may remain internally where required for joins or comparison logic.
-- Do not commit query results or exports containing student records.

SELECT RRRAREQ_TREQ_CODE SSCARD, RRRAREQ_TRST_CODE SSCARD_STATUS, TRUNC(RRRAREQ_STAT_DATE) SSCARD_STAT_DATE,

TRUNC(RCVAPPL_CREATE_DATE) ISIR_CREATE_DATE,

CASE
WHEN TRUNC(RCVAPPL_CREATE_DATE) > TRUNC(RRRAREQ_STAT_DATE)
THEN 'Y'
ELSE 'N'
END NEW_TRANSACTION,

(SELECT DISTINCT SFRTHST_TMST_CODE
FROM SFRTHST
WHERE SFRTHST_PIDM = RRRAREQ_PIDM
AND SFRTHST_TERM_CODE = :SMR
AND SFRTHST_TMST_DATE = 
    (SELECT MAX(Z.SFRTHST_TMST_DATE)
    FROM SFRTHST Z
    WHERE Z.SFRTHST_PIDM = RRRAREQ_PIDM
    AND Z.SFRTHST_TERM_CODE = :SMR)) SMR_TMST,

(SELECT DISTINCT SFRTHST_TMST_CODE
FROM SFRTHST
WHERE SFRTHST_PIDM = RRRAREQ_PIDM
AND SFRTHST_TERM_CODE = :FALL
AND SFRTHST_TMST_DATE = 
    (SELECT MAX(Z.SFRTHST_TMST_DATE)
    FROM SFRTHST Z
    WHERE Z.SFRTHST_PIDM = RRRAREQ_PIDM
    AND Z.SFRTHST_TERM_CODE = :FALL)) FALL_TMST,

(SELECT DISTINCT SFRTHST_TMST_CODE
FROM SFRTHST
WHERE SFRTHST_PIDM = RRRAREQ_PIDM
AND SFRTHST_TERM_CODE = :SPR
AND SFRTHST_TMST_DATE = 
    (SELECT MAX(Z.SFRTHST_TMST_DATE)
    FROM SFRTHST Z
    WHERE Z.SFRTHST_PIDM = RRRAREQ_PIDM
    AND Z.SFRTHST_TERM_CODE = :SPR)) SPR_TMST,

RORMESG_MESG_CODE VSSC, TRUNC(RORMESG_EXPIRATION_DATE) VSSC_EXP_DATE,

CASE
WHEN NVL(RCRAPP1_SSN,0) = NVL(SPBPERS_SSN,0)
THEN 'MATCH'
WHEN NVL(RCRAPP1_SSN,0) <> NVL(SPBPERS_SSN,0)
THEN 'MISMATCH'
ELSE NULL
END SSN_MATCH

FROM RRRAREQ

LEFT JOIN RORMESG
ON RORMESG_PIDM = RRRAREQ_PIDM
AND RORMESG_AIDY_CODE = RRRAREQ_AIDY_CODE
AND RORMESG_MESG_CODE = 'VSSC'

LEFT JOIN RCVAPPL
ON RCVAPPL_PIDM = RRRAREQ_PIDM
AND RCVAPPL_AIDY_CODE = RRRAREQ_AIDY_CODE
AND RCVAPPL_INFC_CODE = 'EDE'
AND RCVAPPL_CURR_REC_IND = 'Y'

LEFT JOIN SPBPERS
ON SPBPERS_PIDM = RRRAREQ_PIDM

LEFT JOIN RCRAPP1
ON RCRAPP1_PIDM = RRRAREQ_PIDM
AND RCRAPP1_AIDY_CODE = RRRAREQ_AIDY_CODE
AND RCRAPP1_INFC_CODE = 'EDE'
AND RCRAPP1_CURR_REC_IND = 'Y'

WHERE RRRAREQ_TREQ_CODE = 'SSCARD'
AND RRRAREQ_AIDY_CODE = :AIDY
