-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Literal student ID/SSN lists have been replaced with bind parameters where applicable.
-- Schema fields may remain internally where required for joins or comparison logic.
-- Do not commit query results or exports containing student records.

SELECT SMR_SAP, FAL_SAP, SPR_SAP, SGASTDN_TERM, STATUS, LEVL, STYPE, DEGR, STU_PROGRM,

(SELECT SGBSTDN_TERM_CODE_EFF
FROM SGBSTDN 
WHERE SGBSTDN_PIDM = PIDM
AND SGBSTDN_TERM_CODE_EFF = 
    (SELECT MIN(Z.SGBSTDN_TERM_CODE_EFF)
    from SGBSTDN Z
    WHERE Z.SGBSTDN_PIDM = PIDM
    AND Z.SGBSTDN_TERM_CODE_EFF >= :SGASTDN_TERM)
AND SGBSTDN_STST_CODE = 'AS') FUTURE_AS_SGASTDN,

SMR_TMST

FROM(
SELECT SPRIDEN_PIDM PIDM,

X.RORSAPR_SAPR_CODE SMR_SAP, Z.RORSAPR_SAPR_CODE FAL_SAP, Y.RORSAPR_SAPR_CODE SPR_SAP, SGBSTDN_TERM_CODE_EFF SGASTDN_TERM,

SGBSTDN_STST_CODE STATUS, SGBSTDN_LEVL_CODE LEVL, SGBSTDN_STYP_CODE STYPE, SGBSTDN_DEGC_CODE_1 DEGR, SGBSTDN_PROGRAM_1 STU_PROGRM,

(SELECT SFRTHST_TMST_CODE
FROM SFRTHST
WHERE SFRTHST_PIDM = Z.RORSAPR_PIDM
AND SFRTHST_TMST_DATE = 
    (SELECT MAX(SFRTHST_TMST_DATE)
    FROM SFRTHST B
    WHERE B.SFRTHST_PIDM = Z.RORSAPR_PIDM
    AND B.SFRTHST_TERM_CODE = :TMST_TERM)) SMR_TMST

FROM SPRIDEN

LEFT JOIN RORSAPR X
ON X.RORSAPR_PIDM = SPRIDEN_PIDM
AND X.RORSAPR_TERM_CODE = :SMR_SAP

LEFT JOIN RORSAPR Z
ON Z.RORSAPR_PIDM = SPRIDEN_PIDM
AND Z.RORSAPR_TERM_CODE = :FALL_SAP

LEFT JOIN RORSAPR Y
ON Y.RORSAPR_PIDM = SPRIDEN_PIDM
AND Y.RORSAPR_TERM_CODE = :SPR_SAP

LEFT JOIN SGBSTDN
ON SGBSTDN_PIDM = SPRIDEN_PIDM

WHERE SPRIDEN_CHANGE_IND IS NULL
AND (Z.RORSAPR_SAPR_CODE IN ('AAFA','ACFA','ASFA','AMFA', 'ACLR')
OR X.RORSAPR_SAPR_CODE IN ('AASU','AMSU','ACSU','ASSU', 'ACLR')
OR Y.RORSAPR_SAPR_CODE IN ('AESP','AASP', 'AMSP', 'ASSP', 'ACSP', 'ACLR'))
AND SGBSTDN_TERM_CODE_EFF = 
    (SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    from SGBSTDN A
    WHERE A.SGBSTDN_PIDM = SPRIDEN_PIDM
    AND A.SGBSTDN_TERM_CODE_EFF <= :SGASTDN_TERM)
AND SGBSTDN_STST_CODE = 'IS')
