-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Literal student ID/SSN lists have been replaced with bind parameters where applicable.
-- Schema fields may remain internally where required for joins or comparison logic.
-- Do not commit query results or exports containing student records.

select RWBPLAP_FUND_CODE APP_FUND, RPRLAPP_FUND_CODE LN_FUND_CODE, RPRAWRD_FUND_CODE AWD_FUND,
        RWBPLAP_REQUESTED_AMT APP_REQ_AMT,
        RPRLAPP_REQUEST_AMT BNR_REQ_AMT, RPRAWRD_ACCEPT_AMT AWARD_AMT, (RWBPLAP_REQUESTED_AMT - RPRAWRD_ACCEPT_AMT) REQ_V_AWD,
        RWBPLAP_LOAN_PERIOD_BEGIN APP_LPRD_BEGIN, RWBPLAP_LOAN_PERIOD_END APP_LPRD_END,
        RPRLAPP_LPRD_START_DATE BNR_LPRD_BEGIN, RPRLAPP_LPRD_END_DATE BNR_LPRD_END,
        A.RPRATRM_ACCEPT_AMT SMR_ACPT_AMT, B.RPRATRM_ACCEPT_AMT FAL_ACPT_AMT, C.RPRATRM_ACCEPT_AMT SPR_ACPT_AMT,
        RPRLCRT_EXP_GRAD_MTH_YR EXP_GRAD, RPRLCRT_CINT_CODE CERT_INT, RPRLCRT_CERT_DATE CERT_DT,
        RPRLAPP_ALT_LOAN_SB_IND STU_BORR, RPRLAPP_CRED_DIF_NM_IND CREDIT_DIFF_NAME,
        RPRLAPP_ALT_BOR_LOAN_DEBT TOTAL_DEBT, RPRLAPP_ALT_LOAN_PROG_TYPE_CDE PROG_TYP,
        RWBPLAP_BATCH_DATE BTCH_DATE, RWBPLAP_ACTIVITY_DATE ACTIVITY_DATE,

G.RRRAREQ_TRST_CODE NSLDSA_STATUS, H.RRRAREQ_TRST_CODE NSLDSR_STATUS,
        I.RRRAREQ_TRST_CODE VERIF_STATUS,
        SGBSTDN_RATE_CODE RATE_CODE, D.RBRAPBG_PBGP_CODE SMR_PBGP,
        (SELECT SUM(RBRAPBC_AMT)
        FROM RBRAPBC
        WHERE RBRAPBC_PIDM = RPRAWRD_PIDM
        AND     RBRAPBC_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND     RBRAPBC_RUN_NAME = 'ACTUAL'
        AND     RBRAPBC_PERIOD = :SMR_PRD
        AND     RBRAPBC_PBTP_CODE = 'COA') SMR_COA,

        (SELECT SUM(RPRATRM_OFFER_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :SMR_PRD
        AND     RPRATRM_OFFER_AMT >0) SMR_OFFER_AID,

        ((SELECT SUM(RBRAPBC_AMT)
        FROM RBRAPBC
        WHERE RBRAPBC_PIDM = RPRAWRD_PIDM
        AND     RBRAPBC_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND     RBRAPBC_RUN_NAME = 'ACTUAL'
        AND     RBRAPBC_PERIOD = :SMR_PRD
        AND     RBRAPBC_PBTP_CODE = 'COA') -

        (SELECT SUM(NVL(RPRATRM_OFFER_AMT,0))
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :SMR_PRD
        AND     RPRATRM_OFFER_AMT >0))SMR_COA_LESS_OFRD,

        (SELECT SUM(RPRATRM_OFFER_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :SMR_PRD
        AND     RPRATRM_FUND_CODE NOT LIKE 'LEU%'
        AND     RPRATRM_OFFER_AMT >0) SMR_NO_LEU_AID,

        (SELECT SUM(RPRATRM_OFFER_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :SMR_PRD
        AND     RPRATRM_ACCEPT_AMT >0) SMR_ACPT_AID,

        (SELECT SUM(RPRATRM_ACCEPT_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :SMR_PRD
        AND     RPRATRM_FUND_CODE NOT LIKE 'LEU%'
        AND     RPRATRM_ACCEPT_AMT > 0) SMR_ACPT_NO_LEU_AID,

        (SELECT SUM(SFRSTCR_CREDIT_HR)
        FROM SFRSTCR
        WHERE SFRSTCR_PIDM = RPRAWRD_PIDM
        AND     SFRSTCR_TERM_CODE = :SMR_PRD
        AND     SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2')
        AND     SFRSTCR_LEVL_CODE = 'UG') SMR_UG_HRS,

        (SELECT SUM(SFRSTCR_CREDIT_HR)
        FROM SFRSTCR
        WHERE SFRSTCR_PIDM = RPRAWRD_PIDM
        AND     SFRSTCR_TERM_CODE = :SMR_PRD
        AND     SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2')
        AND     SFRSTCR_LEVL_CODE = 'GR') SMR_GR_HRS,

        E.RBRAPBG_PBGP_CODE FAL_PBGP,

        (SELECT SUM(RBRAPBC_AMT)
        FROM RBRAPBC
        WHERE RBRAPBC_PIDM = RPRAWRD_PIDM
        AND     RBRAPBC_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND     RBRAPBC_RUN_NAME = 'ACTUAL'
        AND     RBRAPBC_PERIOD = :FAL_PRD
        AND     RBRAPBC_PBTP_CODE = 'COA') FAL_COA,

        (SELECT SUM(RPRATRM_OFFER_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :FAL_PRD
        AND     RPRATRM_OFFER_AMT > 0) FAL_OFFER_AID,

        ((SELECT SUM(RBRAPBC_AMT)
        FROM RBRAPBC
        WHERE RBRAPBC_PIDM = RPRAWRD_PIDM
        AND     RBRAPBC_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND     RBRAPBC_RUN_NAME = 'ACTUAL'
        AND     RBRAPBC_PERIOD = :FAL_PRD
        AND     RBRAPBC_PBTP_CODE = 'COA') -
        (SELECT SUM(NVL(RPRATRM_OFFER_AMT,0))
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :FAL_PRD
        AND     RPRATRM_OFFER_AMT > 0)) FAL_COA_LESS_OFRD,

        (SELECT SUM(RPRATRM_OFFER_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :FAL_PRD
        AND     RPRATRM_FUND_CODE NOT LIKE 'LEU%'
        AND     RPRATRM_OFFER_AMT > 0) FAL_OFRD_NO_LEU_AID,

        (SELECT SUM(RPRATRM_ACCEPT_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :FAL_PRD
        AND     RPRATRM_ACCEPT_AMT > 0) FAL_ACPT_AID,

        (SELECT SUM(RPRATRM_ACCEPT_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :FAL_PRD
        AND     RPRATRM_FUND_CODE NOT LIKE 'LEU%'
        AND     RPRATRM_ACCEPT_AMT > 0) FAL_ACPT_NO_LEU_AID,

        (SELECT SUM(SFRSTCR_CREDIT_HR)
        FROM SFRSTCR
        WHERE SFRSTCR_PIDM = RPRAWRD_PIDM
        AND     SFRSTCR_TERM_CODE = :FAL_PRD
        AND     SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2')
        AND     SFRSTCR_LEVL_CODE = 'UG') FAL_UG_HRS,

        (SELECT SUM(SFRSTCR_CREDIT_HR)
        FROM SFRSTCR
        WHERE SFRSTCR_PIDM = RPRAWRD_PIDM
        AND     SFRSTCR_TERM_CODE = :FAL_PRD
        AND     SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2')
        AND     SFRSTCR_LEVL_CODE = 'GR') FAL_GR_HRS,

        F.RBRAPBG_PBGP_CODE SPR_PBGP,

        (SELECT SUM(RBRAPBC_AMT)
        FROM RBRAPBC
        WHERE RBRAPBC_PIDM = RPRAWRD_PIDM
        AND     RBRAPBC_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND     RBRAPBC_RUN_NAME = 'ACTUAL'
        AND     RBRAPBC_PERIOD = :SPR_PRD
        AND     RBRAPBC_PBTP_CODE = 'COA') SPR_COA,

        (SELECT SUM(RPRATRM_OFFER_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :SPR_PRD
        AND     RPRATRM_OFFER_AMT > 0) SPR_OFFER_AID,

        ((SELECT SUM(RBRAPBC_AMT)
        FROM RBRAPBC
        WHERE RBRAPBC_PIDM = RPRAWRD_PIDM
        AND     RBRAPBC_AIDY_CODE = RPRAWRD_AIDY_CODE
        AND     RBRAPBC_RUN_NAME = 'ACTUAL'
        AND     RBRAPBC_PERIOD = :SPR_PRD
        AND     RBRAPBC_PBTP_CODE = 'COA') -
        (SELECT SUM(NVL(RPRATRM_OFFER_AMT,0))
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :SPR_PRD
        AND     RPRATRM_OFFER_AMT > 0)) SPR_COA_LESS_OFRD,

        (SELECT SUM(RPRATRM_OFFER_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :SPR_PRD
        AND     RPRATRM_FUND_CODE NOT LIKE 'LEU%'
        AND     RPRATRM_OFFER_AMT > 0) SPR_OFF_NO_LEU_AID,

        (SELECT SUM(RPRATRM_ACCEPT_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :SPR_PRD
        AND     RPRATRM_ACCEPT_AMT > 0) SPR_ACCEPT_AID,

        (SELECT SUM(RPRATRM_ACCEPT_AMT)
        FROM RPRATRM
        WHERE RPRATRM_PIDM = RPRAWRD_PIDM
        AND     RPRATRM_PERIOD = :SPR_PRD
        AND     RPRATRM_FUND_CODE NOT LIKE 'LEU%'
        AND     RPRATRM_ACCEPT_AMT > 0) SPR_ACPT_NO_LEU_AID,

        (SELECT SUM(SFRSTCR_CREDIT_HR)
        FROM SFRSTCR
        WHERE SFRSTCR_PIDM = RPRAWRD_PIDM
        AND     SFRSTCR_TERM_CODE = :SPR_PRD
        AND     SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2')
        AND     SFRSTCR_LEVL_CODE = 'UG') SPR_UG_HRS,

        (SELECT SUM(SFRSTCR_CREDIT_HR)
        FROM SFRSTCR
        WHERE SFRSTCR_PIDM = RPRAWRD_PIDM
        AND     SFRSTCR_TERM_CODE = :SPR_PRD
        AND     SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2')
        AND     SFRSTCR_LEVL_CODE = 'GR') SPR_GR_HRS,

  J.RORSAPR_SAPR_CODE SMR_SAP, K.RORSAPR_SAPR_CODE FAL_SAP, L.RORSAPR_SAPR_CODE SPR_SAP,
  RORSTAT_PCKG_COMP_DATE PCKG_DT,

SGBSTDN_COLL_CODE_1 COLL_1, SGBSTDN_PROGRAM_1 PROG_1, SGBSTDN_COLL_CODE_2 COLL_2, SGBSTDN_PROGRAM_2 PROG_2

from rprawrd

left join rpratrm a
on          rprawrd_pidm = a.rpratrm_pidm
and         rprawrd_fund_code = a.rpratrm_fund_code
and         a.rpratrm_period = :SMR_PRD

left join rpratrm b
on          rprawrd_pidm = b.rpratrm_pidm
and         rprawrd_fund_code = b.rpratrm_fund_code
and         b.rpratrm_period = :FAL_PRD

left join rpratrm c
on          rprawrd_pidm = c.rpratrm_pidm
and         rprawrd_fund_code = c.rpratrm_fund_code
and         c.rpratrm_period = :SPR_PRD

left join rprlapp
on          rprawrd_pidm = rprlapp_pidm
and         rprawrd_aidy_code = rprlapp_aidy_code
and         rprawrd_fund_code = rprlapp_fund_code

left join rprlcrt
on      rprawrd_pidm = rprlcrt_pidm
and     rprlapp_fund_code = rprlcrt_fund_code
and     rprlapp_appl_no = rprlcrt_appl_no

left join rbrapbg D
on      D.rbrapbg_pidm = RPRAWRD_pidm
and     D.rbrapbg_aidy_code = RPRAWRD_aidy_code
and     D.rbrapbg_run_name = 'ACTUAL'
AND     D.RBRAPBG_PERIOD = :SMR_PRD

left join rbrapbg E
on      E.rbrapbg_pidm = RPRAWRD_pidm
and     E.rbrapbg_aidy_code = RPRAWRD_aidy_code
and     E.rbrapbg_run_name = 'ACTUAL'
AND     E.RBRAPBG_PERIOD = :FAL_PRD

left join rbrapbg F
on      F.rbrapbg_pidm = RPRAWRD_pidm
and     F.rbrapbg_aidy_code = RPRAWRD_aidy_code
and     F.rbrapbg_run_name = 'ACTUAL'
AND     F.RBRAPBG_PERIOD = :SPR_PRD

LEFT JOIN RRRAREQ G
ON          G.RRRAREQ_PIDM = RPRAWRD_PIDM
AND         G.RRRAREQ_AIDY_CODE = :AIDY
AND         G.RRRAREQ_TREQ_CODE = 'NSLDSA'

LEFT JOIN RRRAREQ H
ON          H.RRRAREQ_PIDM = RPRAWRD_PIDM
AND         H.RRRAREQ_AIDY_CODE = :AIDY
AND         H.RRRAREQ_TREQ_CODE = 'NSLDSR'

LEFT JOIN RRRAREQ I
ON          I.RRRAREQ_PIDM = RPRAWRD_PIDM
AND         I.RRRAREQ_AIDY_CODE = :AIDY
AND         I.RRRAREQ_TREQ_CODE = 'VERIF'

LEFT JOIN RORSAPR J
ON          RPRAWRD_PIDM = J.RORSAPR_PIDM
AND         J.RORSAPR_TERM_CODE = :SMR_PRD

LEFT JOIN RORSAPR K
ON          RPRAWRD_PIDM = K.RORSAPR_PIDM
AND         K.RORSAPR_TERM_CODE = :FAL_PRD

LEFT JOIN RORSAPR L
ON          RPRAWRD_PIDM = L.RORSAPR_PIDM
AND         L.RORSAPR_TERM_CODE = :SPR_PRD

LEFT JOIN SGBSTDN
ON          RPRAWRD_PIDM = SGBSTDN_PIDM

LEFT JOIN RWBPLAP
ON          RPRAWRD_PIDM = RWBPLAP_PIDM
AND         RPRAWRD_AIDY_CODE = RWBPLAP_AIDY_CODE
AND         RPRAWRD_FUND_CODE = RWBPLAP_FUND_CODE

LEFT JOIN RORSTAT
ON          RORSTAT_PIDM = RPRAWRD_PIDM
AND         RORSTAT_AIDY_CODE = RPRAWRD_AIDY_CODE

where rprawrd_aidy_code = :AIDY
and     RWBPLAP_fund_code not like '_____X'
and     rprawrd_accept_amt > 0
AND     SGBSTDN_TERM_CODE_EFF =
        (SELECT MAX(SGBSTDN_TERM_CODE_EFF)
        FROM SGBSTDN_AUDIT G
        WHERE G.SGBSTDN_PIDM = RPRAWRD_PIDM
        AND G.SGBSTDN_TERM_CODE_EFF <= :SPR_PRD)

 ORDER BY RWBPLAP_BATCH_DATE DESC
