/*
FERPA-SAFE PUBLIC VERSION
Direct student/borrower identifiers have been removed or masked from the final result set where practical.
Hard-coded student IDs, SSNs, personal email values, individualized free-text output, and staff user identifiers were removed or parameterized where applicable.
Schema fields may remain internally where required for joins, filtering, calculation, or comparison logic.
This repository contains SQL code only. Do not commit query output or student-level data.
*/

--UPDATE FREEZE DATE FOR EACH TERM: TRUNC(B.SFRSTCA_ACTIVITY_DATE) >= TO_DATE('19-JAN-2026', 'DD-MON-YYYY'))

SELECT
BID, 
FNAME,
LNAME,
CRN,
STATUS_MESS,
CREDIT_HRS,
BF_ACTIVITY_DATE,
BF_STATUS_CODE,
AF_ACTIVITY_DATE,
AF_STATUS_CODE,
RPRATRM_FUND_CODE

FROM
(SELECT
NULL AS BID,
NULL AS FNAME,
NULL AS LNAME,
A.SFRSTCA_TERM_CODE,
A.SFRSTCA_CRN CRN,
A.SFRSTCA_MESSAGE STATUS_MESS,
A.SFRSTCA_CREDIT_HR CREDIT_HRS,
A.SFRSTCA_ACTIVITY_DATE BF_ACTIVITY_DATE,
A.SFRSTCA_RSTS_CODE BF_STATUS_CODE,
B.SFRSTCA_ACTIVITY_DATE AF_ACTIVITY_DATE,
B.SFRSTCA_RSTS_CODE AF_STATUS_CODE,
RPRATRM_FUND_CODE

FROM 
SFRSTCA A

JOIN
SFRSTCA B
ON A.SFRSTCA_PIDM = B.SFRSTCA_PIDM
AND A.SFRSTCA_CRN = B.SFRSTCA_CRN

JOIN SPRIDEN
ON SPRIDEN_PIDM = A.SFRSTCA_PIDM
AND SPRIDEN_PIDM = B.SFRSTCA_PIDM
AND SPRIDEN_CHANGE_IND IS NULL

JOIN RPRATRM
ON A.SFRSTCA_PIDM = RPRATRM_PIDM
AND RPRATRM_PERIOD = '202660'
AND RPRATRM_FUND_CODE IN ('GFNPEL', 'GFUTGU', 'GFUTGG', 'GSNPPF', 'GSNPPP')

 WHERE A.SFRSTCA_TERM_CODE = '202660'
       AND A.SFRSTCA_SOURCE_CDE = 'BASE' 
       AND A.SFRSTCA_RSTS_CODE LIKE 'N%'
       AND TRUNC(A.SFRSTCA_ACTIVITY_DATE) < TO_DATE('27-MAY-2026', 'DD-MON-YYYY')
       AND B.SFRSTCA_RSTS_CODE NOT LIKE 'N%'
       AND TRUNC(B.SFRSTCA_ACTIVITY_DATE) >= TO_DATE('27-MAY-2026', 'DD-MON-YYYY'))
       

       ---May 27 - 202660
       ---August 25 - 202580
       ---January 19 - 202610
