select DISTINCT SPRIDEN_ID ID, SPRIDEN_LAST_NAME LANME, SPRIDEN_FIRST_NAME FNAME, SSBSECT_SUBJ_CODE, RPRATRM_FUND_CODE FUND, RPRATRM_OFFER_AMT, RPRATRM_PAID_AMT PD_AMT,RRRAREQ_TREQ_CODE STUDSA,RRRAREQ_TRST_CODE STUDSA_STATUS

from RPRATRM

LEFT JOIN SPRIDEN
ON          RPRATRM_PIDM = SPRIDEN_PIDM
AND         SPRIDEN_CHANGE_IND IS NULL

LEFT JOIN SFRSTCR
ON          RPRATRM_PIDM = SFRSTCR_PIDM
AND         SFRSTCR_TERM_CODE in (:SUM_TRM, :FAL_TRM, :SPR_TERM)

LEFT JOIN SSBSECT 
---ON          SSBSECT_PIDM = RPRATRM_PIDM
ON         SSBSECT_CRN = SFRSTCR_CRN
AND         SSBSECT_TERM_CODE = SFRSTCR_TERM_CODE


LEFT JOIN RRRAREQ
ON          RRRAREQ_PIDM = RPRATRM_PIDM
AND         RRRAREQ_AIDY_CODE = :AIDY
AND         RRRAREQ_TREQ_CODE = 'STUDSA'

WHERE RPRATRM_OFFER_AMT > '0'
AND    SSBSECT_SUBJ_CODE = 'OGE'
AND    RPRATRM_FUND_CODE LIKE '_F%'
AND    RPRATRM_PERIOD in (:SUM_TRM, :FAL_TRM, :SPR_TERM)
AND    RRRAREQ_TREQ_CODE is null
