-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Literal student ID/SSN lists have been replaced with bind parameters where applicable.
-- Schema fields may remain internally where required for joins or comparison logic.
-- Do not commit query results or exports containing student records.

WITH BASE AS(
SELECT RPVARPY_PIDM PIDM, RPVARPY_TERM_CODE TERM, RPVARPY_TYPE_CODE TYPE, TBBEXPT_EXEMPTION_CODE EXEMPTION_CODE,
RPVARPY_DETAIL_CODE DETAIL_CODE,

CASE
WHEN RPVARPY_DETAIL_CODE IN ('KAFM','DLSW','KXAC')
THEN 'WIWFWO'
WHEN RPVARPY_DETAIL_CODE NOT IN ('KAFM', 'DLSW','KXAC')
THEN 'WIWFWE'
END WAIVER_TYPE,

TBBEXPT_DESC DETAIL_CODE_DESC, SUM(RPVARPY_AMOUNT) AMOUNT

FROM RPVARPY, TBBEXPT

WHERE RPVARPY_AIDY_CODE = :AIDY
AND RPVARPY_TERM_CODE = :RPAARSC_TERM
and RPVARPY_TERM_CODE = TBBEXPT_TERM_CODE
and TBBEXPT_DETAIL_CODE = RPVARPY_DETAIL_CODE
AND NVL(RPVARPY_AMOUNT,0) > 0
AND TBBEXPT_EXEMPTION_CODE NOT IN 
    (SELECT RPREXPT_EXEMPTION_CODE
        FROM RPREXPT
     WHERE TBBEXPT_EXEMPTION_CODE = RPREXPT_EXEMPTION_CODE
     AND TBBEXPT_TERM_CODE = RPREXPT_TERM_CODE)
     
GROUP BY RPVARPY_PIDM, RPVARPY_TERM_CODE, RPVARPY_TYPE_CODE, TBBEXPT_EXEMPTION_CODE,
RPVARPY_DETAIL_CODE, TBBEXPT_DESC
),

FWE_TOTAL AS
(SELECT RPVARPY_PIDM PIDM,RPVARPY_TERM_CODE TERM, SUM(RPVARPY_AMOUNT) FWE_TOTAL

FROM RPVARPY, TBBEXPT

WHERE RPVARPY_AIDY_CODE = :AIDY
AND RPVARPY_TERM_CODE = :RPAARSC_TERM
and RPVARPY_TERM_CODE = TBBEXPT_TERM_CODE
and RPVARPY_DETAIL_CODE NOT in ('KAFM', 'DLSW','KXAC')
and TBBEXPT_DETAIL_CODE = RPVARPY_DETAIL_CODE
AND NVL(RPVARPY_AMOUNT,0) > 0
AND TBBEXPT_EXEMPTION_CODE NOT IN 
    (SELECT RPREXPT_EXEMPTION_CODE
        FROM RPREXPT
     WHERE TBBEXPT_EXEMPTION_CODE = RPREXPT_EXEMPTION_CODE
     AND TBBEXPT_TERM_CODE = RPREXPT_TERM_CODE)
     
GROUP BY RPVARPY_PIDM, RPVARPY_TERM_CODE
),

FWO_TOTAL AS
(SELECT RPVARPY_PIDM PIDM,RPVARPY_TERM_CODE TERM, SUM(RPVARPY_AMOUNT) FWO_TOTAL

FROM RPVARPY, TBBEXPT

WHERE RPVARPY_AIDY_CODE = :AIDY
AND RPVARPY_TERM_CODE = :RPAARSC_TERM
and RPVARPY_TERM_CODE = TBBEXPT_TERM_CODE
and RPVARPY_DETAIL_CODE IN ('DLSW','KXAC')
and TBBEXPT_DETAIL_CODE = RPVARPY_DETAIL_CODE
AND NVL(RPVARPY_AMOUNT,0) > 0
AND TBBEXPT_EXEMPTION_CODE NOT IN 
    (SELECT RPREXPT_EXEMPTION_CODE
        FROM RPREXPT
     WHERE TBBEXPT_EXEMPTION_CODE = RPREXPT_EXEMPTION_CODE
     AND TBBEXPT_TERM_CODE = RPREXPT_TERM_CODE)
     
GROUP BY RPVARPY_PIDM, RPVARPY_TERM_CODE
)

SELECT RORSTAT_APRD_CODE APRD, BASE.TERM, BASE.DETAIL_CODE, BASE.DETAIL_CODE_DESC,
BASE.AMOUNT, 
FWE_TOTAL, FWO_TOTAL,

RPRATRM_PERIOD RPAAWRD_PERIOD, RPRATRM_FUND_CODE RPAAWRD_FUND_CODE, RPRATRM_OFFER_AMT RPAAWRD_OFFER

FROM BASE

LEFT JOIN RORSTAT
ON RORSTAT_PIDM = BASE.PIDM
AND RORSTAT_AIDY_CODE = :AIDY

LEFT JOIN FWE_TOTAL
ON FWE_TOTAL.PIDM = BASE.PIDM
AND BASE.WAIVER_TYPE = 'WIWFWE'

LEFT JOIN FWO_TOTAL
ON FWO_TOTAL.PIDM = BASE.PIDM
AND BASE.WAIVER_TYPE = 'WIWFWO'

LEFT JOIN RPRATRM
ON RPRATRM_PIDM = BASE.PIDM
AND BASE.WAIVER_TYPE = RPRATRM_FUND_CODE
AND RPRATRM_PERIOD = :RPAAWRD_TERM
AND RPRATRM_OFFER_AMT > 0

WHERE NVL(RPRATRM_OFFER_AMT,0) <> COALESCE(FWE_TOTAL, FWO_TOTAL)
ORDER BY BASE.WAIVER_TYPE, BASE.DETAIL_CODE
