-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Schema fields used internally for joins/comparisons are retained where required by the query logic.
-- Do not commit query results or exports containing student records.

(Select RORSTAT_PGRP_CODE, 
RRRAREQ_TREQ_CODE, RRRAREQ_TRST_CODE STATUS, RORHOLD_PERIOD HOLD_TERM,  
RORHOLD_TO_DATE EXP_DATE, RORMESG_MESG_CODE, 'CLEAR SPR REQUIREMENT' AS ACTION
from RORSTAT
left join SPRIDEN on RORSTAT_PIDM = SPRIDEN_PIDM and SPRIDEN_CHANGE_IND is null
left join RRRAREQ on RORSTAT_PIDM = RRRAREQ_PIDM and RORSTAT_AIDY_CODE = RRRAREQ_AIDY_CODE and RRRAREQ_TREQ_CODE = 'ADVSXS'
left join RORHOLD on RORSTAT_PIDM = RORHOLD_PIDM and RORHOLD_HOLD_CODE = 'DP'
left join RORMESG on RORSTAT_PIDM = RORMESG_PIDM and RORSTAT_AIDY_CODE = RORMESG_AIDY_CODE and RORMESG_MESG_CODE = 'XDGS'
where (RRRAREQ_TRST_CODE = 'R' and RORSTAT_AIDY_CODE = :Aid_Year and RORHOLD_PERIOD = :SPR_TERM and RORHOLD_TO_DATE <= sysdate))
UNION
(Select RORSTAT_PGRP_CODE,RRRAREQ_TREQ_CODE, RRRAREQ_TRST_CODE STATUS, RORHOLD_PERIOD HOLD_TERM, RORHOLD_TO_DATE EXP_DATE, RORMESG_MESG_CODE, 'EXP SPR HOLD' AS ACTION
from RORSTAT
left join SPRIDEN on RORSTAT_PIDM = SPRIDEN_PIDM and SPRIDEN_CHANGE_IND is null
left join RRRAREQ on RORSTAT_PIDM = RRRAREQ_PIDM and RORSTAT_AIDY_CODE = RRRAREQ_AIDY_CODE and RRRAREQ_TREQ_CODE = 'ADVSXS'
left join RORHOLD on RORSTAT_PIDM = RORHOLD_PIDM and RORHOLD_HOLD_CODE = 'DP'
left join RORMESG on RORSTAT_PIDM = RORMESG_PIDM and RORSTAT_AIDY_CODE = RORMESG_AIDY_CODE and RORMESG_MESG_CODE = 'XDGS'
where (RRRAREQ_TRST_CODE in ('C','W') and RORSTAT_AIDY_CODE = :Aid_Year and RORHOLD_PERIOD = :SPR_TERM and (RORHOLD_TO_DATE > sysdate or RORHOLD_TO_DATE is null)))
UNION
(Select RORSTAT_PGRP_CODE,RRRAREQ_TREQ_CODE, RRRAREQ_TRST_CODE STATUS, RORHOLD_PERIOD HOLD_TERM, RORHOLD_TO_DATE EXP_DATE, RORMESG_MESG_CODE,'ADD SPR ROAMESG' AS ACTION
from RORSTAT
left join SPRIDEN on RORSTAT_PIDM = SPRIDEN_PIDM and SPRIDEN_CHANGE_IND is null
left join RRRAREQ on RORSTAT_PIDM = RRRAREQ_PIDM and RORSTAT_AIDY_CODE = RRRAREQ_AIDY_CODE and RRRAREQ_TREQ_CODE = 'ADVSXS'
left join RORHOLD on RORSTAT_PIDM = RORHOLD_PIDM and RORHOLD_HOLD_CODE = 'DP'
left join RORMESG on RORSTAT_PIDM = RORMESG_PIDM and RORSTAT_AIDY_CODE = RORMESG_AIDY_CODE and RORMESG_MESG_CODE = 'XDGS'
where RRRAREQ_TRST_CODE in ('C','W') and RORSTAT_AIDY_CODE = :Aid_Year and RORMESG_MESG_CODE is null)
UNION
(Select RORSTAT_PGRP_CODE,RRRAREQ_TREQ_CODE, RRRAREQ_TRST_CODE STATUS, RORHOLD_PERIOD HOLD_TERM,RORHOLD_TO_DATE EXP_DATE, RORMESG_MESG_CODE,'CLEAR FAL REQUIREMENT' AS ACTION
from RORSTAT
left join SPRIDEN on RORSTAT_PIDM = SPRIDEN_PIDM and SPRIDEN_CHANGE_IND is null
left join RRRAREQ on RORSTAT_PIDM = RRRAREQ_PIDM and RORSTAT_AIDY_CODE = RRRAREQ_AIDY_CODE and RRRAREQ_TREQ_CODE = 'ADVSXF'
left join RORHOLD on RORSTAT_PIDM = RORHOLD_PIDM and RORHOLD_HOLD_CODE = 'DP'
left join RORMESG on RORSTAT_PIDM = RORMESG_PIDM and RORSTAT_AIDY_CODE = RORMESG_AIDY_CODE and RORMESG_MESG_CODE = 'XDGF'
where (RRRAREQ_TRST_CODE = 'R' and RORSTAT_AIDY_CODE = :Aid_Year and RORHOLD_PERIOD = :FAL_TERM and RORHOLD_TO_DATE <= sysdate))
UNION
(Select RORSTAT_PGRP_CODE,RRRAREQ_TREQ_CODE, RRRAREQ_TRST_CODE STATUS,RORHOLD_PERIOD HOLD_TERM,RORHOLD_TO_DATE EXP_DATE, RORMESG_MESG_CODE,'EXP FAL HOLD' AS ACTION
from RORSTAT
left join SPRIDEN on RORSTAT_PIDM = SPRIDEN_PIDM and SPRIDEN_CHANGE_IND is null
left join RRRAREQ on RORSTAT_PIDM = RRRAREQ_PIDM and RORSTAT_AIDY_CODE = RRRAREQ_AIDY_CODE and RRRAREQ_TREQ_CODE = 'ADVSXF'
left join RORHOLD on RORSTAT_PIDM = RORHOLD_PIDM and RORHOLD_HOLD_CODE = 'DP'
left join RORMESG on RORSTAT_PIDM = RORMESG_PIDM and RORSTAT_AIDY_CODE = RORMESG_AIDY_CODE and RORMESG_MESG_CODE = 'XDGF'
where (RRRAREQ_TRST_CODE in ('C','W') and RORSTAT_AIDY_CODE = :Aid_Year and RORHOLD_PERIOD = :FAL_TERM and (RORHOLD_TO_DATE > sysdate or RORHOLD_TO_DATE is null)))
UNION
(Select RORSTAT_PGRP_CODE,RRRAREQ_TREQ_CODE, RRRAREQ_TRST_CODE STATUS, RORHOLD_PERIOD HOLD_TERM,RORHOLD_TO_DATE EXP_DATE, RORMESG_MESG_CODE,'ADD FALL ROAMESG' AS ACTION
from RORSTAT
left join SPRIDEN on RORSTAT_PIDM = SPRIDEN_PIDM and SPRIDEN_CHANGE_IND is null
left join RRRAREQ on RORSTAT_PIDM = RRRAREQ_PIDM and RORSTAT_AIDY_CODE = RRRAREQ_AIDY_CODE and RRRAREQ_TREQ_CODE = 'ADVSXF'
left join RORHOLD on RORSTAT_PIDM = RORHOLD_PIDM and RORHOLD_HOLD_CODE = 'DP' and RORHOLD_PERIOD = :FAL_TERM
left join RORMESG on RORSTAT_PIDM = RORMESG_PIDM and RORSTAT_AIDY_CODE = RORMESG_AIDY_CODE and RORMESG_MESG_CODE = 'XDGF'
where RRRAREQ_TRST_CODE in ('C','W') and RORSTAT_AIDY_CODE = :Aid_Year and RORMESG_MESG_CODE is null)
UNION
(Select RORSTAT_PGRP_CODE,RRRAREQ_TREQ_CODE, RRRAREQ_TRST_CODE STATUS,RORHOLD_PERIOD HOLD_TERM, RORHOLD_TO_DATE EXP_DATE, RORMESG_MESG_CODE,'CLEAR SMR REQUIREMENT' AS ACTION
from RORSTAT
left join SPRIDEN on RORSTAT_PIDM = SPRIDEN_PIDM and SPRIDEN_CHANGE_IND is null
left join RRRAREQ on RORSTAT_PIDM = RRRAREQ_PIDM and RORSTAT_AIDY_CODE = RRRAREQ_AIDY_CODE and RRRAREQ_TREQ_CODE = 'ADVSXM'
left join RORHOLD on RORSTAT_PIDM = RORHOLD_PIDM and RORHOLD_HOLD_CODE = 'DP'
left join RORMESG on RORSTAT_PIDM = RORMESG_PIDM and RORSTAT_AIDY_CODE = RORMESG_AIDY_CODE and RORMESG_MESG_CODE = 'XDGM'
where (RRRAREQ_TRST_CODE = 'R' and RORSTAT_AIDY_CODE = :Aid_Year and RORHOLD_PERIOD = :SMR_TERM and RORHOLD_TO_DATE <= sysdate))
UNION
(Select RORSTAT_PGRP_CODE,RRRAREQ_TREQ_CODE, RRRAREQ_TRST_CODE STATUS, RORHOLD_PERIOD HOLD_TERM, RORHOLD_TO_DATE EXP_DATE, RORMESG_MESG_CODE,'EXP SMR HOLD' AS ACTION
from RORSTAT
left join SPRIDEN on RORSTAT_PIDM = SPRIDEN_PIDM and SPRIDEN_CHANGE_IND is null
left join RRRAREQ on RORSTAT_PIDM = RRRAREQ_PIDM and RORSTAT_AIDY_CODE = RRRAREQ_AIDY_CODE and RRRAREQ_TREQ_CODE = 'ADVSXM'
left join RORHOLD on RORSTAT_PIDM = RORHOLD_PIDM and RORHOLD_HOLD_CODE = 'DP'
left join RORMESG on RORSTAT_PIDM = RORMESG_PIDM and RORSTAT_AIDY_CODE = RORMESG_AIDY_CODE and RORMESG_MESG_CODE = 'XDGM'
where (RRRAREQ_TRST_CODE in ('C','W') and RORSTAT_AIDY_CODE = :Aid_Year and RORHOLD_PERIOD = :SMR_TERM and (RORHOLD_TO_DATE > sysdate or RORHOLD_TO_DATE is null)))
UNION
(Select RORSTAT_PGRP_CODE,RRRAREQ_TREQ_CODE, RRRAREQ_TRST_CODE STATUS, RORHOLD_PERIOD HOLD_TERM, RORHOLD_TO_DATE EXP_DATE, RORMESG_MESG_CODE,'ADD SMR ROAMESG' AS ACTION
from RORSTAT
left join SPRIDEN on RORSTAT_PIDM = SPRIDEN_PIDM and SPRIDEN_CHANGE_IND is null
left join RRRAREQ on RORSTAT_PIDM = RRRAREQ_PIDM and RORSTAT_AIDY_CODE = RRRAREQ_AIDY_CODE and RRRAREQ_TREQ_CODE = 'ADVSXM'
left join RORHOLD on RORSTAT_PIDM = RORHOLD_PIDM and RORHOLD_HOLD_CODE = 'DP' and RORHOLD_PERIOD = :SMR_TERM
left join RORMESG on RORSTAT_PIDM = RORMESG_PIDM and RORSTAT_AIDY_CODE = RORMESG_AIDY_CODE and RORMESG_MESG_CODE = 'XDGM'
where (RRRAREQ_TRST_CODE in ('C','W') and RORSTAT_AIDY_CODE = :Aid_Year and RORMESG_MESG_CODE is null))
ORDER BY ACTION, RORSTAT_PGRP_CODE