-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Schema fields used internally for joins/comparisons are retained where required by the query logic.
-- Do not commit query results or exports containing student records.

SELECT M.SERDTSR_SSER_CODE SMR_CH33, M.STVSSER_DESC SMR_CH33_DESC, M.SERDTSR_SEPR_CODE SMR_SERVICE, M.STVSEPR_DESC SMR_SERVICE_DESC,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :SMR AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('SIOFB6','SIOFB8','GFOZAB','SIOFB1','SIOFB2','SIOF16','SIOF14','SIOF12','SIOFN6','SIOFN4','SIOFN2','SIO6FG','SIO4FG','SIO2FG','SIOF18','SIO8FG','SIOFN8','SIOF1G','SIOF11','SIOFXN','SIOF81','SIOF71','SIOF61','SIOF51','SIOF41','SIOF31','SIOF21','SIOFT6','SIOFT2','SIOFT4','SIOFT8','SIOXN8','SIOXN6','SIOXN4','SIOXN2','SIOFTE')) SMR_FGF_OFRD,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :SMR AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('GSNOCG','GSNOCR','GSNO2E')) SMR_OCOG_OFRD,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :SMR AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('SSOWOS','SSOWOE')) SMR_OWOS_OFRD,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :SMR AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('SSOGSA','SSOGSE')) SMR_NAT_GRD_OFRD,
F.SERDTSR_SSER_CODE FALL_CH33, F.STVSSER_DESC FALL_CH33_DESC, F.SERDTSR_SEPR_CODE FALL_SERVICE, F.STVSEPR_DESC FALL_SERVICE_DESC,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :FALL AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('SIOFB6','SIOFB8','GFOZAB','SIOFB1','SIOFB2','SIOF16','SIOF14','SIOF12','SIOFN6','SIOFN4','SIOFN2','SIO6FG','SIO4FG','SIO2FG','SIOF18','SIO8FG','SIOFN8','SIOF1G','SIOF11','SIOFXN','SIOF81','SIOF71','SIOF61','SIOF51','SIOF41','SIOF31','SIOF21','SIOFT6','SIOFT2','SIOFT4','SIOFT8','SIOXN8','SIOXN6','SIOXN4','SIOXN2','SIOFTE')) FALL_FGF_OFRD,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :FALL AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('GSNOCG','GSNOCR','GSNO2E')) FALL_OCOG_OFRD,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :FALL AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('SSOWOS','SSOWOE')) FALL_OWOS_OFRD,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :FALL AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('SSOGSA','SSOGSE')) FALL_NAT_GRD_OFRD,
S.SERDTSR_SSER_CODE SPR_CH33, S.STVSSER_DESC SPR_CH33_DESC, S.SERDTSR_SEPR_CODE SPR_SERVICE, S.STVSEPR_DESC SPR_SERVICE_DESC,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :SPR AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('SIOFB6','SIOFB8','GFOZAB','SIOFB1','SIOFB2','SIOF16','SIOF14','SIOF12','SIOFN6','SIOFN4','SIOFN2','SIO6FG','SIO4FG','SIO2FG','SIOF18','SIO8FG','SIOFN8','SIOF1G','SIOF11','SIOFXN','SIOF81','SIOF71','SIOF61','SIOF51','SIOF41','SIOF31','SIOF21','SIOFT6','SIOFT2','SIOFT4','SIOFT8','SIOXN8','SIOXN6','SIOXN4','SIOXN2','SIOFTE')) SPR_FGF_OFRD,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :SPR AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('GSNOCG','GSNOCR','GSNO2E')) SPR_OCOG_OFRD,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :SPR AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('SSOWOS','SSOWOE')) SPR_OWOS_OFRD,
(SELECT DISTINCT 'Y' FROM RPRATRM WHERE RPRATRM_PIDM = SPRIDEN_PIDM AND RPRATRM_PERIOD = :SPR AND RPRATRM_OFFER_AMT > 0 AND RPRATRM_FUND_CODE IN ('SSOGSA','SSOGSE')) SPR_NAT_GRD_OFRD
FROM SPRIDEN
LEFT JOIN SERDTSR M ON M.SERDTSR_PIDM = SPRIDEN_PIDM AND M.SERDTSR_TERM_CODE_EFF = :SMR AND M.SERDTSR_SSER_CODE IN ('VTR1','VTR6') AND M.SERDTSR_SEPR_CODE is not null
LEFT JOIN STVSSER M ON M.STVSSER_CODE = M.SERDTSR_SSER_CODE
LEFT JOIN STVSEPR M ON M.STVSEPR_CODE = M.SERDTSR_SEPR_CODE
LEFT JOIN SERDTSR F ON F.SERDTSR_PIDM = SPRIDEN_PIDM AND F.SERDTSR_TERM_CODE_EFF = :FALL AND F.SERDTSR_SSER_CODE IN ('VTR1','VTR6') AND F.SERDTSR_SEPR_CODE is not null
LEFT JOIN STVSSER F ON F.STVSSER_CODE = F.SERDTSR_SSER_CODE
LEFT JOIN STVSEPR F ON F.STVSEPR_CODE = F.SERDTSR_SEPR_CODE
LEFT JOIN SERDTSR S ON S.SERDTSR_PIDM = SPRIDEN_PIDM AND S.SERDTSR_TERM_CODE_EFF = :SPR AND S.SERDTSR_SSER_CODE IN ('VTR1','VTR6') AND S.SERDTSR_SEPR_CODE is not null
LEFT JOIN STVSSER S ON S.STVSSER_CODE = S.SERDTSR_SSER_CODE
LEFT JOIN STVSEPR S ON S.STVSEPR_CODE = S.SERDTSR_SEPR_CODE
WHERE SPRIDEN_CHANGE_IND IS NULL
AND (M.SERDTSR_SSER_CODE IS NOT NULL OR F.SERDTSR_SSER_CODE IS NOT NULL OR S.SERDTSR_SSER_CODE IS NOT NULL)