-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Schema fields used internally for joins/comparisons are retained where required by the query logic.
-- Do not commit query results or exports containing student records.

SELECT FLOOR(MONTHS_BETWEEN(sysdate, SPBPERS_BIRTH_DATE)/12) AGE,
RORSTAT_TGRP_CODE TGRP,
RRRAREQ_TREQ_CODE VERIF, RRRAREQ_EST_DATE VERIF_EST_DATE,
(SELECT SGBSTDN_STST_CODE FROM SGBSTDN WHERE SGBSTDN_PIDM = SPBPERS_PIDM AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z WHERE Z.SGBSTDN_PIDM = SPBPERS_PIDM AND Z.SGBSTDN_TERM_CODE_EFF <= :TERM)) SGASTDN_STATUS
FROM SPBPERS
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM = SPBPERS_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN RORSTAT ON RORSTAT_PIDM = SPBPERS_PIDM AND RORSTAT_AIDY_CODE = :AIDY
LEFT JOIN RRRAREQ ON RRRAREQ_PIDM = SPBPERS_PIDM AND RRRAREQ_AIDY_CODE = :AIDY AND RRRAREQ_TREQ_CODE = 'VERIF'
WHERE SPBPERS_SSN IN (:SSN_1, :SSN_2, :SSN_3, :SSN_4)
ORDER BY SGASTDN_STATUS, TGRP