-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Schema fields used internally for joins/comparisons are retained where required by the query logic.
-- Do not commit query results or exports containing student records.

-- calculated SAP status 202360 C% or AD%
-- have FGF award (any status)
-- have fall SAP status not C% or AD%
SELECT * FROM (
SELECT A.RORSAPR_SAPR_CODE_CALC SMR_SAP_CALCULATED, B.RORSAPR_SAPR_CODE FAL_SAP, C.RORSAPR_SAPR_CODE SPR_SAP,
(SELECT DISTINCT 'X' FROM RPRAWRD WHERE RPRAWRD_PIDM = A.RORSAPR_PIDM AND RPRAWRD_AIDY_CODE = :AIDY AND RPRAWRD_FUND_CODE IN ('SIOF12','SIOF14','SIOF16','SIO8FG','SIO4FG','SIO6FG','SIO2FG')) FGF_AWARD
FROM RORSAPR A
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM = A.RORSAPR_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN RORSAPR B ON B.RORSAPR_PIDM = A.RORSAPR_PIDM
LEFT JOIN RORSAPR C ON C.RORSAPR_PIDM = A.RORSAPR_PIDM
WHERE A.RORSAPR_TERM_CODE = '202360'
AND (A.RORSAPR_SAPR_CODE_CALC LIKE 'C%' OR A.RORSAPR_SAPR_CODE_CALC LIKE 'AD%')
AND B.RORSAPR_TERM_CODE = '202380'
OR C.RORSAPR_TERM_CODE = '202410'
AND ((B.RORSAPR_SAPR_CODE NOT LIKE 'C%' OR B.RORSAPR_SAPR_CODE NOT LIKE 'AD%') OR (C.RORSAPR_SAPR_CODE NOT LIKE 'C%' OR C.RORSAPR_SAPR_CODE NOT LIKE 'AD%')))
WHERE FGF_AWARD = 'X'