-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Schema fields used internally for joins/comparisons are retained where required by the query logic.
-- Do not commit query results or exports containing student records.

SELECT CASE WHEN RORSTAT_APPL_RCVD_DATE IS NOT NULL THEN 'Y' ELSE 'N' END FAFSA,
M.RORSAPR_TERM_CODE SMR, M.RORSAPR_SAPR_CODE SMR_SAP, TRUNC(M.RORSAPR_ACTIVITY_DATE) SMR_SAP_DATE, RORMESG_MESG_CODE, RORMESG_EXPIRATION_DATE,
F.RORSAPR_TERM_CODE FALL, F.RORSAPR_SAPR_CODE FALL_SAP, TRUNC(F.RORSAPR_ACTIVITY_DATE) FALL_SAP_DATE,
(SELECT GURMAIL_LETR_CODE FROM GURMAIL WHERE GURMAIL_PIDM = M.RORSAPR_PIDM AND GURMAIL_LETR_CODE = 'FA_SAP_CITE_GR' AND GURMAIL_DATE_PRINTED = (SELECT MAX(Z.GURMAIL_DATE_PRINTED) FROM GURMAIL Z WHERE Z.GURMAIL_PIDM = M.RORSAPR_PIDM AND Z.GURMAIL_LETR_CODE = 'FA_SAP_CITE_GR' AND Z.GURMAIL_DATE_PRINTED >= '16-MAY-2024')) EMAIL,
(SELECT GURMAIL_DATE_PRINTED FROM GURMAIL WHERE GURMAIL_PIDM = M.RORSAPR_PIDM AND GURMAIL_LETR_CODE = 'FA_SAP_CITE_GR' AND GURMAIL_DATE_PRINTED = (SELECT MAX(Z.GURMAIL_DATE_PRINTED) FROM GURMAIL Z WHERE Z.GURMAIL_PIDM = M.RORSAPR_PIDM AND Z.GURMAIL_LETR_CODE = 'FA_SAP_CITE_GR' AND Z.GURMAIL_DATE_PRINTED >= '16-MAY-2024')) EMAIL_DATE,
RRRAREQ_TREQ_CODE, RRRAREQ_SAT_IND, RRRAREQ_STAT_DATE
FROM RORSAPR M
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM = M.RORSAPR_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN RORSTAT ON RORSTAT_PIDM = M.RORSAPR_PIDM AND RORSTAT_AIDY_CODE = '2425'
LEFT JOIN RORMESG ON RORMESG_PIDM = M.RORSAPR_PIDM AND RORMESG_AIDY_CODE = '2425' AND RORMESG_MESG_CODE = 'ARMG' AND TRUNC(RORMESG_EXPIRATION_DATE) > SYSDATE
LEFT JOIN RORSAPR F ON F.RORSAPR_PIDM = M.RORSAPR_PIDM AND F.RORSAPR_TERM_CODE = '202480' AND (F.RORSAPR_SAPR_CODE LIKE 'AA%' OR F.RORSAPR_SAPR_CODE LIKE 'AM%' OR F.RORSAPR_SAPR_CODE LIKE 'AS%')
LEFT JOIN RRRAREQ ON RRRAREQ_PIDM = M.RORSAPR_PIDM AND RRRAREQ_AIDY_CODE = '2425' AND RRRAREQ_TREQ_CODE = 'FAFSA'
WHERE M.RORSAPR_TERM_CODE = '202460'
AND M.RORSAPR_SAPR_CODE IN ('CPG', 'CGG', 'CGPG')
AND RORSTAT_APPL_RCVD_DATE IS NOT NULL
AND RORMESG_MESG_CODE IS NULL