-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Schema fields used internally for joins/comparisons are retained where required by the query logic.
-- Do not commit query results or exports containing student records.

SELECT * FROM (
SELECT DISTINCT RORSAPR_TERM_CODE, RORSAPR_SAPR_CODE, RORMESG_AIDY_CODE, RORMESG_MESG_CODE, RRRAREQ_TREQ_CODE, RRRAREQ_TRST_CODE, RRRAREQ_EST_DATE, RRRAREQ_AIDY_CODE
FROM RORSAPR
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM = RORSAPR_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN RORMESG ON RORMESG_PIDM = RORSAPR_PIDM AND RORMESG_AIDY_CODE = '2425' AND RORMESG_MESG_CODE = 'ARMG'
LEFT JOIN RORSTAT ON RORSTAT_PIDM = RORSAPR_PIDM AND RORSTAT_AIDY_CODE = '2425' AND RORSTAT_APPL_RCVD_DATE IS NOT NULL
LEFT JOIN RRRAREQ ON RRRAREQ_PIDM = RORSAPR_PIDM AND RRRAREQ_TREQ_CODE = 'FAFSA' AND RRRAREQ_TRST_CODE = 'S' AND RRRAREQ_EST_DATE > '01 January 2024'
WHERE RORSAPR_TERM_CODE = '202460' AND RORSAPR_SAPR_CODE IN ('CPG', 'CGG', 'CGPG'))
WHERE RORMESG_MESG_CODE IS NULL
AND RRRAREQ_TREQ_CODE = 'FAFSA'
AND RRRAREQ_EST_DATE > '01 January 2024'
AND RRRAREQ_AIDY_CODE = '2425'