-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Schema fields used internally for joins/comparisons are retained where required by the query logic.
-- Do not commit query results or exports containing student records.

SELECT * FROM (
SELECT F.RORSAPR_SAPR_CODE SMR_SAP, Z.RORSAPR_SAPR_CODE FAL_SAP, Y.RORSAPR_SAPR_CODE SPR_SAP,
(SELECT TRUNC(SHRLGPA_GPA,2) FROM SHRLGPA WHERE SHRLGPA_PIDM = F.RORSAPR_PIDM AND SHRLGPA_LEVL_CODE = 'UG' AND SHRLGPA_GPA_TYPE_IND = 'O') UG_OVERALL_GPA,
(SELECT SHRLGPA_HOURS_ATTEMPTED FROM SHRLGPA WHERE SHRLGPA_PIDM = F.RORSAPR_PIDM AND SHRLGPA_LEVL_CODE = 'UG' AND SHRLGPA_GPA_TYPE_IND = 'I') UG_INST_ATTPT_HRS,
(SELECT TRUNC(SHRLGPA_GPA,2) FROM SHRLGPA WHERE SHRLGPA_PIDM = F.RORSAPR_PIDM AND SHRLGPA_LEVL_CODE = 'GR' AND SHRLGPA_GPA_TYPE_IND = 'O') GR_OVERALL_GPA,
(SELECT SHRLGPA_HOURS_ATTEMPTED FROM SHRLGPA WHERE SHRLGPA_PIDM = F.RORSAPR_PIDM AND SHRLGPA_LEVL_CODE = 'GR' AND SHRLGPA_GPA_TYPE_IND = 'I') GR_INST_ATTPT_HRS,
(SELECT DISTINCT 'X' FROM SHRTCKG WHERE SHRTCKG_PIDM = F.RORSAPR_PIDM AND SHRTCKG_GRDE_CODE_FINAL = 'W') W_GRADE,
(SELECT DISTINCT 'X' FROM SHRTCKG WHERE SHRTCKG_PIDM = F.RORSAPR_PIDM AND SHRTCKG_GRDE_CODE_FINAL IN ('F','NF','IF','XNF','SF','XF','XSF','WF','FC','FF')) FAIL_GRADE,
(SELECT DISTINCT 'X' FROM SHRTCKG WHERE SHRTCKG_PIDM = F.RORSAPR_PIDM AND SHRTCKG_GRDE_CODE_FINAL = 'S') S_GRADE,
CASE WHEN RORSTAT_APPL_RCVD_DATE IS NOT NULL THEN 'Y' ELSE 'N' END FAFSA
FROM RORSAPR F
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM = F.RORSAPR_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN RORSAPR Z ON F.RORSAPR_PIDM = Z.RORSAPR_PIDM AND Z.RORSAPR_TERM_CODE = :FALL
LEFT JOIN RORSAPR Y ON Y.RORSAPR_PIDM = F.RORSAPR_PIDM AND Y.RORSAPR_TERM_CODE = :SPR
LEFT JOIN RORSTAT ON RORSTAT_PIDM = F.RORSAPR_PIDM AND RORSTAT_AIDY_CODE = :AIDY
WHERE F.RORSAPR_TERM_CODE = :SMR AND F.RORSAPR_SAPR_CODE IN ('C2YTF','CGG','CG','CG2Y'))
WHERE ((UG_OVERALL_GPA < .01 AND UG_INST_ATTPT_HRS > 0) OR (GR_OVERALL_GPA < .01 AND GR_INST_ATTPT_HRS > 0)) AND FAFSA = 'Y'