-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

select distinct * from(

SELECT --SGBSTDN_LEVL_CODE STU_LEVEL,

(SELECT SUM(SFRSTCR_BILL_HR)
FROM SFRSTCR
WHERE SFRSTCR_PIDM = SPRIDEN_PIDM
--AND SFRSTCR_RSTS_CODE IN ('RR','RW','R2', 'RE')
AND SFRSTCR_CAMP_CODE = 'KC'
AND SFRSTCR_LEVL_CODE = 'UG'
AND SFRSTCR_TERM_CODE = '202280'
AND NVL(SFRSTCR_BILL_HR,0) > 0) FALL_UG_KC_HRS,

(SELECT SUM(SFRSTCR_BILL_HR)
FROM SFRSTCR
WHERE SFRSTCR_PIDM = SPRIDEN_PIDM
--AND SFRSTCR_RSTS_CODE IN ('RR','RW','R2', 'RE')
AND SFRSTCR_CAMP_CODE <> 'KC'
AND SFRSTCR_LEVL_CODE = 'UG'
AND SFRSTCR_TERM_CODE = '202280'
AND NVL(SFRSTCR_BILL_HR,0) > 0) FALL_UG_RC_HRS,

RCRAPP4_FISAP_INC FISAP_INC,

(SELECT MIN(SGBSTDN_RATE_CODE)
FROM SGBSTDN_AUDIT
WHERE SGBSTDN_PIDM = SPRIDEN_PIDM
AND SGBSTDN_RATE_CODE LIKE '2%') COHORT

FROM SPRIDEN

LEFT JOIN RCRAPP1
ON RCRAPP1_PIDM = SPRIDEN_PIDM
AND RCRAPP1_AIDY_CODE = '2223'
AND RCRAPP1_INFC_CODE = 'EDE'
AND RCRAPP1_CURR_REC_IND = 'Y'

LEFT JOIN RCRAPP4
ON SPRIDEN_PIDM = RCRAPP4_PIDM
AND RCRAPP1_AIDY_CODE = RCRAPP4_AIDY_CODE
AND RCRAPP1_INFC_CODE = 'EDE'
AND RCRAPP1_SEQ_NO = RCRAPP4_SEQ_NO

--LEFT JOIN SGBSTDN_AUDIT
--ON SGBSTDN_PIDM = SPRIDEN_PIDM

WHERE SPRIDEN_CHANGE_IND IS NULL

)

WHERE NVL(FALL_UG_RC_HRS,0) = 0
AND  (NVL(FALL_UG_KC_HRS,0) > 0 AND FALL_UG_KC_HRS < 12)
--AND COHORT >= '2019'
--AND COHORT LIKE '2%'
--AND STU_LEVEL = 'UG'
--AND FISAP_INC <= 75000 --and FISAP_INC <= 100000)