-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT RPRAWRD_AIDY_CODE AIDY, RPRAWRD_FUND_CODE FUND, RFRBASE_FUND_TITLE FUND_TITLE, 

RPRAWRD_OFFER_AMT OFFERED, RPRAWRD_ACCEPT_AMT ACCEPTED, RPRAWRD_PAID_AMT PAID, 

SGBSTDN_MAJR_CODE_1 MAJOR_CODE, STVMAJR_DESC MAJOR

FROM RPRAWRD

LEFT JOIN SPRIDEN
ON SPRIDEN_PIDM = RPRAWRD_PIDM
AND SPRIDEN_CHANGE_IND IS NULL

LEFT JOIN RFRBASE
ON RFRBASE_FUND_CODE = RPRAWRD_FUND_CODE

LEFT JOIN SGBSTDN
ON SGBSTDN_PIDM = RPRAWRD_PIDM

LEFT JOIN STVMAJR
ON STVMAJR_CODE = SGBSTDN_MAJR_CODE_1

WHERE RPRAWRD_AIDY_CODE = :AIDY
AND RPRAWRD_OFFER_AMT > 0
AND RPRAWRD_FUND_CODE = 'SPBS04'
AND SGBSTDN_TERM_CODE_EFF = 
    (SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Z
    WHERE Z.SGBSTDN_PIDM = RPRAWRD_PIDM
    AND Z.SGBSTDN_TERM_CODE_EFF <= :SPR)
AND SGBSTDN_STST_CODE = 'AS'