-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT RPRAWRD_FUND_CODE FUND,

(SELECT DISTINCT 'Y'
FROM RPRAWRD
WHERE RPRAWRD_PIDM = SPRIDEN_PIDM
AND RPRAWRD_FUND_CODE = 'SPMZCC'
AND RPRAWRD_AIDY_CODE = '2223'
AND RPRAWRD_OFFER_AMT > 0) OFFERED_2223,

(SELECT DISTINCT 'Y'
FROM RPRAWRD
WHERE RPRAWRD_PIDM = SPRIDEN_PIDM
AND RPRAWRD_FUND_CODE = 'SPMZCC'
AND RPRAWRD_AIDY_CODE = '2324'
AND RPRAWRD_OFFER_AMT > 0) OFFERED_2324,

(SELECT DISTINCT 'Y'
FROM RPRAWRD
WHERE RPRAWRD_PIDM = SPRIDEN_PIDM
AND RPRAWRD_FUND_CODE = 'SPMZCC'
AND RPRAWRD_AIDY_CODE = '2425'
AND RPRAWRD_OFFER_AMT > 0) OFFERED_2425,

(SELECT DISTINCT 'Y'
FROM RPRAWRD
WHERE RPRAWRD_PIDM = SPRIDEN_PIDM
AND RPRAWRD_FUND_CODE = 'SPMZCC'
AND RPRAWRD_AIDY_CODE = '2526'
AND RPRAWRD_OFFER_AMT > 0) OFFERED_2526,

(SELECT DISTINCT 'Y'
FROM RPRAWRD
WHERE RPRAWRD_PIDM = SPRIDEN_PIDM
AND RPRAWRD_FUND_CODE = 'SPMZCC'
AND RPRAWRD_AIDY_CODE = '2627'
AND RPRAWRD_OFFER_AMT > 0) OFFERED_2627

FROM SPRIDEN, RPRAWRD

WHERE RPRAWRD_FUND_CODE = 'SPMZCC'
AND RPRAWRD_AIDY_CODE >= '2223'
AND RPRAWRD_AIDY_CODE LIKE '2%'
AND RPRAWRD_OFFER_AMT > 0
AND SPRIDEN_PIDM = RPRAWRD_PIDM
AND SPRIDEN_CHANGE_IND IS NULL