-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT BASE.*, CASE WHEN (NVL(TOTAL_OFFER_AMOUNT,0) + NVL(RESOURCES,0)) > TOTAL_BUDGET_COA THEN 'Y' END OVER_COST,
CASE WHEN NVL(NEED_BASED_AID_OFFERED,0) > 0 AND FM_UNMET_NEED < 0 THEN 'Y' END OVER_NEED
FROM (
SELECT RORSTAT_APRD_CODE, SGAS.STATUS, SGAS.LEVL, SGAS.RATE, SGAS.RES, SGAS.PROG, SGAS.CAMP,
(SELECT DISTINCT 'Y' FROM SFRSTCR, SSBSECT WHERE SFRSTCR_PIDM = RORSTAT_PIDM AND SFRSTCR_CRN = SSBSECT_CRN AND SFRSTCR_TERM_CODE = SSBSECT_TERM_CODE AND SSBSECT_INSM_CODE = 'TR' AND SFRSTCR_TERM_CODE = RBRAPBG_PERIOD) TR_COURSE,
AUDITS.RATE AUDIT_RATE, RBRAPBG_PERIOD, RBRAPBG_PBGP_CODE, RBRAPBG_PBGP_CODE_LOCK_IND,
(SELECT SUM(SFRSTCR_BILL_HR) FROM SFRSTCR WHERE SFRSTCR_PIDM = RORSTAT_PIDM AND SFRSTCR_TERM_CODE = RBRAPBG_PERIOD AND SFRSTCR_BILL_HR > 0) BILLED,
CASE WHEN B.RBRAPBC_AMT = 400 THEN 'FT' WHEN B.RBRAPBC_AMT = 300 THEN 'LF' WHEN B.RBRAPBC_AMT = 200 THEN 'LH' END BUDGET_TMST,
X.RBRAPBC_PBCP_CODE "T+F", X.RBRAPBC_SEQ_NO "T+F SEQ", X.RBRAPBC_AMT "T+F AMT", X.RBRAPBC_ACTIVITY_DATE "T+F UPDATE", X.RBRAPBC_SYS_IND "T+F SYS IND",
S.RBRAPBC_PBCP_CODE "SURC", S.RBRAPBC_SEQ_NO "SURC SEQ", S.RBRAPBC_AMT "SURC AMT", S.RBRAPBC_ACTIVITY_DATE "SURC UPDATE", S.RBRAPBC_SYS_IND "SURC SYS IND",
(SELECT DISTINCT 'Y' FROM RPRAWRD WHERE RPRAWRD_PIDM = RORSTAT_PIDM AND RPRAWRD_AIDY_CODE = '2526' AND RPRAWRD_FUND_CODE LIKE 'GIAM%' AND RPRAWRD_OFFER_AMT > 0) ATHLETE,
NVL((SELECT SUM(RPRAWRD_OFFER_AMT) FROM RPRAWRD WHERE RPRAWRD_PIDM = RORSTAT_PIDM AND RPRAWRD_AIDY_CODE = RORSTAT_AIDY_CODE AND RPRAWRD_OFFER_AMT > 0),0) TOTAL_OFFER_AMOUNT,
RNVAND0_RESOURCE_AMOUNT RESOURCES, RNVAND0_FM_BUDGET_AMT TOTAL_BUDGET_COA,
(SELECT SUM(RPRAWRD_OFFER_AMT) FROM RPRAWRD WHERE RPRAWRD_PIDM = RORSTAT_PIDM AND RPRAWRD_AIDY_CODE = RORSTAT_AIDY_CODE AND (RPRAWRD_FUND_CODE LIKE '_SN%' OR RPRAWRD_FUND_CODE LIKE '_FN%' OR RPRAWRD_FUND_CODE LIKE '_FB%' OR RPRAWRD_FUND_CODE LIKE '_SB%' OR RPRAWRD_FUND_CODE IN ('JENGLE','JENGLI')) AND RPRAWRD_OFFER_AMT > 0) NEED_BASED_AID_OFFERED,
RNVAND0_UNMET_NEED FM_UNMET_NEED
FROM RORSTAT
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM = RORSTAT_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN (SELECT SGBSTDN_PIDM PIDM, SGBSTDN_TERM_CODE_EFF TERM, SGBSTDN_STST_CODE STATUS, SGBSTDN_LEVL_CODE LEVL, SGBSTDN_RATE_CODE RATE, SGBSTDN_RESD_CODE RES, SGBSTDN_PROGRAM_1 PROG, SGBSTDN_CAMP_CODE CAMP FROM SPRIDEN, SGBSTDN WHERE SPRIDEN_CHANGE_IND IS NULL AND SPRIDEN_PIDM = SGBSTDN_PIDM AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z WHERE Z.SGBSTDN_PIDM = SPRIDEN_PIDM AND Z.SGBSTDN_TERM_CODE_EFF <= '202580')) SGAS ON SGAS.PIDM = RORSTAT_PIDM
LEFT JOIN (SELECT SGBSTDN_PIDM PIDM, SGBSTDN_TERM_CODE_EFF TERM, SGBSTDN_STST_CODE STATUS, SGBSTDN_RATE_CODE RATE FROM SPRIDEN, SGBSTDN_AUDIT WHERE SPRIDEN_CHANGE_IND IS NULL AND SPRIDEN_PIDM = SGBSTDN_PIDM AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN_AUDIT Z WHERE Z.SGBSTDN_PIDM = SPRIDEN_PIDM AND Z.SGBSTDN_TERM_CODE_EFF <= '202580')) AUDITS ON AUDITS.PIDM = RORSTAT_PIDM
LEFT JOIN RNVAND0 ON RNVAND0_PIDM = RORSTAT_PIDM AND RNVAND0_AIDY_CODE = RORSTAT_AIDY_CODE
LEFT JOIN RBRAPBG ON RBRAPBG_PIDM = RORSTAT_PIDM AND RBRAPBG_AIDY_CODE = RORSTAT_AIDY_CODE AND RBRAPBG_RUN_NAME = 'ACTUAL'
LEFT JOIN RBRAPBC B ON B.RBRAPBC_PIDM = RORSTAT_PIDM AND B.RBRAPBC_AIDY_CODE = RORSTAT_AIDY_CODE AND B.RBRAPBC_RUN_NAME = 'ACTUAL' AND B.RBRAPBC_PBTP_CODE = 'COA' AND B.RBRAPBC_PERIOD = RBRAPBG_PERIOD AND B.RBRAPBC_PBCP_CODE = 'B+S'
LEFT JOIN RBRAPBC X ON X.RBRAPBC_PIDM = RORSTAT_PIDM AND X.RBRAPBC_AIDY_CODE = RORSTAT_AIDY_CODE AND X.RBRAPBC_RUN_NAME = 'ACTUAL' AND X.RBRAPBC_PBTP_CODE = 'COA' AND X.RBRAPBC_PERIOD = RBRAPBG_PERIOD AND X.RBRAPBC_PBCP_CODE = 'T+F'
LEFT JOIN RBRAPBC S ON S.RBRAPBC_PIDM = RORSTAT_PIDM AND S.RBRAPBC_AIDY_CODE = RORSTAT_AIDY_CODE AND S.RBRAPBC_RUN_NAME = 'ACTUAL' AND S.RBRAPBC_PBTP_CODE = 'COA' AND S.RBRAPBC_PERIOD = RBRAPBG_PERIOD AND S.RBRAPBC_PBCP_CODE = 'SURC'
WHERE RORSTAT_AIDY_CODE = '2526' AND ((SGAS.RATE = 'SPRC' OR AUDITS.RATE = 'SPRC') OR (SGAS.CAMP LIKE '__V' AND SGAS.RES <> 'R') OR SGAS.PROG IN ('NU-BSN-NURN','AS-MFA-CRWG'))) BASE
WHERE RES <> 'R' AND CAMP LIKE '__V' AND TR_COURSE = 'Y'
ORDER BY RBRAPBG_PERIOD, RBRAPBG_PBGP_CODE