-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT * FROM (
SELECT SORHSCH_SBGI_CODE CEEB_CODE, SOVSBGV_DESC HIGH_SCHOOL, SOVSBGV_CITY HS_CITY, SOVSBGV_STAT_CODE HS_STATE,
(SELECT SUM(SFRSTCR_CREDIT_HR) FROM SFRSTCR WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE = '202380' AND SFRSTCR_RSTS_CODE IN ('RR','RE','RW','R2')) ENROLLED,
(SELECT 'Y' FROM SGBSTDN WHERE SGBSTDN_PIDM = SPRIDEN_PIDM AND SGBSTDN_STST_CODE = 'AS' AND SGBSTDN_LEVL_CODE = 'UG' AND SGBSTDN_STYP_CODE = 'F' AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z WHERE Z.SGBSTDN_PIDM = SPRIDEN_PIDM AND Z.SGBSTDN_TERM_CODE_EFF in ('202360','202380','202410'))) NEW_FRESHMAN,
RCRAPP2_PELL_PGI PELL_EFC, RCRESAR_PELL_ELGBL PELL_ELIGIBLE_FLAG
FROM SPRIDEN
LEFT JOIN SORHSCH ON SORHSCH_PIDM = SPRIDEN_PIDM
LEFT JOIN SOVSBGV ON SOVSBGV_CODE = SORHSCH_SBGI_CODE
LEFT JOIN RCRAPP1 ON RCRAPP1_PIDM = SPRIDEN_PIDM AND RCRAPP1_AIDY_CODE = '2324' AND RCRAPP1_INFC_CODE = 'EDE' AND RCRAPP1_CURR_REC_IND = 'Y'
LEFT JOIN RCRAPP2 ON RCRAPP2_PIDM = RCRAPP1_PIDM AND RCRAPP2_AIDY_CODE = RCRAPP1_AIDY_CODE AND RCRAPP2_INFC_CODE = RCRAPP1_INFC_CODE AND RCRAPP2_SEQ_NO = RCRAPP1_SEQ_NO
LEFT JOIN RCRESAR ON RCRESAR_PIDM = RCRAPP1_PIDM AND RCRESAR_AIDY_CODE = RCRAPP1_AIDY_CODE AND RCRESAR_INFC_CODE = RCRAPP1_INFC_CODE AND RCRESAR_SEQ_NO = RCRAPP1_SEQ_NO
WHERE SPRIDEN_CHANGE_IND IS NULL
AND SORHSCH_SBGI_CODE IN ('361425', '360102', '365166','360055', '360035','360040', '360043', '365284','360070')
AND SORHSCH_GRADUATION_DATE IS NOT NULL
AND RCRESAR_PELL_ELGBL = 'Y')
WHERE NVL(ENROLLED,0) > 0
ORDER BY NEW_FRESHMAN NULLS LAST, HIGH_SCHOOL