-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT PREDOM_CAMPUS, MAJR_1_CIPC, MAJOR_1_CODE, MAJOR_1, STU_CLASS, COUNT(DISTINCT SPRIDEN_ID) STUDENT_COUNT, ROUND(AVG(GPA),2) AVG_GPA, ROUND(AVG(UNMET_NEED),2) AVG_UNMET_NEED, SUM(SCH_CALC) TOTAL_SCH_NEEDED
FROM(
SELECT SPRIDEN_ID, SPRIDEN_FIRST_NAME SPRIDEN_LAST_NAME, STU_LEVEL, PROGRAM_CAMPUS, MAJR_1_CIPC, MAJOR_1_CODE, MAJOR_1, UNMET_NEED, UG_KC_HRS, UG_RC_HRS, UG_STARK_HRS, FAFSA, STU_CLASS, GPA, SCH_CALC,
CASE WHEN NVL(UG_KC_HRS,0) >= NVL(UG_STARK_HRS,0) THEN 'KENT' WHEN (NVL(UG_STARK_HRS,0) > NVL(UG_KC_HRS,0)) AND NVL(UG_STARK_HRS,0) > 0 THEN 'STARK' END PREDOM_CAMPUS
FROM (
SELECT SPRIDEN_ID, SPRIDEN_FIRST_NAME, SPRIDEN_LAST_NAME, SGBSTDN_LEVL_CODE STU_LEVEL, SGBSTDN_CAMP_CODE PROGRAM_CAMPUS, A.STVMAJR_CIPC_CODE MAJR_1_CIPC, SGBSTDN_MAJR_CODE_1 MAJOR_1_CODE, A.STVMAJR_DESC MAJOR_1, RNVAND0_UNMET_NEED UNMET_NEED, RCRAPP4_FISAP_INC,
(SELECT SUM(SFRSTCR_CREDIT_HR) FROM SFRSTCR WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE IN ('202360','202380','202410') AND SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2') AND SFRSTCR_CAMP_CODE = 'KC' AND SFRSTCR_LEVL_CODE = 'UG') UG_KC_HRS,
(SELECT SUM(SFRSTCR_CREDIT_HR) FROM SFRSTCR WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE IN ('202360','202380','202410') AND SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2') AND SFRSTCR_CAMP_CODE <> 'KC' AND SFRSTCR_LEVL_CODE = 'UG') UG_RC_HRS,
(SELECT SUM(SFRSTCR_CREDIT_HR) FROM SFRSTCR WHERE SFRSTCR_PIDM = SPRIDEN_PIDM AND SFRSTCR_TERM_CODE IN ('202360','202380','202410') AND SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2') AND SFRSTCR_CAMP_CODE = 'ST' AND SFRSTCR_LEVL_CODE = 'UG') UG_STARK_HRS,
CASE WHEN RORSTAT_APPL_RCVD_DATE IS NULL THEN 'N' WHEN RORSTAT_APPL_RCVD_DATE IS NOT NULL THEN 'Y' END FAFSA,
CASE WHEN SHRLGPA_HOURS_EARNED > 90 THEN 'SENIOR' WHEN SHRLGPA_HOURS_EARNED > 60 THEN 'JUNIOR' WHEN SHRLGPA_HOURS_EARNED > 30 THEN 'SOPHOMORE' WHEN NVL(SHRLGPA_HOURS_EARNED,0) >= 0 THEN 'FRESHMAN' END STU_CLASS,
SHRLGPA_GPA GPA,
FLOOR(CASE WHEN RNVAND0_UNMET_NEED IS NOT NULL AND NVL(RNVAND0_UNMET_NEED,0) < 15000 AND NVL(RNVAND0_UNMET_NEED,0) > 0 THEN NVL(RNVAND0_UNMET_NEED,0) WHEN RNVAND0_UNMET_NEED IS NOT NULL AND NVL(RNVAND0_UNMET_NEED,0) >= 15000 THEN 15000 WHEN NVL(RNVAND0_UNMET_NEED,0) <= 0 THEN 0 ELSE 0 END) SCH_CALC
FROM SPRIDEN
LEFT JOIN SGBSTDN ON SGBSTDN_PIDM = SPRIDEN_PIDM
LEFT JOIN RORSTAT ON RORSTAT_PIDM = SPRIDEN_PIDM AND RORSTAT_AIDY_CODE = :AIDY
LEFT JOIN RNVAND0 ON RNVAND0_PIDM = SPRIDEN_PIDM AND RNVAND0_AIDY_CODE = :AIDY
LEFT JOIN RCRAPP1 ON RCRAPP1_PIDM = SPRIDEN_PIDM
LEFT JOIN RCRAPP4 ON RCRAPP4_PIDM = SPRIDEN_PIDM AND RCRAPP4_INFC_CODE = RCRAPP1_INFC_CODE AND RCRAPP4_SEQ_NO = RCRAPP1_SEQ_NO AND RCRAPP4_AIDY_CODE = RCRAPP1_AIDY_CODE
LEFT JOIN STVMAJR A ON A.STVMAJR_CODE = SGBSTDN_MAJR_CODE_1
LEFT JOIN SHRLGPA ON SHRLGPA_PIDM = SPRIDEN_PIDM AND SHRLGPA_LEVL_CODE = 'UG' AND SHRLGPA_GPA_TYPE_IND = 'O'
WHERE SPRIDEN_CHANGE_IND IS NULL
AND SGBSTDN_STST_CODE = 'AS' AND SGBSTDN_LEVL_CODE = 'UG'
AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z WHERE Z.SGBSTDN_PIDM = SPRIDEN_PIDM AND Z.SGBSTDN_TERM_CODE_EFF <= :SPR)
AND SGBSTDN_DEGC_CODE_1 LIKE 'B%' AND A.STVMAJR_CIPC_CODE IN ('260101','261201','030101','261501')
AND SGBSTDN_CAMP_CODE IN ('KC','ST')
AND RORSTAT_APPL_RCVD_DATE IS NOT NULL AND RORSTAT_PCKG_REQ_COMP_DATE IS NOT NULL AND RNVAND0_UNMET_NEED IS NOT NULL
AND RCRAPP1_AIDY_CODE = :AIDY AND RCRAPP1_CURR_REC_IND = 'Y' AND RCRAPP1_INFC_CODE = 'EDE'
AND RCRAPP4_FISAP_INC <= 75000)
WHERE NVL(UG_KC_HRS,0) + NVL(UG_RC_HRS,0) + NVL(UG_STARK_HRS,0) > 0)
GROUP BY PREDOM_CAMPUS, MAJR_1_CIPC, MAJOR_1_CODE, MAJOR_1, STU_CLASS
ORDER BY 1,2,3,5