-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT RORSTAT_APRD_CODE, TSAAREV_AMT,
(SELECT SUM(RPRATRM_OFFER_AMT) FROM RPRATRM WHERE RPRATRM_PIDM=BASE.PIDM AND RPRATRM_PERIOD='202660' AND RPRATRM_FUND_CODE IN ('WIWFWE','WIWFWO') AND RPRATRM_OFFER_AMT>0) RPAAWRD_AMOUNT,
RNVAND0_FM_BUDGET_AMT TOTAL_BUDGET,
(SELECT SUM(RPRAWRD_OFFER_AMT) FROM RPRAWRD WHERE RPRAWRD_AIDY_CODE='2627' AND RPRAWRD_PIDM=BASE.PIDM AND RPRAWRD_OFFER_AMT>0 AND RPRAWRD_FUND_CODE NOT IN ('WIWFWE','WIWFWO')) RPAAWRD_MINUS_WAIVER,
(SELECT SUM(TBRACCD_AMOUNT) FROM TBRACCD WHERE TBRACCD_TERM_CODE IN ('202660','202680','202710') AND TBRACCD_PIDM=BASE.PIDM AND (TBRACCD_DETAIL_CODE LIKE 'E%' OR TBRACCD_DETAIL_CODE LIKE 'K%')) YEAR_WAIVER
FROM (SELECT TBRACCD_PIDM PIDM, SUM(TBRACCD_AMOUNT) TSAAREV_AMT FROM TBRACCD WHERE TBRACCD_TERM_CODE='202660' GROUP BY TBRACCD_PIDM) BASE
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM=BASE.PIDM AND SPRIDEN_CHANGE_IND IS NULL
JOIN RORSTAT ON RORSTAT_PIDM=BASE.PIDM AND RORSTAT_AIDY_CODE='2627'
LEFT JOIN RNVAND0 ON RNVAND0_PIDM=BASE.PIDM AND RNVAND0_AIDY_CODE='2627'
JOIN RPRATRM ON RPRATRM_PIDM=BASE.PIDM AND RPRATRM_PERIOD='202660' AND RPRATRM_FUND_CODE='GFNPEL' AND RPRATRM_OFFER_AMT>0