-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT A.RPRAWRD_AIDY_CODE AIDY, A.RPRAWRD_FUND_CODE FUND, RFRBASE_FUND_TITLE FUND_TITLE, A.RPRAWRD_OFFER_AMT WAIVER_OFFER,
(SELECT SUM(Z.RPRAWRD_OFFER_AMT) FROM RPRAWRD Z,RFRBASE WHERE Z.RPRAWRD_PIDM=SPRIDEN_PIDM AND Z.RPRAWRD_AIDY_CODE=A.RPRAWRD_AIDY_CODE AND Z.RPRAWRD_FUND_CODE=RFRBASE_FUND_CODE AND RFRBASE_FTYP_CODE<>'W') OTHER_AID
FROM RPRAWRD A, SPRIDEN, RFRBASE
WHERE SPRIDEN_PIDM=A.RPRAWRD_PIDM
AND SPRIDEN_CHANGE_IND IS NULL
AND A.RPRAWRD_FUND_CODE=RFRBASE_FUND_CODE
AND RFRBASE_FTYP_CODE='W'
AND A.RPRAWRD_OFFER_AMT>0
AND A.RPRAWRD_AIDY_CODE LIKE '2%'
ORDER BY AIDY DESC, FUND