-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT * FROM(
SELECT CREDITS, ROKMISC_RULES.F_CALC_RULE_HRS_NO_ROTSREG ('2627',BASE.PIDM,'202660','FEDAID') FEDAID,
(SELECT DISTINCT 'Y' FROM SFRSCRE WHERE SFRSCRE_TERM_CODE='202660' AND SFRSCRE_CREATE_DATE IS NOT NULL AND SFRSCRE_PIDM=BASE.PIDM) CPOS_RUN,
RPRATRM_OFFER_AMT PELL_OFFER_SMR,
(SELECT SUM(TBRACCD_AMOUNT) FROM TBRACCD WHERE TBRACCD_TERM_CODE IN ('202660','X202680','X202710') AND TBRACCD_PIDM=BASE.PIDM AND ((TBRACCD_DETAIL_CODE LIKE 'E%' OR TBRACCD_DETAIL_CODE LIKE 'K%') AND TBRACCD_DETAIL_CODE NOT LIKE 'ES%')) SMR_WAIVER_TSAAREV,
(SELECT SUM(RPRATRM_OFFER_AMT) FROM RPRATRM WHERE RPRATRM_PIDM=BASE.PIDM AND RPRATRM_FUND_CODE IN ('WIWFWE','WIWFWO') AND RPRATRM_PERIOD='202660' AND RPRATRM_OFFER_AMT>0) SMR_WAIVER_RPAAWRD,
(SELECT SUM(RPRAWRD_OFFER_AMT) FROM RPRAWRD WHERE RPRAWRD_PIDM=BASE.PIDM AND RPRAWRD_FUND_CODE IN ('WIWFWE','WIWFWO') AND RPRAWRD_AIDY_CODE='2627' AND RPRAWRD_OFFER_AMT>0) YR_WAIVER_RPAAWRD,
RNVAND0_FM_BUDGET_AMT, RNVAND0_OFFER_AMT, RNVAND0_FM_BUDGET_AMT-RNVAND0_OFFER_AMT OVERCOST,
(SELECT SUM(RPRAWRD_OFFER_AMT) FROM RPRAWRD WHERE RPRAWRD_AIDY_CODE='2627' AND RPRAWRD_PIDM=BASE.PIDM AND RPRAWRD_OFFER_AMT>0 AND RPRAWRD_FUND_CODE NOT IN ('WIWFWE','WIWFWO')) RPAAWRD_MINUS_WAIVER
FROM (SELECT SFRSTCR_PIDM PIDM, SUM(SFRSTCR_CREDIT_HR) CREDITS FROM SFRSTCR WHERE SFRSTCR_TERM_CODE='202660' AND SFRSTCR_RSTS_CODE IN ('RR','RE','R2','RW') AND SFRSTCR_CREDIT_HR>0 GROUP BY SFRSTCR_PIDM) BASE
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM=BASE.PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN RPRATRM ON RPRATRM_PIDM=BASE.PIDM AND RPRATRM_FUND_CODE='GFNPEL' AND RPRATRM_PERIOD='202660'
LEFT JOIN RNVAND0 ON RNVAND0_PIDM=BASE.PIDM AND RNVAND0_AIDY_CODE='2627'
WHERE RPRATRM_OFFER_AMT>0)
WHERE SMR_WAIVER_TSAAREV>0
AND (NVL(CREDITS,0)>NVL(FEDAID,0) OR NVL(SMR_WAIVER_TSAAREV,0)<>NVL(SMR_WAIVER_RPAAWRD,0))