-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT SGBSTDN_STYP_CODE STYP_CODE, STVSTYP_DESC STYPE_DESC, SGBSTDN_LEVL_CODE STU_LEVEL, STVLEVL_DESC STU_LEVEL_DESC,
SGBSTDN_PROGRAM_1, A.SMRPRLE_PROGRAM_DESC PROGRAM_1_DESC, SGBSTDN_PROGRAM_2, B.SMRPRLE_PROGRAM_DESC PROGRAM_2_DESC,
RORSTAT_APRD_CODE APRD,
M.RBRAPBG_PBGP_CODE SMR_BUDG_GROUP,
F.RBRAPBG_PBGP_CODE FALL_BUDG_GROUP,
S.RBRAPBG_PBGP_CODE SPR_BUDG_GROUP
FROM RORSTAT
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM = RORSTAT_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN SGBSTDN ON SGBSTDN_PIDM = RORSTAT_PIDM
LEFT JOIN STVLEVL ON STVLEVL_CODE = SGBSTDN_LEVL_CODE
LEFT JOIN STVSTYP ON STVSTYP_CODE = SGBSTDN_STYP_CODE
LEFT JOIN SMRPRLE A ON A.SMRPRLE_PROGRAM = SGBSTDN_PROGRAM_1
LEFT JOIN SMRPRLE B ON B.SMRPRLE_PROGRAM = SGBSTDN_PROGRAM_2
LEFT JOIN RBRAPBG M ON M.RBRAPBG_PIDM = RORSTAT_PIDM AND M.RBRAPBG_PERIOD = :SMR AND M.RBRAPBG_RUN_NAME = 'ACTUAL'
LEFT JOIN RBRAPBG F ON F.RBRAPBG_PIDM = RORSTAT_PIDM AND F.RBRAPBG_PERIOD = :FALL AND F.RBRAPBG_RUN_NAME = 'ACTUAL'
LEFT JOIN RBRAPBG S ON S.RBRAPBG_PIDM = RORSTAT_PIDM AND S.RBRAPBG_PERIOD = :SPR AND S.RBRAPBG_RUN_NAME = 'ACTUAL'
WHERE RORSTAT_AIDY_CODE = :AIDY
AND (M.RBRAPBG_PBGP_CODE = 'XDISS2' OR F.RBRAPBG_PBGP_CODE = 'XDISS2' OR S.RBRAPBG_PBGP_CODE = 'XDISS2')
AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z WHERE Z.SGBSTDN_PIDM = RORSTAT_PIDM AND Z.SGBSTDN_TERM_CODE_EFF <= :SPR)
AND SGBSTDN_STST_CODE = 'AS'