-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT FLOOR(MONTHS_BETWEEN(sysdate, SPBPERS_BIRTH_DATE)/12) AGE,
RPRAWRD_FUND_CODE, M.RPRATRM_OFFER_AMT SMR_OFFER, M.RPRATRM_PAID_AMT SMR_PAID, M.RPRATRM_PAID_DATE SMR_DISB_DATE,
F.RPRATRM_OFFER_AMT FALL_OFFER, F.RPRATRM_PAID_AMT FALL_PAID, F.RPRATRM_PAID_DATE FALL_PAID_DATE,
S.RPRATRM_OFFER_AMT SPR_OFFER,
RRRAREQ_TREQ_CODE OGSLSV, RRRAREQ_TRST_CODE OGSLSV_STATUS, RRRAREQ_FUND_CODE OGSLSV_FUND,
CSS.SCORE "Selective Service",
CASE
WHEN CSS.SCORE = 'F' THEN 'Female'
WHEN CSS.SCORE = 'I' THEN 'International Student'
WHEN CSS.SCORE = 'X' THEN 'Non-Ohio Resident'
WHEN CSS.SCORE = 'U' THEN 'Under 18 Years of Age'
WHEN CSS.SCORE = 'O' THEN 'Over 26 Years of Age'
WHEN CSS.SCORE = 'B' THEN 'Incarcerated'
WHEN CSS.SCORE = 'W' THEN 'One-term Waiver'
WHEN CSS.SCORE = 'C' THEN 'Compliant'
WHEN CSS.SCORE = 'N' THEN 'Non-compliant'
WHEN CSS.SCORE = 'H' THEN 'Exception List'
END "Selective Service Description",
SGAS.TERM SGASTDN_TERM_CODE_EFF, SGAS.RES RESIDENCY
FROM RPRAWRD
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM = RPRAWRD_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN SPBPERS ON SPBPERS_PIDM = RPRAWRD_PIDM
LEFT JOIN RPRATRM M ON M.RPRATRM_PIDM = RPRAWRD_PIDM AND M.RPRATRM_FUND_CODE = RPRAWRD_FUND_CODE AND M.RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE AND M.RPRATRM_PERIOD LIKE '%60'
LEFT JOIN RPRATRM F ON F.RPRATRM_PIDM = RPRAWRD_PIDM AND F.RPRATRM_FUND_CODE = RPRAWRD_FUND_CODE AND F.RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE AND F.RPRATRM_PERIOD LIKE '%80'
LEFT JOIN RPRATRM S ON S.RPRATRM_PIDM = RPRAWRD_PIDM AND S.RPRATRM_FUND_CODE = RPRAWRD_FUND_CODE AND S.RPRATRM_AIDY_CODE = RPRAWRD_AIDY_CODE AND S.RPRATRM_PERIOD LIKE '%10'
LEFT JOIN RRRAREQ ON RRRAREQ_PIDM = RPRAWRD_PIDM AND RRRAREQ_AIDY_CODE = RPRAWRD_AIDY_CODE AND RRRAREQ_TREQ_CODE = 'OGSLSV' AND NVL(RRRAREQ_FUND_CODE,RPRAWRD_FUND_CODE) = RPRAWRD_FUND_CODE
LEFT JOIN (SELECT SPRIDEN_PIDM PIDM, SORTEST_TEST_SCORE SCORE FROM SPRIDEN, SORTEST WHERE SORTEST_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL AND SORTEST_TESC_CODE = 'CSS' AND SORTEST_TEST_DATE = (SELECT MAX(Z.SORTEST_TEST_DATE) FROM SORTEST Z WHERE Z.SORTEST_PIDM = SPRIDEN_PIDM AND Z.SORTEST_TESC_CODE = 'CSS')) CSS ON CSS.PIDM = RPRAWRD_PIDM
LEFT JOIN (SELECT SPRIDEN_PIDM PIDM, SGBSTDN_TERM_CODE_EFF TERM, SGBSTDN_RESD_CODE RES FROM SGBSTDN, SPRIDEN WHERE SGBSTDN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z WHERE Z.SGBSTDN_PIDM = SPRIDEN_PIDM AND Z.SGBSTDN_TERM_CODE_EFF <= :SPR)) SGAS ON SGAS.PIDM = RPRAWRD_PIDM
WHERE RPRAWRD_AIDY_CODE = :AIDY
AND RPRAWRD_OFFER_AMT > 0
AND RPRAWRD_FUND_CODE IN (SELECT RFRTREQ_FUND_CODE FROM RFRTREQ WHERE RFRTREQ_AIDY_CODE = :AIDY AND RFRTREQ_FUND_CODE LIKE 'S%' AND RFRTREQ_TREQ_CODE = 'OGSLSV')
AND (RRRAREQ_TREQ_CODE IS NULL OR (RRRAREQ_SAT_IND = 'Y' AND CSS.SCORE IN ('N','E')) OR (RRRAREQ_SAT_IND = 'N' AND CSS.SCORE NOT IN ('N','E')) OR (RRRAREQ_SAT_IND = 'N' AND (NVL(S.RPRATRM_PAID_AMT,0) + NVL(F.RPRATRM_PAID_AMT,0) > 0)))
ORDER BY RPRAWRD_FUND_CODE