-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT SGBSTDN_TERM_CODE_EFF, SGBSTDN_STST_CODE, SGBSTDN_STYP_CODE, STVSTYP_DESC,
RCRAPP1_AIDY_CODE, RCRAPP3_YR_IN_COLL_2, RCRAPP1_DEGREE_BY_JULY, RCVEDEA_PURSUE_TEACH_CERT
FROM RCRAPP1
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM = RCRAPP1_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN RCVEDEA ON RCVEDEA_PIDM = RCRAPP1_PIDM AND RCVEDEA_INFC_CODE = RCRAPP1_INFC_CODE AND RCVEDEA_SEQ_NO = RCRAPP1_SEQ_NO AND RCVEDEA_AIDY_CODE = RCRAPP1_AIDY_CODE
LEFT JOIN RCRAPP3 ON RCRAPP1_PIDM = RCRAPP3_PIDM AND RCRAPP1_AIDY_CODE = RCRAPP3_AIDY_CODE AND RCRAPP1_INFC_CODE = RCRAPP3_INFC_CODE AND RCRAPP1_SEQ_NO = RCRAPP3_SEQ_NO
LEFT JOIN SGBSTDN ON SGBSTDN_PIDM = RCRAPP1_PIDM
LEFT JOIN STVSTYP ON STVSTYP_CODE = SGBSTDN_STYP_CODE
WHERE RCRAPP1_AIDY_CODE = '2425'
AND RCRAPP1_INFC_CODE = 'EDE'
AND RCRAPP1_CURR_REC_IND = 'Y'
AND RCVEDEA_PURSUE_TEACH_CERT = '1'
AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z WHERE Z.SGBSTDN_PIDM = RCRAPP1_PIDM AND Z.SGBSTDN_TERM_CODE_EFF <= '202510')