-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

WITH MaxRRRAREQDate AS (
SELECT RRRAREQ_PIDM, RRRAREQ_AIDY_CODE, MAX(RRRAREQ_STAT_DATE) AS MaxStatDate
FROM RRRAREQ
GROUP BY RRRAREQ_PIDM, RRRAREQ_AIDY_CODE)
SELECT DISTINCT RCRAPP3_GRANT_SCHOLAR_AID STU_GRANT_SCHOLAR_AID,
RCRAPP2_MODEL_CDE DEPEND,
RCRAPP1_PAR_US_INC PAR_AGI,
RCRAPP1_US_INC STU_AGI,
RORSTAT_PCKG_COMP_DATE PCKG,
RCRIRSF_PAR_IRS_REQUEST_FLAG PAR_IRS_FLAG,
RCRIRSF_IRS_REQUEST_FLAG STU_IRS_FLAG,
RORSTAT_TGRP_CODE TGRP,
RORSTAT_VER_DATE VERIF_DATE,
RCRAPP1_USED_TRANS_NO CURR_TRANS_NO,
RCRAPP4_PAR_TX_RET_FILED_IND PAR_TAX_FILED,
RCRAPP4_TX_RET_FILED_IND STU_TAX_FILED,
RCRAPP1_MRTL_STATUS MRTL_STATUS,
RRRAREQ_TRST_CODE VERIF_STATUS,
RRRAREQ_STAT_DATE VERIF_STAT_DATE
FROM RCRAPP1
LEFT JOIN SPRIDEN ON RCRAPP1_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN RORSTAT ON RCRAPP1_PIDM = RORSTAT_PIDM AND RCRAPP1_AIDY_CODE = RORSTAT_AIDY_CODE
LEFT JOIN MaxRRRAREQDate MRR ON RCRAPP1_PIDM = MRR.RRRAREQ_PIDM AND RCRAPP1_AIDY_CODE = MRR.RRRAREQ_AIDY_CODE
LEFT JOIN RRRAREQ ON RRRAREQ.RRRAREQ_PIDM = MRR.RRRAREQ_PIDM AND RRRAREQ.RRRAREQ_AIDY_CODE = MRR.RRRAREQ_AIDY_CODE AND RRRAREQ.RRRAREQ_STAT_DATE = MRR.MaxStatDate
LEFT JOIN RCRAPP2 ON RCRAPP1_PIDM = RCRAPP2_PIDM AND RCRAPP1_AIDY_CODE = RCRAPP2_AIDY_CODE AND RCRAPP1_INFC_CODE = RCRAPP2_INFC_CODE AND RCRAPP1_SEQ_NO = RCRAPP2_SEQ_NO
LEFT JOIN RCRAPP3 ON RCRAPP1_PIDM = RCRAPP3_PIDM AND RCRAPP1_AIDY_CODE = RCRAPP3_AIDY_CODE AND RCRAPP1_INFC_CODE = RCRAPP3_INFC_CODE AND RCRAPP1_SEQ_NO = RCRAPP3_SEQ_NO
LEFT JOIN RCRIRSF ON RCRAPP1_PIDM = RCRIRSF_PIDM AND RCRAPP1_AIDY_CODE = RCRIRSF_AIDY_CODE AND RCRAPP1_INFC_CODE = RCRIRSF_INFC_CODE AND RCRAPP1_SEQ_NO = RCRIRSF_SEQ_NO
LEFT JOIN RCRAPP4 ON RCRAPP1_PIDM = RCRAPP4_PIDM AND RCRAPP1_AIDY_CODE = RCRAPP4_AIDY_CODE AND RCRAPP1_INFC_CODE = RCRAPP4_INFC_CODE AND RCRAPP1_SEQ_NO = RCRAPP4_SEQ_NO
WHERE RCRAPP1_AIDY_CODE = '2425'
AND RCRAPP1_INFC_CODE = 'EDE'
AND RCRAPP1_CURR_REC_IND = 'Y'
AND RCRAPP3_GRANT_SCHOLAR_AID > 0
ORDER BY RCRAPP3_GRANT_SCHOLAR_AID DESC