-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT SGAS.TERM_CODE, SGAS.STYPE, SGAS.STYPE_DESC,

RRRAREQ_TREQ_CODE FASPRL, RRRAREQ_TRST_CODE FASPRL_STATUS, TRUNC(RRRAREQ_STAT_DATE) FASPRL_STAT_DATE,

RCVEDEA_PAR_KILLED_LINE_DUTY PAR_KILLED_LOD,

RCVAPPL_SEQ_NO ISIR_SEQ_NO, RCVAPPL_USED_TRANS_NO ISIR_TRANS_NO, TRUNC(RCVAPPL_CREATE_DATE) ISIR_CREATE_DATE,

CASE
WHEN TRUNC(RCVAPPL_CREATE_DATE) > TRUNC(RRRAREQ_STAT_DATE)
THEN 'Y'
ELSE 'N'
END NEW_TRANSACTION,

(SELECT DISTINCT SFRTHST_TMST_CODE
FROM SFRTHST
WHERE SFRTHST_PIDM = RRRAREQ_PIDM
AND SFRTHST_TERM_CODE = :SMR
AND SFRTHST_TMST_DATE = 
    (SELECT MAX(Z.SFRTHST_TMST_DATE)
    FROM SFRTHST Z
    WHERE Z.SFRTHST_PIDM = RRRAREQ_PIDM
    AND Z.SFRTHST_TERM_CODE = :SMR)) SMR_TMST,
    
(SELECT DISTINCT SFRTHST_TMST_CODE
FROM SFRTHST
WHERE SFRTHST_PIDM = RRRAREQ_PIDM
AND SFRTHST_TERM_CODE = :FALL
AND SFRTHST_TMST_DATE = 
    (SELECT MAX(Z.SFRTHST_TMST_DATE)
    FROM SFRTHST Z
    WHERE Z.SFRTHST_PIDM = RRRAREQ_PIDM
    AND Z.SFRTHST_TERM_CODE = :FALL)) FALL_TMST,
    
    (SELECT DISTINCT SFRTHST_TMST_CODE
FROM SFRTHST
WHERE SFRTHST_PIDM = RRRAREQ_PIDM
AND SFRTHST_TERM_CODE = :SPR
AND SFRTHST_TMST_DATE = 
    (SELECT MAX(Z.SFRTHST_TMST_DATE)
    FROM SFRTHST Z
    WHERE Z.SFRTHST_PIDM = RRRAREQ_PIDM
    AND Z.SFRTHST_TERM_CODE = :SPR)) SPR_TMST,
    
FLOOR(MONTHS_BETWEEN(sysdate, RCRAPP1_BIRTH_DATE)/12) AGE,

PR_FASPRL.AIDY PRIOR_AIDY, PR_FASPRL.TREQ PRIOR_FASPRL, PR_FASPRL.TRST PRIOR_FASPRL_STATUS,

RHRCOMM_CATEGORY_CODE RHACOMM, RHRCOMM_ACTIVITY_DATE RHACOMM_ACTIVITY_DATE,

RCRESAR_PELL_ELGBL PELL_ELIGIBILITY_FLAG, RCVEDEA_MAXIMUM_PELL_IND MAX_PELL_IND, RCVEDEA_MINIMUM_PELL_IND MIN_PELL_IND

FROM RRRAREQ

LEFT JOIN SPRIDEN
ON SPRIDEN_PIDM = RRRAREQ_PIDM
AND SPRIDEN_CHANGE_IND IS NULL

LEFT JOIN RCVAPPL
ON RCVAPPL_PIDM = RRRAREQ_PIDM
AND RCVAPPL_AIDY_CODE = RRRAREQ_AIDY_CODE
AND RCVAPPL_INFC_CODE = 'EDE'
AND RCVAPPL_CURR_REC_IND = 'Y'

LEFT JOIN SPBPERS
ON SPBPERS_PIDM = RRRAREQ_PIDM

LEFT JOIN RCRAPP1
ON RCRAPP1_PIDM = RRRAREQ_PIDM
AND RCRAPP1_AIDY_CODE = RRRAREQ_AIDY_CODE
AND RCRAPP1_INFC_CODE = 'EDE'
AND RCRAPP1_CURR_REC_IND = 'Y'

LEFT JOIN RCVEDEA
ON RCVEDEA_PIDM = RRRAREQ_PIDM
AND RCVEDEA_AIDY_CODE = RRRAREQ_AIDY_CODE
AND RCVEDEA_INFC_CODE = RCRAPP1_INFC_CODE
AND RCVEDEA_SEQ_NO = RCRAPP1_SEQ_NO

LEFT JOIN RCRESAR
ON RCRESAR_PIDM = RRRAREQ_PIDM
AND RCRESAR_AIDY_CODE = RRRAREQ_AIDY_CODE
AND RCRESAR_INFC_CODE = RCRAPP1_INFC_CODE
AND RCRESAR_SEQ_NO = RCRAPP1_SEQ_NO

LEFT JOIN RHRCOMM
ON RHRCOMM_PIDM = RRRAREQ_PIDM
AND RHRCOMM_AIDY_CODE = RRRAREQ_AIDY_CODE
AND RHRCOMM_CATEGORY_CODE = 'FASPRL'

LEFT JOIN
(SELECT RRRAREQ_PIDM PIDM, RRRAREQ_AIDY_CODE AIDY, RRRAREQ_TREQ_CODE TREQ, RRRAREQ_TRST_CODE TRST
FROM RRRAREQ, SPRIDEN
WHERE RRRAREQ_TREQ_CODE = 'FASPRL'
AND RRRAREQ_PIDM = SPRIDEN_PIDM
AND SPRIDEN_CHANGE_IND IS NULL
AND RRRAREQ_AIDY_CODE =
    (SELECT MAX(Z.RRRAREQ_AIDY_CODE)
    FROM RRRAREQ Z
    WHERE Z.RRRAREQ_PIDM = SPRIDEN_PIDM
    AND Z.RRRAREQ_TREQ_CODE = 'FASPRL')) PR_FASPRL
ON PR_FASPRL.PIDM = RRRAREQ_PIDM

LEFT JOIN
(SELECT SGBSTDN_PIDM PIDM, SGBSTDN_TERM_CODE_EFF TERM_CODE, SGBSTDN_STYP_CODE STYPE, STVSTYP_DESC STYPE_DESC
FROM SGBSTDN, SPRIDEN, STVSTYP
WHERE SGBSTDN_PIDM = SPRIDEN_PIDM
AND SGBSTDN_STYP_CODE = STVSTYP_CODE
AND SPRIDEN_CHANGE_IND IS NULL
AND SGBSTDN_TERM_CODE_EFF =
    (SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Z
     WHERE Z.SGBSTDN_PIDM = SPRIDEN_PIDM)) SGAS
ON SGAS.PIDM = RRRAREQ_PIDM

WHERE RRRAREQ_TREQ_CODE = 'FASPRL'
AND RRRAREQ_AIDY_CODE = :AIDY
ORDER BY RRRAREQ_TRST_CODE, RHRCOMM_ACTIVITY_DATE DESC