-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from public output.
-- Schema fields used internally for joins/comparisons are retained where required by query logic.
-- Do not commit query results or exports containing student records.

SELECT RORSTAT_TGRP_CODE,
(SELECT DISTINCT 'Y'
FROM RCRESAR
WHERE RCRESAR_AIDY_CODE = RCRAPP1_AIDY_CODE
AND RCRESAR_PIDM = RCRAPP1_PIDM
AND RCRESAR_INFC_CODE = RCRAPP1_INFC_CODE
AND RCRESAR_SEQ_NO = RCRAPP1_SEQ_NO
AND (RCRESAR_COMM_CODE_01 = '278' OR RCRESAR_COMM_CODE_02 = '278' OR RCRESAR_COMM_CODE_03 = '278' OR RCRESAR_COMM_CODE_04 = '278' OR RCRESAR_COMM_CODE_05 = '278' OR RCRESAR_COMM_CODE_06 = '278' OR RCRESAR_COMM_CODE_07 = '278' OR RCRESAR_COMM_CODE_08 = '278' OR RCRESAR_COMM_CODE_09 = '278' OR RCRESAR_COMM_CODE_10 = '278' OR RCRESAR_COMM_CODE_11 = '278' OR RCRESAR_COMM_CODE_12 = '278' OR RCRESAR_COMM_CODE_13 = '278' OR RCRESAR_COMM_CODE_14 = '278' OR RCRESAR_COMM_CODE_15 = '278' OR RCRESAR_COMM_CODE_16 = '278' OR RCRESAR_COMM_CODE_17 = '278' OR RCRESAR_COMM_CODE_18 = '278' OR RCRESAR_COMM_CODE_19 = '278' OR RCRESAR_COMM_CODE_20 = '278')) CODE_278
FROM RCRAPP1
LEFT JOIN SPRIDEN ON SPRIDEN_PIDM = RCRAPP1_PIDM AND SPRIDEN_CHANGE_IND IS NULL
LEFT JOIN SPBPERS ON SPBPERS_PIDM = RCRAPP1_PIDM
LEFT JOIN RORSTAT ON RORSTAT_PIDM = RCRAPP1_PIDM AND RORSTAT_AIDY_CODE = RCRAPP1_AIDY_CODE
LEFT JOIN RCRESAR ON RCRESAR_AIDY_CODE = RCRAPP1_AIDY_CODE AND RCRESAR_PIDM = RCRAPP1_PIDM AND RCRESAR_INFC_CODE = RCRAPP1_INFC_CODE AND RCRESAR_SEQ_NO = RCRAPP1_SEQ_NO
WHERE RCRAPP1_AIDY_CODE = :AIDY
AND RCRAPP1_INFC_CODE = 'EDE'
AND RCRAPP1_CURR_REC_IND = 'Y'
AND (RCRESAR_COMM_CODE_01 = '278' OR RCRESAR_COMM_CODE_02 = '278' OR RCRESAR_COMM_CODE_03 = '278' OR RCRESAR_COMM_CODE_04 = '278' OR RCRESAR_COMM_CODE_05 = '278' OR RCRESAR_COMM_CODE_06 = '278' OR RCRESAR_COMM_CODE_07 = '278' OR RCRESAR_COMM_CODE_08 = '278' OR RCRESAR_COMM_CODE_09 = '278' OR RCRESAR_COMM_CODE_10 = '278' OR RCRESAR_COMM_CODE_11 = '278' OR RCRESAR_COMM_CODE_12 = '278' OR RCRESAR_COMM_CODE_13 = '278' OR RCRESAR_COMM_CODE_14 = '278' OR RCRESAR_COMM_CODE_15 = '278' OR RCRESAR_COMM_CODE_16 = '278' OR RCRESAR_COMM_CODE_17 = '278' OR RCRESAR_COMM_CODE_18 = '278' OR RCRESAR_COMM_CODE_19 = '278' OR RCRESAR_COMM_CODE_20 = '278')