WITH ocog_offered AS (
    SELECT DISTINCT RPRATRM_PIDM
    FROM RPRATRM
    WHERE RPRATRM_AIDY_CODE = :AIDY
      AND RPRATRM_PERIOD = :CUR_TRM
      AND RPRATRM_FUND_CODE IN ('GSNOCG','GSNOCX','GSNOCR','GSNO2E')
      AND RPRATRM_OFFER_AMT > 0
),

enrolled_students AS (
    SELECT DISTINCT SFRSTCR_PIDM,
        SUM(SFRSTCR_BILL_HR) AS TOTAL_BILLED_HOURS,
        SUM(CASE WHEN SFRSTCR_CAMP_CODE = 'KC' AND SFRSTCR_LEVL_CODE = 'UG' THEN SFRSTCR_BILL_HR ELSE 0 END) AS KC_BILLED,
        SUM(CASE WHEN SFRSTCR_CAMP_CODE <> 'KC' AND SFRSTCR_LEVL_CODE = 'UG' THEN SFRSTCR_BILL_HR ELSE 0 END) AS RC_BILLED
    FROM SFRSTCR 
    WHERE SFRSTCR_BILL_HR > 0
    AND SFRSTCR_TERM_CODE = :CUR_TRM
    GROUP BY SFRSTCR_PIDM),

joined_columns AS (
    SELECT
        DISTINCT RCRAPP1_PIDM,
        SPRIDEN_ID,
        SPRIDEN_LAST_NAME || ', ' || SPRIDEN_FIRST_NAME AS STUDENT_NAME,
        SPBPERS_SSN,
                 
        (SELECT SUM(TBRACCD_AMOUNT)
         FROM  TBRACCD
         WHERE TBRACCD_PIDM = RCRAPP1_PIDM
         AND   TBRACCD_TERM_CODE = :CUR_TRM        
         AND (TBRACCD_DETAIL_CODE LIKE 'T%'
         OR TBRACCD_DETAIL_CODE LIKE 'F%CS')) TUITION_AND_FEES,
         
        RCRAPP2_PELL_PGI                      PELL_PGI,      
        SGBSTDN_CAMP_CODE                     CAMPUS_ENROLLED,
        RCRAPP4_FISAP_INC                     BANNER_FISAP_INCOME,
        RNVAND0_UNMET_NEED                    BANNER_UNMET_NEED,
        TRUNC(RORSTAT_PCKG_COMP_DATE)         PCKG_COMP_DATE,
        RORSTAT_APRD_CODE                     AID_PERIOD,
        RORMESG_MESG_CODE                     MESSAGE,
        RORMESG_EXPIRATION_DATE               MESSAGE_EXP_DATE,
               
        CASE WHEN iprom.RPRATRM_OFFER_AMT > '0' THEN 'Y' ELSE 'N' END AS "I-PROMISE",
        
        tpell.RPRATRM_OFFER_AMT               PELL,   
        ssowoe.RPRATRM_OFFER_AMT              SSOWOE_OFFER_AMT,
        
        ts.RPRATRM_FUND_CODE TS_FUND,
        ts.RPRATRM_OFFER_AMT TS_FUND_OFFER_AMT,
        ts.RPRATRM_AWST_CODE TS_FUND_STATUS,
        
        gsnocg.RPRATRM_PERIOD, 
        gsnocg.RPRATRM_ORIG_OFFER_AMT OCOG_ORIG_OFFER,       
        gsnocg.RPRATRM_CANCEL_AMT OCOG_CNCL_AMT,     
        gsnocg.RPRATRM_LOCK_IND OCOG_AWARD_LOCKED, 
        
        fgf_smr.RPRATRM_FUND_CODE FGF_SMR_FUND,
        fgf_smr.RPRATRM_OFFER_AMT FGF_SMR_OFFER,
        fgf_fal.RPRATRM_FUND_CODE FGF_FALL_FUND,
        fgf_fal.RPRATRM_OFFER_AMT FGF_FALL_OFFER,
        fgf_spr.RPRATRM_FUND_CODE FGF_SPR_FUND,
        fgf_spr.RPRATRM_OFFER_AMT FGF_SPR_OFFER,
        
        gsno2e.RPRATRM_FUND_CODE GSNO2E_FUND,
        gsno2e.RPRATRM_OFFER_AMT GSNO2E_OFFER_AMT,
        gsno2e.RPRATRM_AWST_CODE GSNO2E_STATUS,
        
        gsnocx.RPRATRM_FUND_CODE GSNOCX_FUND,
        gsnocx.RPRATRM_OFFER_AMT GSNOCX_OFFER_AMT,
        gsnocx.RPRATRM_AWST_CODE GSNOCX_STATUS,
        
        gsnocr.RPRATRM_FUND_CODE GSNOCR_FUND,
        gsnocr.RPRATRM_OFFER_AMT GSNOCR_OFFER_AMT,
        gsnocr.RPRATRM_AWST_CODE GSNOCR_STATUS,
        
        pbg_smr.RBRAPBG_PBGP_CODE SMR_BUDG_GROUP,
        pbg_fal.RBRAPBG_PBGP_CODE FALL_BUDG_GROUP,
        pbg_spr.RBRAPBG_PBGP_CODE SPR_BUDG_GROUP,
        
        sap_smr.RORSAPR_SAPR_CODE SMR_SAP,
        sap_fal.RORSAPR_SAPR_CODE FALL_SAP,
        sap_spr.RORSAPR_SAPR_CODE SPR_SAP,
        
        ogslsv.RRRAREQ_TREQ_CODE OGSLSV_TREQ,
        ogslsv.RRRAREQ_TRST_CODE OGSLSV_STATUS,
        verif.RRRAREQ_TREQ_CODE VERIF_TREQ,
        verif.RRRAREQ_TRST_CODE VERIF_STATUS,
        uner.RRRAREQ_TREQ_CODE UNER_TREQ,
        uner.RRRAREQ_TRST_CODE UNER_STATUS,   
        advsxm.RRRAREQ_TREQ_CODE ADVSXM_TREQ,
        advsxm.RRRAREQ_TRST_CODE ADVSXM_STATUS,      
        advsxf.RRRAREQ_TREQ_CODE ADVSXF_TREQ,
        advsxf.RRRAREQ_TRST_CODE ADVSXF_STATUS,
        advsxs.RRRAREQ_TREQ_CODE ADVSXS_TREQ,
        advsxs.RRRAREQ_TRST_CODE ADVSXS_STATUS,
        zqa.RRRAREQ_TREQ_CODE ZQA_TREQ,
        zqa.RRRAREQ_TRST_CODE ZQA_STATUS,     
        zqa.RRRAREQ_SAT_IND ZQA_INDICATOR,
        certcit.RRRAREQ_TREQ_CODE CERTCIT_TREQ,
        certcit.RRRAREQ_TRST_CODE CERTCIT_STATUS,
        TRUNC(certcit.RRRAREQ_ACTIVITY_DATE) CERTCIT_DATE,
        fhcitc.RRRAREQ_TREQ_CODE FHCERTC_TREQ,
        fhcitc.RRRAREQ_TRST_CODE FHCERTC_STATUS,
        TRUNC(fhcitc.RRRAREQ_ACTIVITY_DATE) FHCERTC_DATE,
        hsch.RRRAREQ_TREQ_CODE HSCH_TREQ,
        hsch.RRRAREQ_TRST_CODE HSCH_STATUS,
        TRUNC(hsch.RRRAREQ_ACTIVITY_DATE) HSCH_DATE,              
        
        (SELECT SFRTHST_TMST_CODE
         FROM (
             SELECT SFRTHST_TMST_CODE
             FROM SFRTHST
             WHERE SFRTHST_PIDM = RCRAPP1_PIDM
               AND SFRTHST_TERM_CODE = :SMR_TRM
             ORDER BY SFRTHST_ACTIVITY_DATE DESC
         )
         WHERE ROWNUM = 1) AS SMR_TMST,

        (SELECT SFRTHST_TMST_CODE
         FROM (
             SELECT SFRTHST_TMST_CODE
             FROM SFRTHST
             WHERE SFRTHST_PIDM = RCRAPP1_PIDM
               AND SFRTHST_TERM_CODE = :FAL_TRM
             ORDER BY SFRTHST_ACTIVITY_DATE DESC
         )
         WHERE ROWNUM = 1) AS FAL_TMST,

        (SELECT SFRTHST_TMST_CODE
         FROM (
             SELECT SFRTHST_TMST_CODE
             FROM SFRTHST
             WHERE SFRTHST_PIDM = RCRAPP1_PIDM
               AND SFRTHST_TERM_CODE = :SPR_TRM
             ORDER BY SFRTHST_ACTIVITY_DATE DESC
         )
         WHERE ROWNUM = 1) AS SPR_TMST
                
    FROM RCRAPP1
       
    LEFT JOIN SPRIDEN 
    ON        SPRIDEN_PIDM = RCRAPP1_PIDM
    AND       SPRIDEN_CHANGE_IND IS NULL
                         
    LEFT JOIN SPBPERS 
    ON        SPBPERS_PIDM = RCRAPP1_PIDM
    
    LEFT JOIN SGBSTDN
    ON        SGBSTDN_PIDM = RCRAPP1_PIDM
    
    LEFT JOIN RCRAPP2
    ON      RCRAPP1_PIDM = RCRAPP2_PIDM
    AND     RCRAPP1_AIDY_CODE = RCRAPP2_AIDY_CODE
    AND     RCRAPP1_INFC_CODE = RCRAPP2_INFC_CODE
    AND     RCRAPP1_SEQ_NO = RCRAPP2_SEQ_NO
    
    LEFT JOIN RCRAPP4
    ON      RCRAPP4_PIDM = RCRAPP1_PIDM
    AND     RCRAPP1_AIDY_CODE = RCRAPP4_AIDY_CODE
    AND     RCRAPP1_INFC_CODE = RCRAPP4_INFC_CODE
    AND     RCRAPP1_SEQ_NO = RCRAPP4_SEQ_NO
    
    LEFT JOIN RNVAND0
    ON        RNVAND0_PIDM = RCRAPP1_PIDM
    AND       RNVAND0_AIDY_CODE = :AIDY
    
    LEFT JOIN RORSTAT
    ON        RORSTAT_PIDM = RCRAPP1_PIDM
    AND       RORSTAT_AIDY_CODE = :AIDY
    
    LEFT JOIN RPRATRM iprom
    ON  iprom.RPRATRM_PIDM = RCRAPP1_PIDM
    AND iprom.RPRATRM_PERIOD = :CUR_TRM
    AND iprom.RPRATRM_FUND_CODE IN ('SIMSPT','SIMSP3','SIMSP6','SIMSPB','SIMSPR')
    AND NVL(iprom.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RPRATRM tpell
    ON tpell.RPRATRM_PIDM = RCRAPP1_PIDM
    AND tpell.RPRATRM_PERIOD = :CUR_TRM
    AND tpell.RPRATRM_FUND_CODE = 'GFNPEL'
    AND NVL(tpell.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RPRATRM ssowoe
    ON ssowoe.RPRATRM_PIDM = RCRAPP1_PIDM
    AND ssowoe.RPRATRM_PERIOD = :CUR_TRM
    AND ssowoe.RPRATRM_FUND_CODE = 'SSOWOE'
    AND NVL(ssowoe.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RPRATRM ts
    ON ts.RPRATRM_PIDM = RCRAPP1_PIDM
    AND ts.RPRATRM_PERIOD = :CUR_TRM
    AND ts.RPRATRM_FUND_CODE IN ('SSOWOS','SSOGSA','WIWFWE','WIWFWO')
    AND NVL(ts.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RPRATRM gsnocg
    ON gsnocg.RPRATRM_PIDM = RCRAPP1_PIDM
    AND gsnocg.RPRATRM_PERIOD = :CUR_TRM
    AND gsnocg.RPRATRM_FUND_CODE = 'GSNOCG'
    AND NVL(gsnocg.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RPRATRM fgf_smr
    ON fgf_smr.RPRATRM_PIDM = RCRAPP1_PIDM
    AND fgf_smr.RPRATRM_PERIOD = :SMR_TRM
    AND fgf_smr.RPRATRM_FUND_CODE IN ('SIO8FG', 'SIO6FG', 'SIO4FG', 'SIO2FG', 'SIOFN8', 'SIOFN6', 
    'SIOFN4', 'SIOFN2','SIOFTE','SIOFT4','SIOFT2','SIOXN4','SIOXN2')
    AND NVL(fgf_smr.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RPRATRM fgf_fal
    ON fgf_fal.RPRATRM_PIDM = RCRAPP1_PIDM
    AND fgf_fal.RPRATRM_PERIOD = :FAL_TRM
    AND fgf_fal.RPRATRM_FUND_CODE IN ('SIO8FG', 'SIO6FG', 'SIO4FG', 'SIO2FG', 'SIOFN8', 'SIOFN6', 
    'SIOFN4', 'SIOFN2','SIOFTE','SIOFT4','SIOFT2','SIOXN4','SIOXN2')
    AND NVL(fgf_fal.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RPRATRM fgf_spr
    ON fgf_spr.RPRATRM_PIDM = RCRAPP1_PIDM
    AND fgf_spr.RPRATRM_PERIOD = :SPR_TRM
    AND fgf_spr.RPRATRM_FUND_CODE IN ('SIO8FG', 'SIO6FG', 'SIO4FG', 'SIO2FG', 'SIOFN8', 'SIOFN6', 
    'SIOFN4', 'SIOFN2','SIOFTE','SIOFT4','SIOFT2','SIOXN4','SIOXN2')
    AND NVL(fgf_spr.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RPRATRM gsno2e
    ON gsno2e.RPRATRM_PIDM = RCRAPP1_PIDM
    AND gsno2e.RPRATRM_PERIOD = :CUR_TRM
    AND gsno2e.RPRATRM_FUND_CODE = 'GSNO2E'
    AND NVL(gsno2e.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RPRATRM gsnocx
    ON gsnocx.RPRATRM_PIDM = RCRAPP1_PIDM
    AND gsnocx.RPRATRM_PERIOD = :CUR_TRM
    AND gsnocx.RPRATRM_FUND_CODE = 'GSNOCX'
    AND NVL(gsnocx.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RPRATRM gsnocr
    ON gsnocr.RPRATRM_PIDM = RCRAPP1_PIDM
    AND gsnocr.RPRATRM_PERIOD = :CUR_TRM
    AND gsnocr.RPRATRM_FUND_CODE = 'GSNOCR'
    AND NVL(gsnocr.RPRATRM_OFFER_AMT, 0) > 0
    
    LEFT JOIN RBRAPBG pbg_smr
    ON pbg_smr.RBRAPBG_PIDM = RCRAPP1_PIDM
    AND pbg_smr.RBRAPBG_RUN_NAME = 'ACTUAL'
    AND pbg_smr.RBRAPBG_AIDY_CODE = :AIDY
    AND pbg_smr.RBRAPBG_PERIOD = :SMR_TRM
    
    LEFT JOIN RBRAPBG pbg_fal
    ON pbg_fal.RBRAPBG_PIDM = RCRAPP1_PIDM
    AND pbg_fal.RBRAPBG_RUN_NAME = 'ACTUAL'
    AND pbg_fal.RBRAPBG_AIDY_CODE = :AIDY
    AND pbg_fal.RBRAPBG_PERIOD = :FAL_TRM
    
    LEFT JOIN RBRAPBG pbg_spr
    ON pbg_spr.RBRAPBG_PIDM = RCRAPP1_PIDM
    AND pbg_spr.RBRAPBG_RUN_NAME = 'ACTUAL'
    AND pbg_spr.RBRAPBG_AIDY_CODE = :AIDY
    AND pbg_spr.RBRAPBG_PERIOD = :SPR_TRM
    
    LEFT JOIN RORSAPR sap_smr
    ON sap_smr.RORSAPR_PIDM = RCRAPP1_PIDM
    AND sap_smr.RORSAPR_TERM_CODE = :SMR_TRM
    
    LEFT JOIN RORSAPR sap_fal
    ON sap_fal.RORSAPR_PIDM = RCRAPP1_PIDM
    AND sap_fal.RORSAPR_TERM_CODE = :FAL_TRM
    
    LEFT JOIN RORSAPR sap_spr
    ON sap_spr.RORSAPR_PIDM = RCRAPP1_PIDM
    AND sap_spr.RORSAPR_TERM_CODE = :SPR_TRM
    
    LEFT JOIN RRRAREQ ogslsv
    ON ogslsv.RRRAREQ_PIDM = RCRAPP1_PIDM
    AND ogslsv.RRRAREQ_AIDY_CODE = :AIDY
    AND ogslsv.RRRAREQ_TREQ_CODE = 'OGSLSV'
    
    LEFT JOIN RRRAREQ verif
    ON verif.RRRAREQ_PIDM = RCRAPP1_PIDM
    AND verif.RRRAREQ_AIDY_CODE = :AIDY
    AND verif.RRRAREQ_TREQ_CODE = 'VERIF'
    
    LEFT JOIN RRRAREQ uner
    ON uner.RRRAREQ_PIDM = RCRAPP1_PIDM
    AND uner.RRRAREQ_AIDY_CODE = :AIDY
    AND uner.RRRAREQ_TREQ_CODE = 'UNER'
    
    LEFT JOIN RRRAREQ advsxm
    ON advsxm.RRRAREQ_PIDM = RCRAPP1_PIDM
    AND advsxm.RRRAREQ_AIDY_CODE = :AIDY
    AND advsxm.RRRAREQ_TREQ_CODE = 'ADVSXM'
    
    LEFT JOIN RRRAREQ advsxf
    ON advsxf.RRRAREQ_PIDM = RCRAPP1_PIDM
    AND advsxf.RRRAREQ_AIDY_CODE = :AIDY
    AND advsxf.RRRAREQ_TREQ_CODE = 'ADVSXF'
    
    LEFT JOIN RRRAREQ advsxs
    ON advsxs.RRRAREQ_PIDM = RCRAPP1_PIDM
    AND advsxs.RRRAREQ_AIDY_CODE = :AIDY
    AND advsxs.RRRAREQ_TREQ_CODE = 'ADVSXS'
    
    LEFT JOIN RRRAREQ zqa
    ON zqa.RRRAREQ_PIDM = RCRAPP1_PIDM
    AND zqa.RRRAREQ_AIDY_CODE = :AIDY
    AND zqa.RRRAREQ_TREQ_CODE = 'ZQA'
    
    LEFT JOIN RRRAREQ certcit
    ON certcit.RRRAREQ_PIDM = RCRAPP1_PIDM
    AND certcit.RRRAREQ_AIDY_CODE = :AIDY
    AND certcit.RRRAREQ_TREQ_CODE = 'CERTCIT'
    
    LEFT JOIN RRRAREQ fhcitc
    ON fhcitc.RRRAREQ_PIDM = RCRAPP1_PIDM
    AND fhcitc.RRRAREQ_AIDY_CODE = :AIDY
    AND fhcitc.RRRAREQ_TREQ_CODE = 'FHCITC'
    
    LEFT JOIN RRRAREQ hsch
    ON hsch.RRRAREQ_PIDM = RCRAPP1_PIDM
    AND hsch.RRRAREQ_AIDY_CODE = :AIDY
    AND hsch.RRRAREQ_TREQ_CODE = 'HSCH'    
    
    LEFT JOIN RORMESG
    ON        RORMESG_PIDM = RCRAPP1_PIDM
    AND       RORMESG_AIDY_CODE = :AIDY
    AND      (RORMESG_MESG_CODE LIKE 'GO%'
           OR RORMESG_MESG_CODE = 'RRNC'
           OR RORMESG_MESG_CODE = 'OSLS')
    AND       RORMESG_EXPIRATION_DATE > sysdate
                                               
    WHERE   RCRAPP1_AIDY_CODE = :AIDY
    AND     RCRAPP1_INFC_CODE = 'EDE'
    AND     RCRAPP1_CURR_REC_IND = 'Y'
    AND     SGBSTDN_TERM_CODE_EFF =
           (SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
                  FROM SGBSTDN Y
                 WHERE Y.SGBSTDN_PIDM = RCRAPP1_PIDM
                   AND Y.SGBSTDN_TERM_CODE_EFF <= :CUR_TRM
                   AND Y.SGBSTDN_STST_CODE = 'AS')
    )

SELECT *

    FROM enrolled_students
    
    JOIN joined_columns ON enrolled_students.SFRSTCR_PIDM = joined_columns.RCRAPP1_PIDM
    
    WHERE enrolled_students.SFRSTCR_PIDM NOT IN (SELECT RPRATRM_PIDM FROM ocog_offered)
    
    ORDER BY joined_columns.STUDENT_NAME;
