SELECT ID, LNAME, FNAME, TERM, FUND, OFRD_AMT, ACPT_AMT, PD_AMT, LOCK_IND, DISB_OVRD,

            TBUGHRS_K, TBUGHRS_R, TBUGHRS_X, INST_GEN_UG,
            
            (CASE
    WHEN NVL(TBUGHRS_K,0) > 0 AND NVL(TBUGHRS_R,0) > 0 AND NVL(TBUGHRS_X,0) >= 12 AND ACPT_AMT <= 1600 AND ((INST_GEN_UG - 3698) >= 1600) THEN 'Y'
    WHEN NVL(TBUGHRS_K,0) > 0 AND NVL(TBUGHRS_R,0) > 0 AND NVL(TBUGHRS_X,0) BETWEEN 09 AND 11 AND ACPT_AMT <= 1200 AND ((INST_GEN_UG - 2773) >= 1200) THEN 'Y'
    WHEN NVL(TBUGHRS_K,0) > 0 AND NVL(TBUGHRS_R,0) > 0 AND NVL(TBUGHRS_X,0) BETWEEN 06 AND 08 AND ACPT_AMT <= 800 AND ((INST_GEN_UG - 1849) >= 800) THEN 'Y'
    WHEN NVL(TBUGHRS_K,0) > 0 AND NVL(TBUGHRS_R,0) > 0 AND NVL(TBUGHRS_X,0) BETWEEN 01 AND 05 AND ACPT_AMT <= 400 AND ((INST_GEN_UG - 925) >= 400) THEN 'Y'    
        END) OK, 
        
        BURADJ, DFOVR, OCOGLMT, DUAL, TIME_STATUS, STATUS_DATE,
        
        
       (CASE
       WHEN STATUS_DATE >= SYSDATE-7
       THEN 'Y'
       END) STATUS_CHG,
       
       REG_ACTIVITY            
            
FROM
(
SELECT SPRIDEN_ID ID, SPRIDEN_LAST_NAME LNAME, SPRIDEN_FIRST_NAME FNAME, RPRATRM_PERIOD TERM,
        RPRATRM_FUND_CODE FUND, RPRATRM_OFFER_AMT OFRD_AMT, RPRATRM_ACCEPT_AMT ACPT_AMT, 
        RPRATRM_PAID_AMT PD_AMT, RPRATRM_LOCK_IND LOCK_IND, RPRATRM_OVERRIDE_DISB_RULE DISB_OVRD,
        
        (SELECT SUM(SFRSTCR_BILL_HR)
        FROM SFRSTCR
        WHERE SFRSTCR_PIDM = RPRATRM_PIDM
        AND     SFRSTCR_TERM_CODE = :TERM
        AND     SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2')
        AND     SFRSTCR_CAMP_CODE = 'KC'
        AND     SFRSTCR_LEVL_CODE = 'UG') TBUGHRS_K,
        
        (SELECT SUM(SFRSTCR_BILL_HR)
        FROM SFRSTCR
        WHERE SFRSTCR_PIDM = RPRATRM_PIDM
        AND     SFRSTCR_TERM_CODE = :TERM
        AND     SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2')
        AND     SFRSTCR_CAMP_CODE <> 'KC'
        AND     SFRSTCR_LEVL_CODE = 'UG') TBUGHRS_R,
        
        (SELECT SUM(SFRSTCR_BILL_HR)
        FROM SFRSTCR
        WHERE SFRSTCR_PIDM = RPRATRM_PIDM
        AND     SFRSTCR_TERM_CODE = :TERM
        AND     SFRSTCR_RSTS_CODE IN ('RE','RR','RW','R2')
        AND     SFRSTCR_LEVL_CODE = 'UG') TBUGHRS_X,
        
        (SELECT SUM(TBRACCD_AMOUNT)
FROM TBRACCD
WHERE TBRACCD_PIDM = RPRATRM_PIDM
AND TBRACCD_TERM_CODE = :TERM        
AND TBRACCD_DETAIL_CODE IN ('TDUX','TRDL','TDUW','TKUP','TKUX','TKUO','TKUU','TRUP','TRUX','TRUU','TRUO','TRWP','TRWX','TKUW','TKUJ',
'TKUI','TKUT','TRUJ','TRUW','TRUI','TRUT','TRWJ','TRWW','TSNX','TSNU','TSNW','TSNT','TR05','TSND','TSNF','TSNB','TSNA','TR04','TCAP',
'TCPR','TCAM','TKUD','TKUF','TKUB','TKUC','TKUE','TKUA','TRUD','TRUF','TRUB','TRWD','TRWF','TRWB','TRUC','TRUE','TRUA','FKCS','FRCS',
'FACS','TCPG','TCPI')
) INST_GEN_UG, 
        
        a.RHRCOMM_CATEGORY_CODE BURADJ, B.RHRCOMM_CATEGORY_CODE DFOVR, C.RHRCOMM_CATEGORY_CODE OCOGLMT, D.RHRCOMM_CATEGORY_CODE DUAL, 
        
        (SELECT (SFRTHST_TMST_CODE)
        FROM SFRTHST
        WHERE rownum = 1 
        AND SFRTHST_PIDM = RPRATRM_PIDM
        AND     SFRTHST_TERM_CODE = :TERM
        AND     SFRTHST_ACTIVITY_DATE =
                (SELECT MAX(SFRTHST_ACTIVITY_DATE)
                FROM SFRTHST Z
                WHERE Z.SFRTHST_PIDM = RPRATRM_PIDM
                AND   Z.SFRTHST_TERM_CODE = :TERM)) TIME_STATUS,
                

       (SELECT MAX(SFRTHST_ACTIVITY_DATE)
        FROM SFRTHST Z
       WHERE Z.SFRTHST_PIDM = RPRATRM_PIDM
        AND     Z.SFRTHST_TERM_CODE = :TERM) STATUS_DATE,
        
        
        (select DISTINCT 'Y'
        from sfrstcr
        where sfrstcr_pidm = rpratrm_pidm
        AND SFRSTCR_TERM_CODE = :TERM
        and sfrstcr_rsts_code in ('RE','RR','RW','R2')
        AND    TRUNC(SFRSTCR_ACTIVITY_DATE) > SYSDATE-7) REG_ACTIVITY
               
        

FROM RPRATRM

LEFT JOIN SPRIDEN
ON          RPRATRM_PIDM = SPRIDEN_PIDM
AND         SPRIDEN_CHANGE_IND IS NULL

left join rhrcomm a
on      A.RHRCOMM_PIDM = RPRATRM_PIDM
AND     A.RHRCOMM_AIDY_CODE = :AIDY
AND     a.RHRCOMM_CATEGORY_CODE	= 'BURADJ'

left join rhrcomm B
on      B.RHRCOMM_PIDM = RPRATRM_PIDM
AND     B.RHRCOMM_AIDY_CODE = :AIDY
AND     B.RHRCOMM_CATEGORY_CODE	= 'DFOVR'

left join rhrcomm C
on      C.RHRCOMM_PIDM = RPRATRM_PIDM
AND     C.RHRCOMM_AIDY_CODE = :AIDY
AND     C.RHRCOMM_CATEGORY_CODE	= 'OCOGLMT'

left join rhrcomm D
on      D.RHRCOMM_PIDM = RPRATRM_PIDM
AND     D.RHRCOMM_AIDY_CODE = :AIDY
AND     D.RHRCOMM_CATEGORY_CODE	= 'DUAL'

WHERE RPRATRM_FUND_CODE IN ('GSNOCG', 'GSNO2E', 'GSNOCX', 'GSNOCR')
AND     RPRATRM_OFFER_AMT > 0
AND     RPRATRM_PERIOD = :TERM

)

WHERE NVL(TBUGHRS_K,0) > 0
AND     NVL(TBUGHRS_R,0) >0
