SELECT DISTINCT SPRIDEN_ID             ID,
       SPRIDEN_LAST_NAME      LNAME,
       SPRIDEN_FIRST_NAME     FNAME,
       SPBPERS_BIRTH_DATE     BIRTHDATE,
       RRRAREQ_TREQ_CODE      TREQ,
       RRRAREQ_TRST_CODE      TREQ_STATUS,
       SORTEST_TESC_CODE      TESC_CODE,
       SORTEST_TEST_SCORE     TEST_SCORE,
       RPRATRM_FUND_CODE      FUND,
       RPRATRM_PERIOD         FUND_PERIOD
       
  FROM RRRAREQ
       LEFT JOIN SPRIDEN 
       ON SPRIDEN_PIDM = RRRAREQ_PIDM
       AND SPRIDEN_CHANGE_IND IS NULL
       
       LEFT JOIN SORTEST 
       ON RRRAREQ_PIDM = SORTEST_PIDM
       
       LEFT JOIN RPRATRM
       ON RPRATRM_PIDM = RRRAREQ_PIDM 
       --AND RPRATRM_PERIOD = RRRAREQ_PERIOD
       
       LEFT JOIN SPBPERS
       ON SPRIDEN_PIDM = SPBPERS_PIDM
           
 WHERE     RRRAREQ_AIDY_CODE = :AIDY
       AND RRRAREQ_TREQ_CODE = 'OGSLSV'
       --AND RRRAREQ_SAT_IND = 'Y'
       
       AND SORTEST_TESC_CODE = 'CSS'
       AND NVL (SORTEST_TEST_SCORE, 'N') IN ('E', 'N')
       AND SORTEST_ACTIVITY_DATE =
           (SELECT MAX (SORTEST_ACTIVITY_DATE)
              FROM SORTEST X
             WHERE     X.SORTEST_PIDM = RRRAREQ_PIDM
                   AND X.SORTEST_TESC_CODE = 'CSS')
                   
       AND RPRATRM_AIDY_CODE = :AIDY
       AND RPRATRM_FUND_CODE LIKE '_S%'
       AND RPRATRM_OFFER_AMT > 0
       
       ORDER BY 1
