-- SANITIZED PUBLIC VERSION
-- Direct student identifiers and hard-coded student data have been removed from report output.
-- Literal student ID/SSN lists have been replaced with bind parameters where applicable.
-- Schema fields may remain internally where required for joins or comparison logic.
-- Do not commit query results or exports containing student records.

Select * from 
(Select RORSTAT_APRD_CODE, RORSTAT_PCKG_COMP_DATE,

(Select SFRTHST_TMST_CODE
from SFRTHST
where RORSTAT_PIDM = SFRTHST_PIDM
and SFRTHST_TERM_CODE = '201860'
and SFRTHST_TMST_DATE = 
    (Select MAX(A.SFRTHST_TMST_DATE)
    from SFRTHST A
    where RORSTAT_PIDM = A.SFRTHST_PIDM
    and A.SFRTHST_TERM_CODE = '201860')) SMR_TMST, 
    
    robusdf_value_201 UDF_201, ROBUSDF_VALUE_202 UDF_202, ROBUSDF_VALUE_203 UDF_203, ROBUSDF_VALUE_204 UDF_204, ROBUSDF_VALUE_205 UDF_205, ROBUSDF_VALUE_206 UDF_206, ROBUSDF_VALUE_207 UDF_207,

    robusdf_value_222 UDF_222, ROBUSDF_VALUE_223 UDF_223, ROBUSDF_VALUE_224 UDF_224, ROBUSDF_VALUE_225 UDF_225, ROBUSDF_VALUE_226 UDF_226, ROBUSDF_VALUE_227 UDF_227, RCRAPP2_PELL_PGI,
    
    RRRAREQ_TREQ_CODE ENRCFA, RRRAREQ_TRST_CODE ENRCFA_STATUS, A.RORSAPR_SAPR_CODE SMR_SAP, B.RORSAPR_SAPR_CODE FALL_SAP, C.RORSAPR_SAPR_CODE SPR_SAP

from RORSTAT
LEFT JOIN ROBUSDF
ON          RORSTAT_PIDM = ROBUSDF_PIDM
AND         RORSTAT_AIDY_CODE = ROBUSDF_AIDY_CODE

LEFT JOIN RRRAREQ
ON          RORSTAT_PIDM = RRRAREQ_PIDM
AND         RORSTAT_AIDY_CODE = RRRAREQ_AIDY_CODE
AND         RRRAREQ_TREQ_CODE = 'ENRCFA'

left join RCRAPP2
on RORSTAT_PIDM = RCRAPP2_PIDM
and RCRAPP2_INFC_CODE = 'EDE'
and RCRAPP2_AIDY_CODE = RORSTAT_AIDY_CODE

left join RORSAPR A
on RORSTAT_PIDM = A.RORSAPR_PIDM
and A.RORSAPR_TERM_CODE = '201860'

left join RORSAPR B
on RORSTAT_PIDM = B.RORSAPR_PIDM
and B.RORSAPR_TERM_CODE = '201880'

left join RORSAPR C
on RORSTAT_PIDM = C.RORSAPR_PIDM
and C.RORSAPR_TERM_CODE = '201910'

where RORSTAT_AIDY_CODE = '1819'
and RORSTAT_APRD_CODE in ('FA/SPR','FALL','SPRING')
and RORSTAT_PCKG_COMP_DATE is not null
)
where SMR_TMST is not null
and SMR_TMST <> '00'
