Select * from (



SELECT SPRIDEN_ID, SPRIDEN_LAST_NAME LNAME, SPRIDEN_FIRST_NAME FNAME,

(Select SGBSTDN_STYP_CODE
from SGBSTDN
where  GLBEXTR_KEY = SGBSTDN_PIDM
and SGBSTDN_TERM_CODE_EFF =
                (Select MAX(A.SGBSTDN_TERM_CODE_EFF)
                from SGBSTDN A
                where A.SGBSTDN_PIDM =  GLBEXTR_KEY
                and A.SGBSTDN_TERM_CODE_EFF <='202380')) STU_TYPE,
                
 (SELECT SUM(SFRSTCR_CREDIT_HR)
        FROM SFRSTCR A
        WHERE A.SFRSTCR_PIDM =  GLBEXTR_KEY
        and     a.sfrstcr_term_code = '202360'
        AND    A.SFRSTCR_RSTS_CODE IN ('RR','RE','RW','R2')) SMR_HRS
        

FROM GLBEXTR

LEFT JOIN SPRIDEN
ON          GLBEXTR_KEY = SPRIDEN_PIDM
AND         SPRIDEN_CHANGE_IND IS NULL

LEFT JOIN RPRATRM
ON          GLBEXTR_KEY = RPRATRM_PIDM
AND         RPRATRM_AIDY_CODE = '2324'
AND         RPRATRM_PERIOD = '202380'
AND         RPRATRM_FUND_CODE = 'GFNPEL'


WHERE glbextr_application = 'FINAID'
AND     GLBEXTR_SELECTION = 'FA_TRANSFER_MONITOR_ADD'
AND     GLBEXTR_USER_ID = 'ECRAWLE1'
AND     GLBEXTR_CREATOR_ID = 'ECRAWLE1'
--and     RPRATRM_ACCEPT_AMT > 0
)

where SMR_HRS > 0

