SELECT DISTINCT
       SPRIDEN_ID,
       SPBPERS_SSN,
       SPBPERS_BIRTH_DATE,
       SPRIDEN_LAST_NAME,
       SPRIDEN_FIRST_NAME,
       RORHOLD_HOLD_CODE,
       RORHOLD_AIDY_CODE,
       RORHOLD_PERIOD,
       RORHOLD_FROM_DATE,
       RORHOLD_TO_DATE,
       RORHOLD_USER_ID           RORHOLD_USER,
       RORMESG_MESG_CODE,    
       A.RHRCOMM_CATEGORY_CODE   TA_RHACOMM,
       A.RHRCOMM_ACTIVITY_DATE   TA_RHACOMM_DATE,
       A.RHRCOMM_COMMENT         TA_COMMENT,
       B.RHRCOMM_CATEGORY_CODE   TMCLR_RHACOMM,
       B.RHRCOMM_ACTIVITY_DATE   TMCLR_RHACOMM_DATE,
       C.RHRCOMM_CATEGORY_CODE   TMAID_RHACOMM,
       C.RHRCOMM_ACTIVITY_DATE   TMAID_RHCAOMM_DATE,
       C.RHRCOMM_COMMENT         TMAID_COMMENT,
       (SELECT SGBSTDN_STYP_CODE
          FROM SGBSTDN
         WHERE     RORHOLD_PIDM = SGBSTDN_PIDM
               AND SGBSTDN_TERM_CODE_EFF =
                   (SELECT MAX (A.SGBSTDN_TERM_CODE_EFF)
                      FROM SGBSTDN A
                     WHERE A.SGBSTDN_PIDM = RORHOLD_PIDM))   MAX_STU_TYPE,
       (SELECT MAX (B.SGBSTDN_TERM_CODE_EFF)
          FROM SGBSTDN B
         WHERE     B.SGBSTDN_PIDM = RORHOLD_PIDM
               AND B.SGBSTDN_TERM_CODE_EFF <= :SPR_TRM)      MAX_SGASTDN_TERM,
       (SELECT SFRTHST_TMST_CODE
          FROM SFRTHST
         WHERE     RORHOLD_PIDM = SFRTHST_PIDM
               AND SFRTHST_TERM_CODE = :SPR_TRM
               AND SFRTHST_TMST_DATE =
                   (SELECT MAX (A.SFRTHST_TMST_DATE)
                      FROM SFRTHST A
                     WHERE     A.SFRTHST_TERM_CODE = :SPR_TRM
                           AND A.SFRTHST_PIDM = RORHOLD_PIDM))  SPR_TIME_STATUS,
       SHRDGMR_TERM_CODE_GRAD    GRAD_TERM,
       shrdgmr_degs_code,
       SHRDGMR_LEVL_CODE,
       SHRDGMR_DEGC_CODE
  
  FROM RORHOLD
       LEFT JOIN SPRIDEN
           ON RORHOLD_PIDM = SPRIDEN_PIDM 
           AND SPRIDEN_CHANGE_IND IS NULL
           
       LEFT JOIN SPBPERS 
       ON SPBPERS_PIDM = RORHOLD_PIDM
       
       LEFT JOIN RHRCOMM A
           ON     A.RHRCOMM_PIDM = RORHOLD_PIDM
              AND A.RHRCOMM_AIDY_CODE = :AIDY
              AND A.RHRCOMM_CATEGORY_CODE = 'TA'
              
       LEFT JOIN RHRCOMM B
           ON     B.RHRCOMM_PIDM = RORHOLD_PIDM
              AND B.RHRCOMM_AIDY_CODE = :AIDY
              AND B.RHRCOMM_CATEGORY_CODE = 'TMCLR'
              
       LEFT JOIN RHRCOMM C
           ON     C.RHRCOMM_PIDM = RORHOLD_PIDM
              AND C.RHRCOMM_AIDY_CODE = :AIDY
              AND C.RHRCOMM_CATEGORY_CODE = 'TMAID'
              
       LEFT JOIN RORMESG
           ON     RORMESG_PIDM = RORHOLD_PIDM
              AND RORMESG_AIDY_CODE = RORHOLD_AIDY_CODE
              AND RORMESG_MESG_CODE IN ('LDTP', 'LDTD')
              
       LEFT JOIN SHRDGMR
           ON     RORHOLD_PIDM = SHRDGMR_PIDM
              AND SHRDGMR_TERM_CODE_GRAD IN ( :SUM_TRM, :FAL_TRM, :SPR_TRM)
              AND shrdgmr_degs_code IN ('PN', 'AW')
              
 WHERE     RORHOLD_HOLD_CODE = 'TS'
       AND (   RORHOLD_AIDY_CODE = :AIDY
            OR RORHOLD_PERIOD IN ( :SUM_TRM, :FAL_TRM, :SPR_TRM))
